apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert-logs
  namespace: observability
spec:
  evaluationInterval: "10s"
  nodeSelector:
    node_pool: observability-resources
  ruleSelector:
    matchLabels:
      is_logs: "true"
  datasource:
    url: http://victorialogs-server.observability.svc.cluster.local:9428
  notifiers:
    - selector:
        namespaceSelector:
          matchNames:
            - observability
  remoteRead:
    url: http://vmsingle-vm.observability.svc.cluster.local:8429
  remoteWrite:
    url: http://vmsingle-vm.observability.svc.cluster.local:8429
