# TODO: Seal this secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubescape-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: kubescape-infra
      namespace: security
