apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - service-lb.yaml
  - securityadmin-patch-job.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - syslog-tls.yaml
