apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: false
  datasource:
    isDefault: true
    access: proxy
    database: prometheus
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: VictoriaMetrics
    type: prometheus
    url: http://vmsingle-vm-victoria-metrics-k8s-stack.observability.svc.cluster.local:8429