---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-google-chat-webhook
  namespace: security
spec:
  encryptedData:
    WAZUH_GOOGLE_CHAT_WEBHOOK_URL: AgA7ZZJugZrVJnW/pCpqhbljPYXtChwPveQ/Iyew+xyX9iJ5S6jYpNlORk3ry+O64bFpt5zFr28m2f2q2TBBcEDmODLA3nHmCt657B0nsjg33x86406nOREx5EM54LyBrWKBvV+H7sHTdZrIpZBAWdbC3zE/F0a18/HqqVBW7kkanTFwHqcxuQyukEZLFd56mdzwzeB9p2JUER5R8hsKRJqJTIwIhSCPXXoCvEDYEKgX/Udqx071FW1xp+RbF8W7P0lgXKskhtRbyHhSpf1/URLqNesXk5r3XP+1f5e5wrdWm5MMhrg45vcGiytSppjOBbLPs6um8twj6c8+Zofj+zd0QI4/zkEmq1qAISXctXza1aIP9JMnnrKjtVtquDEbY3YALXstkNMB01tIEXp4HqTl5EhIJhgaQ1o9Ql34xrW/L+3mwimjsRjLSHVRZIfdfq8HClG/gIwkxGRHKK0C9mREQzaC8Ox3JSUya14obm0RNNmL1lsaKHt9fcRqiA9YfFy4lT9OaZL5zCLKPSv34rUflU3T1z+0soCsZ+orqecLjyjJ9zT6UUWtOrm7/f9SJsX7NTTePvzgfG9azbQvY3pMv+1bGUVXYDYm31qPX14IjiKMjCopvXOMGZrLsmo6PZ+ctNuuDTfC+DQu2X/IN1SfU1emnfIS7+J7j5nrlEWauVqN12KKECmU1MBZ6PtLioiqsukTGWBK85RAkp/6UdFsCDYiPMY+hvCiezU0HbI9nDwCvx39PD73OuvNdQvgyj1i+WVLCm8U+tR7FZNo6K8NQaNueLBzt5d+tiHcjAHZjDEkxIeejP0tRkZWz6UwodCs4tfxs35Gh5rPjx6KdFWgcyns6LDyZENV55S8iGE3njK/NOskYlDu1OsY+p84lxJwJepnmmBmGA==
  template:
    metadata:
      name: wazuh-google-chat-webhook
      namespace: security

