---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-google-chat-webhook
  namespace: security
spec:
  encryptedData:
    WAZUH_GOOGLE_CHAT_WEBHOOK_URL: AgAMrpu+1wpMkRjYGZeekqZu27J4iHHl2ElOA8Zv0UroikSfjiOq6Z2qPEWkujHfbW5lOAo2Ktzfq/jyGoziYb2lh1fArbhxnTWntsKNyKFjEo2dnNChgp5YOEJcmHDCvUVP6jme6E31YVHyg6I8WymJasm+Gxdecc/thc+0S3Aw2i6iRZhoEJC4eS7KbkZYoeALW6ZnrP7LYbPkJE0LlX2/G8IsJtCDRrsbRca1pQt39jjcpct/tdqeYKAzQiL0qrChliTT2ISlswyPhTIBlc3jFkof1V1YlppYzv7fp4Gcrezooqr8/BHBWR1KrpambVkONhd85ijUa7gfPBp6LH6VXMscQVQXl2ggOcDpEXNKxCwJo86dotPTVMEjh8IMcVt8ygDUWL/ZdCpWLHazVE4MeykNfjpwbSsoYwrmj2FobNEgWNCKJ9aDd+DDRT6cOAgni8ZopYdsfjURMX3AV9YwRyoyN6F/0WBy/zlsfoKqgrGqmkvfsp/igwNMo/P1wJFmVkH1E1FkL6BdnwiCuXpyjL5PlLwPlwtEE0yitLprqXK7rFav/YcDYJM+dhrASSS7kPZz3YOXmgow2o+rkj+xVpM/vW2lM/wOhkoReSGJK6QPB+mMfzVtuTntGeh+KNkdwybNQvRq4IjsiGg6lHP5LsLbVLA1bV2VOJ9Lk0fHzbNkw74v1SkasV6OuZAHOKYbUbl9dXM1cYlsNIsLoOFRnxbLW0q8PPYnU3I5w9bwN8umxxDsHeeFUl69hkRkA6y0G+vJMSENNXaUmbUMbJtgM8iDEZnkR3nZa15KtGrZseTDeP5ohvYxx6xUDY0SItucLMY8kF98C4YevaOZlestYWUPIOEbEGoZ/Rk6wsIoQpk9QAH9k6dgRa6SqfsfY7x///xiysx2WQ==
  template:
    metadata:
      name: wazuh-google-chat-webhook
      namespace: security
