apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubernetes-secret-generator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-secret-gen'
    spec:
      project: default
      source:
        chart: kubernetes-secret-generator
        repoURL: https://helm.mittwald.de
        targetRevision: 3.4.0
        helm:
          valuesObject:
            nodeSelector:
              node_pool: observability
      destination:
        server: "{{.server}}"
        namespace: secret-generator
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
