# TODO: Seal these secrets before deployment.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: kube-bench-infra
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: kube-bench-gcs-credentials
      namespace: security
