---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubescape-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAvbtFl4sFSX7Ohho3mzXOPjNhurQwOpvEYZGa2j35ZOShZDm37cpqBRPiJtg6Rrk7rjaG0RXrtXO3C8drRkGciInX3VEdYokeR0swkGCKoUwjvPC/FuVY41BvBG3FvFo3I4zILTjaHBrCHR2r6FvFsaq7XaXjwkdy1UqECKkQBMCKuCmQ9J01azEh7zXF7+ZSADLdFqFascn0rcatsQcD2sL8balolR/Z/coHLu2AW8BYDCXiMbxllILXDjQMj8mdCB1p2j23HHONIL1RKR5T8tRwtxOgBg2G1nahV4bzCtaVXD8dSrr3VsaBZOb5KONEzkKVTtCCLgVHAFNXmO3bHqDskqoSHyN1A3WQwBFH4cqSqU2ei8j/c7udPPN6fIfylo//APC5y3xf+By1Pc8HA1OR0VtRCLFXvp+ANDLTXuOwNW9PIMWx+7QEpNm72U55eLZN/fyUmK1uOKz7FUNejTN2XZ053yt77V96Hhicbgdqtwkzn/EB0uH5cgCtpIH4d2SIAyU3pchY+G5zGyzcx2s+mGwyDx6xTLpzvtlK+TKvX3yS99HKWJz196wdPHjNmj7/qJnq1dtm0S9Oi3EFYHUNGQM75ka+tMBSTVhI1ndRk8TsNWSWXvZOMxerKM/Cppdr5uyVgLIPC56Sw4dN0ENrJF7n1uiht3LMJCPwvCUtojVU8MlpkQ+6VlwJ1PamJBGW73pPnhN6OrJavjsSfL3wEQc7xMUpcEshLow==
  template:
    metadata:
      name: kubescape-infra
      namespace: security
