apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{substr 0 40 .name | replace "_" "-"}}-observability-stack'
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: 94-add-app-plane-observability-stack
        path: tofu/gcp/observability_stack/app_plane/argocd/manifests
      destination:
        server: "{{.server}}"
        namespace: default
      syncPolicy:
        automated: {}
