apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{substr 0 40 .name | replace "_" "-"}}-grafana-op'
    spec:
      project: default
      source:
        chart: grafana-operator
        repoURL: ghcr.io/grafana/helm-charts
        targetRevision: v5.16.0
        helm:
          valuesObject:
            fullnameOverride: grafana-operator
      destination:
        server: "{{.server}}"
        namespace: observability
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
