apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secret-generator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{substr 0 40 .name | replace "_" "-"}}-secret-gen'
    spec:
      project: default
      source:
        chart: kubernetes-secret-generator
        repoURL: https://helm.mittwald.de
        targetRevision: 3.4.0
        helm:
          valuesObject:
            fullnameOverride: secret-generator
      destination:
        server: "{{.server}}"
        namespace: observability
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
