apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{`{{substr 0 40 .name | replace "_" "-"}}`}}-victoriametrics'
    spec:
      project: default
      source:
        chart: victoria-metrics-operator
        repoURL: https://victoriametrics.github.io/helm-charts
        targetRevision: 0.40.4
        helm:
          releaseName: victoriametrics
          valuesObject: {}
      destination:
        server: "{{`{{.server}}`}}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
