apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{substr 0 40 .name | replace "_" "-"}}-victoriametrics'
    spec:
      project: default
      source:
        chart:  victoria-metrics-k8s-stack
        repoURL: https://victoriametrics.github.io/helm-charts
        targetRevision: 0.33.4
        helm:
          releaseName: vm
          valuesObject:
            defaultDashboards:
              enabled: false
            defaultRules:
              create: true
            vmsingle:
              spec:
                retentionPeriod: 3d
                logFormat: json
                nodeSelector:
                  node_pool: observability
            alertmanager:
              spec:
                nodeSelector:
                  node_pool: observability
            vmalert:
              spec:
                nodeSelector:
                  node_pool: observability
            vmagent:
              enabled: false
            grafana:
              enabled: true
              grafanaOperator:
                enabled: true
                spec:
                  instanceSelector:
                    matchLabels:
                      dashboards: grafana
              dashboards:
                victoriametrics-vmalert:
                  enabled: true
                victoriametrics-operator:
                  enabled: true
                node-exporter-full:
                  enabled: false
            prometheus-node-exporter:
              enabled: false
            kube-state-metrics:
              enabled: false
            kubelet:
              enabled: false
            kubeApiServer:
              enabled: false
            kubeControllerManager:
              enabled: false
            kubeDns:
              enabled: false
            coreDns:
              enabled: false
            kubeEtcd:
              enabled: false
            enabled:
              enabled: false
            kubeProxy:
              enabled: false
      destination:
        server: "{{.server}}"
        namespace: observability
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: victoria-metrics-k8s-stack-vm-validation
          namespace: observability
          jsonPointers:
            - /data
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: victoria-metrics-k8s-stack-vm-admission
          jqPathExpressions:
            - ".webhooks[]?.clientConfig.caBundle"
