apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-lua-scripts
  namespace: fluent-bit
data:
  victoria-logs-filter.lua: |
    # The Lua script remains unused, but is kept for reference as it was in the original configuration.
    function map_log_to_msg(tag, timestamp, record)
        if record["log"] then
            record["_msg"] = record["log"]
            record["log"] = nil
        end
        return 1, timestamp, record
    end
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    # INPUTS
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        Mem_Buf_Limit     5MB
        DB                /var/log/flb_kube.db
        Skip_Long_Lines   On
        Path_Key          log_file

    [INPUT]
        Name              tail
        Tag               node_syslog
        Path              /var/log/syslog
        Parser            syslog
        Mem_Buf_Limit     5MB
        DB                /var/log/flb_syslog.db
        Skip_Long_Lines   On

    # KUBERNETES Filter
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log
        Labels              On
        Annotations         On
        Buffer_Size         1MB

    # 1. REWRITE TAG (ERROR): Tag error logs but KEEP the original record.
    # The original record continues with the tag 'kube.*', and a copy proceeds with 'kube.error.*'
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        # Rule format: KEY REGEX NEW_TAG KEEP
        Rule          $log    (?i)error|fail|exception|denied|fatal|critical    kube.error.$TAG    true
        
    # 2. RECORD MODIFIER (ERROR): Set 'level=error' on the error copies
    # This filter only matches the *new* error tag.
    [FILTER]
        Name          record_modifier
        Match         kube.error.*
        Record        level error
        
    # 3. RECORD MODIFIER (INFO): Set 'level=info' on *all* records with the base tag
    # This runs for the original 'kube.*' record AND the error copy.
    # The important part is that the next filter (4) will *override* the 'level' field for errors.
    [FILTER]
        Name          record_modifier
        Match         kube.*
        Record        level info

    # 4. RECORD MODIFIER (OVERRIDE ERROR): Re-set 'level=error' on error copies to ensure it wins
    # This filter runs LAST for records that matched the error tag, guaranteeing 'error' is the final value.
    [FILTER]
        Name          record_modifier
        Match         kube.error.*
        Record        level error

    # 1. OUTPUT: Dedicated block for ERROR logs
    # This block routes the error copies. The base tag 'kube.*' is excluded to prevent duplication
    # if the output plugin supported Match_Exclude, but since it doesn't, we rely on the tag match here.
    [OUTPUT]
        Name          loki
        Match         kube.error.*
        Host          alloy.observability.svc.cluster.local
        Port          3100
        URI           /loki/api/v1/push
        Labels        namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],level=$level
        Retry_Limit   3

    # 2. OUTPUT: Dedicated block for INFO logs
    # This block routes the original records, excluding those that were *also* tagged as errors.
    # It must NOT include the error logs, but since we cannot use Match_Exclude, we rely on
    # the fact that the error logs are ONLY routed by the dedicated error output.
    [OUTPUT]
        Name          loki
        Match         kube.*
        # WARNING: Because your Loki output doesn't support Match_Exclude, this output will
        # unfortunately DUPLICATE the error logs, but it will deliver ALL logs.
        # The ultimate fix requires upgrading Fluent Bit/Loki plugin.
        # We will filter on the level field to separate info/error in the output.
        Host          alloy.observability.svc.cluster.local
        Port          3100
        URI           /loki/api/v1/push
        Labels        namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],level=$level
        Retry_Limit   3


    # 3. OUTPUT: Sends node system logs
    [OUTPUT]
        Name          loki
        Match         node_syslog
        Host          alloy.observability.svc.cluster.local
        Port          3100
        URI           /loki/api/v1/push
        Labels        job=node/syslog,node_name=${HOST_NAME},level=syslog
        Retry_Limit   3

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep    On

    [PARSER]
        Name         syslog
        Format       regex
        Regex        ^(?<time>[^ ]* +[^ ]* +[^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:<(?<priority>[0-9]+)>)?(?:\[[^\]]+\])?(?<message>.*)$
        Time_Key     time
        Time_Format  %b %d %H:%M:%S
        Time_Keep    On