apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-lua-scripts
  namespace: fluent-bit
data:
  victoria-logs-filter.lua: |
    # The Lua script remains unused, but is kept for reference as it was in the original configuration.
    function map_log_to_msg(tag, timestamp, record)
        if record["log"] then
            record["_msg"] = record["log"]
            record["log"] = nil
        end
        return 1, timestamp, record
    end
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    # INPUTS remain the same
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        Mem_Buf_Limit     5MB
        DB                /var/log/flb_kube.db
        Skip_Long_Lines   On
        Path_Key          log_file

    [INPUT]
        Name              tail
        Tag               node_syslog
        Path              /var/log/syslog
        Parser            syslog
        Mem_Buf_Limit     5MB
        DB                /var/log/flb_syslog.db
        Skip_Long_Lines   On

    # KUBERNETES filter remains the same
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log
        Labels              On
        Annotations         On
        Buffer_Size         1MB

    # 1. REWRITE TAG (ERROR): Detects error content and re-tags to kube.error.*
    # We use 'false' for KEEP to stop the original record from proceeding with the old tag.
    # The new error record proceeds down the pipeline.
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        # Rule format: KEY REGEX NEW_TAG KEEP
        Rule          $log    (?i)error|fail|exception|denied|fatal|critical    kube.error.$TAG    false
        
    # 2. REWRITE TAG (INFO): Re-tags all remaining kube.* logs to kube.info.*
    # This ensures that any log that made it past the error check gets an explicit info tag.
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        # Match any remaining kube.* log, give it the new explicit kube.info tag.
        Rule          $log    .* kube.info.$TAG     false
        
    # 3. RECORD MODIFIER: Add 'level=error' field to error records
    # This filter only matches the new error tag.
    [FILTER]
        Name          record_modifier
        Match         kube.error.*
        Record        level error
        
    # 4. RECORD MODIFIER: Add 'level=info' field to info records
    # This filter only matches the new info tag.
    [FILTER]
        Name          record_modifier
        Match         kube.info.*
        Record        level info

    # 1. OUTPUT: Dedicated block for ERROR logs
    # This block only routes the kube.error.* stream.
    [OUTPUT]
        Name          loki
        Match         kube.error.*
        Host          alloy.observability.svc.cluster.local
        Port          3100
        URI           /loki/api/v1/push
        Labels        namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],level=$level
        Retry_Limit   3

    # 2. OUTPUT: Dedicated block for INFO logs
    # This block only routes the kube.info.* stream.
    [OUTPUT]
        Name          loki
        Match         kube.info.*
        Host          alloy.observability.svc.cluster.local
        Port          3100
        URI           /loki/api/v1/push
        Labels        namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],level=$level
        Retry_Limit   3

    # 3. OUTPUT: Sends node system logs
    [OUTPUT]
        Name          loki
        Match         node_syslog
        Host          alloy.observability.svc.cluster.local
        Port          3100
        URI           /loki/api/v1/push
        Labels        job=node/syslog,node_name=${HOST_NAME},level=syslog
        Retry_Limit   3

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep    On

    [PARSER]
        Name         syslog
        Format       regex
        Regex        ^(?<time>[^ ]* +[^ ]* +[^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:<(?<priority>[0-9]+)>)?(?:\[[^\]]+\])?(?<message>.*)$
        Time_Key     time
        Time_Format  %b %d %H:%M:%S
        Time_Keep    On