# TODO: Seal these secrets before deployment.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: grype-infra
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-aws-credentials
  namespace: security
spec:
  encryptedData:
    role-arn: PLACEHOLDER_RUN_SEAL_ENV_SH
    region: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: grype-aws-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: grype-gcs-credentials
      namespace: security
