---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgARzb2AeqzuNk7MgbsrXcaJIgPAWtjRo923eiIo9PqXXqJswX/QfY8xWcfufPb5KVjLB81SvmDZ+bRmI51by5MqFzz6T9Z0c7BsxEo8qqvVeDshIBElBBzp6+Za6O0kyJc/D6y3tKpgOAFFD0ou5iztqaYMAt7d07ht7Uvl0GOr7uD+FRTM6Q9RCnDOL7xgKei/gdSrdww+yAhyR9cMN7rCgXjtNZ6APNADt82gjMhw5A+I+yi/WHiSyPbkQiBTdezLpRGEo9VDbyEvRa8NEZ8G6LInjF1ew72WK4Y0Ne76O13aEZJnyiJVkPpchaXJuoY4gBv5b4YhHvrGhpUJrGMtRKROty4xHkPyWvqv1qeZ7ysuaKM7PuSvCZcJ0ih4UP6WxF4KwyFcyZPd8ScUIeZm+0H0RT06VmodACT8l7fTPSz+PfR7nmDIPoPsmfFKRlirOSHo5a9F6zgL2sxQ4RiY8vKGjfUC0ilaoaeVLC67uTuzsYyao3cbZyqRaSM7heEKH/EvTC8Gt4scGKR4JKIyYuzRsBijDtkFiM/P00fsg24hwJob8ml2L2rf83t082qG2NH3dZp+x5rr3o8efs8p0YvHuguWnz5sGfFeDwlrxl4zzs5ZzwV1fXZpqk+9D/A7WbmDFD4p22b4+Q9d3IcQIrPbNeEjpDh1jpVwpouIpMjfmm0tJjSKluKvW7cG9fjt6222MT6wrokJ/O1ahHyGaUzLvqzjEWXLaWubIw==
  template:
    metadata:
      name: grype-infra
      namespace: security
