apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape
  namespace: security
  annotations:
    iam.gke.io/gcp-service-account: prowler-uploader@ctrl-plane-prod-b1b92df2.iam.gserviceaccount.com
