---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAj69N2YoXqzPSS3SGbG0D+sNro0NtYm3QoO+mqV0IN4rjWVZ19tVfsr7ACUIjc0skS8j5knbl10Kq//9e8L3Z32z4k3bF7IYfiTuS4k78trtsf1uYxCLr8BoAJ7VQP5wq9477VhLLY849IK6b67FVNfuvuuzi/DI0OwJ9MvNCvVf4AnvuMM1i8c/XqX31Hzp9Jzu3Qe1HdtB/YRkEwLEbqTx+Q/hsljZxiOB+b46v+GHBe3PswN0LJZchWdIkuxeHEV6IQZeEQ8isR9braf6+smS3qLZc9E029zYwJQWHFQ3C2mlSl1JCmSszwvaP7lYLhovuSOArdI2HXEth+0Gfgng1Qnu9lfhPX17KhNrlfVzMMg2gP+dAmsmUxnOcq3JYZkOhdj2tUpLH3EzTe0ELsz3Aj6Axc1cxHJvXR2irLNaooXcZE39D7vfE9sifl59ydJsZKXIpd5l51kjqpb8c6Ic2VAw+9vpPCGicLfWifB43HQtCWaofdpHYCeCIuMecultbH7QkjSlv99iP7xD/7cBASI1pGjexiB83pzJ/5NMvIkA/Rp52W/a01xD0X2L83+8yKAVjRwuvDfHTCcvfHGyEjmC+VM8cWne30Jd8cUwIOiqLvmnyfNJ4u7lI6QTmrfabkkpKomJqTLbznwHQUh5AhwAmxipeDsm+wHpGvciQZSrEG8REaYNmz7RyKVuZfo9hARFh7BAWm
  template:
    metadata:
      name: prowler-infra
      namespace: security
