apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

resources:
  - ../../base
  - db-importer-env-secret.yaml

images:
  - name: us-central1-docker.pkg.dev/PROJECT/backend/db-importer
    newName: us-central1-docker.pkg.dev/ctrl-plane-prod-b1b92df2/backend/db-importer
