steps:
  - id: Deploy to Cloud Run
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'europe-west1-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--service-account'
      - 'db-exporter-sa@${_PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=${_NODE_ENV},SERVICE_NAME=${_SERVICE_NAME},EXPORT_BUCKET_NAME=${_EXPORT_BUCKET_NAME},OMNISTRATE_SERVICE_ID=${_OMNISTRATE_SERVICE_ID},OMNISTRATE_ENVIRONMENT_ID=${_OMNISTRATE_ENVIRONMENT_ID},TASKS_REPOSITORY_MONGODB_DB=${_TASKS_REPOSITORY_MONGODB_DB},TASKS_REPOSITORY_MONGODB_COLLECTION=${_TASKS_REPOSITORY_MONGODB_COLLECTION},CTRL_PLANE_PROJECT_ID=${_CTRL_PLANE_PROJECT_ID},CTRL_PLANE_CLUSTER_ID=${_CTRL_PLANE_CLUSTER_ID},CTRL_PLANE_REGION=${_CTRL_PLANE_REGION},NAMESPACE=${_NAMESPACE},APPLICATION_PLANE_PROJECT_ID=${_APPLICATION_PLANE_PROJECT_ID}'
      - '--set-secrets'
      - 'MONGODB_URI=projects/${_PROJECT_ID}/secrets/MONGODB_URI/versions/latest,GOOGLE_RECAPTCHA_SECRET_KEY=projects/${_PROJECT_ID}/secrets/RECAPTCHA_SECRET_KEY/versions/latest,OMNISTRATE_EMAIL=projects/${_PROJECT_ID}/secrets/OMNISTRATE_EMAIL/versions/latest,OMNISTRATE_PASSWORD=projects/${_PROJECT_ID}/secrets/OMNISTRATE_PASSWORD/versions/latest,REDIS_URL=projects/${_PROJECT_ID}/secrets/REDIS_QUEUE_URL/versions/latest'

tags:
  - backend
  - service-db-importer
  - env-${_NODE_ENV}

substitutions:
  _PROJECT_ID: 'ctrl-plane-dev-f7a2434f'
  _PROJECT_NUMBER: '425012726186'
  _REPOSITORY: 'backend'
  _IMAGE_NAME: 'db-importer'
  _SERVICE_NAME: 'db-importer'
  _NODE_ENV: 'development'
  _APPLICATION_PLANE_PROJECT_ID: 'app-plane-dev-f7a2434f'
  _EXPORT_BUCKET_NAME: 'falkordb-dev-rdb-exports-f7a2434f'
  _OMNISTRATE_SERVICE_ID: 's-KgFDwg5vBS'
  _OMNISTRATE_ENVIRONMENT_ID: 'se-DC0AzhMHOD'
  _TASKS_REPOSITORY_MONGODB_DB: 'db-exporter'
  _TASKS_REPOSITORY_MONGODB_COLLECTION: 'tasks'
  _CTRL_PLANE_PROJECT_ID: 'ctrl-plane-dev-f7a2434f'
  _CTRL_PLANE_CLUSTER_ID: 'observability-stack-a89z'
  _CTRL_PLANE_REGION: 'us-central1'
  _NAMESPACE: 'db-import-export'

