---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-git-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgABffuYoZrBlmNq4VzI8kvO3YEGjHKG+l94r6nKUjKLMY/hooy3GomaR2ujXsnSgxFsnZyqsgN2JPhr1FcCpw9oWdS7muf7LSJh6g3M0SR/ibQ30psn0LM4T1Z5qgcGcKpXH7nQkT0L8GraHYxZg9lzov76apoZIMj3Tqksg2IO1LG7V6yvehxo180l13VpWVhW97aAID8PSvw7xStaNxxRRnYMK24GlXFQ62YI5otjMBC7HxbZ66aUfKzpUSIevGIxFS4v7sOkdnWxGuxPKovv9dv0d251lvQfw0GW8zyxvMKO4j9cphHODyLPU2GOkk4FiqveldwJcCUm4qcH2ulIdi62t/izna/IEqqC0Ia31dBP7nXy8uUj+sqTOS17qIt6ZzvMYagIVf1xqVXFvtqCww9BiuibGlWzASPy797afAwW8cAdtNdJ0dC+3BPNa2IPpX0okeU4rPZTj558spn7f7x2lQrdayRtRU1Pk+ocKXn1kdARqK0SC4Yqzz5PkFG2mAz67b7IrW6bQvTeSamuLHWWn9Wi+DxnXxTtJUseOTxPNnePsv0Olg7X3gnGRYNfMtgoE9g9E1sr6RdzxRbdZABLQClMotK99iVdDgw0Z21pZvwZHv4WbbtPtUp2Q+KkmcCAV6t9C3GVk1N8+aoCPDeJQR8rQdPxGdFEWhLq/JXVLVWCgrKRMlE/qZ6WOFH5qn7BG+no3qCBlCeRpWw3rxndZG2k7L3N7RELnAacGpjrwh6rzEKZSG1Bxf8AfBxPA33jmNxot6dox4C/zc7RJ8KQVetY4kM3S1LFO55Fj9r1L+tugJnl2CuuzR0=
    username: AgB0IRmZGlafjSJjl9SxqSf7ZguzZDpJejsUuqsDM4M4JwKxIOrDJ6jqRsXWWoEEtDpac9qyJkz0f/TbMt7KSH2hkejbMiP4r53lJq/IfqP6PfJmd6l463xMywsRdY6CM1VGprgjUj7UhbYk/fLtJVwTrHd+OiajVFHdulVXpDNf15tPBW3cHte85hDPKWk/4xre8F2BbEKb+Uhbu4So9cl+B+UdXDE9XaJV5c/Csx9LsvsaOvU8QRVC8loBbc6O14rWgUn5l9X5OkcYXhnfncdFhjxV0mNvo5m2SSWQjGyRyaJ9wJW0APGVHZzt44YIt858oVPo/pUWumdWGtwIyeSwxazzFW8ndRNDCF9cWw1X4cCbwo4OjSfu4nKxEzNXbC1Ta4qFNBE/wEaZh/X5fCH0aA7+JRznu+tIZzhdtDsnbL/xdFkSdDY6mDe4sl1zGNnziLFpKQS2x4ckIIkSkC/IejvLaGRGM8PHUvGJ4Fj3OG7+Yd1NH3xwMmNkph38qSs0K32QqQkHMU3ANU94KSlWTFLXVuIDFlY+sRc/Hd0V77xDlnCc7kS7opO/Q11pGFBE1IBQ/1VwBEjSjgSf7e8dsi414VtTqKW6JsPwYbY2kAx+zttT6WKHwXn/jZJotEU3Wjhr5A3qCe/9rfIt0eKgfZ0/IACUN5jQd2Ods6oR7FDOF6YGGDst7Og1ygkSFq9uaZsm5CGfV8vpzF4=
  template:
    metadata:
      name: argocd-image-updater-git-secret
      namespace: argocd

