apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - n8n-secrets-env-secret.yaml

patches:
  - target:
      kind: Ingress
      name: n8n-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "n8n.falkordb.cloud"
      - op: replace
        path: /spec/rules/0/host
        value: "n8n.falkordb.cloud"
