# TODO: Seal this secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: kube-bench-infra
      namespace: security
