apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
  - wazuh-manager-ca.yaml
configMapGenerator:
  - name: wazuh-agent-config
    behavior: create
    literals:
      - agent-group=app-plane-prod
generatorOptions:
  disableNameSuffixHash: true
