---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    registration-password: AgAUbcWoBklFBD2OG6AaVFaXU3Vd4ggV7jGYkOWzr+bhiH1cvmbgl5c2Gf/H1GxbquEI+8W2mbnnPGpeLDou/FT50uFH5bd87gMlIvC/BHcdClTL6mQiTe8OCmC92klHwsHrEqBAV8DvqTRDA7uA/aswxtFpyJys6zZd3kRpZVh9d87v4H1GU3U4u9kEdkP+a74ET9RrTXVNWh22+StmkiFAAzj/51zC1ie9wrnSiCXXlj2JQAODyOWrbn4Ofx/IK12asicuvDtrmdb0/v3keeEajStCMCvQqruoBkix20zDKhlsOvRL47hGv3RpOXajMhn6vBMaITsPONeYaHcPumCEE9+xtSWmLfPz04cG6q14VK5Z3AA8Gcc8nvjHDnQBafylRglt+y7nEcYnWx79v6UgvnO5LmtYxL3Xg8+yx4XZxhsSOnp9BkWY9J91Gv01gxhZM1RjSo2WOuP1QiP0WEaL4+04f87n35FZN436FzCogeHAKYRWcodUvLafZvaZ8Cfy9EBVFTYUCHZNKN5UrduN33MJNwkIuh3iwutBLqpy/ipWvq8CusjJjSy81AZzg1tGpVJJJ7gboWpH+Fg8XaQrx652GTRVnjsnGueK6oYhdjHQAM845dVu8k9F45TQjwW25ZOJP0A6eLEr7z7/RkybCPwux6tGqqFFziFDIfB+Ux6h908E8j3/mPUqN7LkPhoCLQyuv0pg3meXGZiA/yMsRqaU1WNFpQvBqE7q+OIU1x82v4ZuJaMgVwzE0Jl/YfGHTHoImxsfV+Fm3gOwZnTW
    wazuh-manager: AgCE5WGMKB81bf9ZvLbQlBupFyQ60F/zKkaxvcOSe36WQg+Qy7QnVAIACMca0P08R5kRH4SAlNjAbl+0WO62FNh85TODdzUISxfnnxdUTawHxIeDVJm3FmQTNJ7KiL5dFAssTpnh2oIPbOM0B3XE61Zu4ytDKcqVab+tJ7irL9LsjL9yaesGQIoMXuJ3WFuAizNwkk3GeyHQ83kdWTqug0tQa00HoL6FvXZh8FZZLiJNQxVdv0y84fCRmfNRQ1NE6QTOK0U311vJdmDYwhPZlUG4gnQothbBA1JSGz+TZE/5QkozbweB9asYN7GF7gNzOz+opMlv49q8Ek1gPkG70TFUzxLJkrjngZ0pc/qMyoIElDnSEkVpb38zpQdfYc/3qzwwukysewhD2b4luAG7xeVj4C0//Vp+nLCWnrU9FvvU/ftqglyk5AzZMjaH30n0rSWu2WgKvE7WrwAdMuj8U3xLWyOLlHcLsD9GwILUH5c0aWeGdjXv3re0sTMewJ07Jc7rMmafU0vg9QamjXho8f2RQ83ZZ6yssI6RjSLLCfqngfp5xP/5P4IgbkK0VMwur35nJCyzSXxDeU0+8cxWh0gvb7EpXnf7N4OH9uGxRn1zr2+mby5uIPh3OUJ8p/5NVoKXs25SA2dHIBE3amhToGOlYTt0jiQf0Aq2KvotO+leHZIB1UQ6FFj3EbB0enBhk3n1CmAs5rbJ7VKvMscxesWcpbHm4UTsWkbmrw==
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security
