---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    enrollment-key: AgBw36La/WEN3PpxukNM2YUjFzDHd9LaaoK3ZixNAfR1KO42fKEJTEgjiXRKPTNroOHJmnJ5+Og+pXpTQLM/4aobMXipB85swbVN4IT3jXQUgBlGbJrXWqttF71U8vUEHlhkoKCnoRiZrxD9V8SQVndsEBBl9q2I5yO8RlhOv0aoYwIII52igcuwB+L5hg4FKfkwedsy5kohcs6r6+8o6COqEx/uvCy/Abp+9ePNMQ+57wq2Rylq1nnelA5NOkwJ799arQ5Zh9bjtovbtYNj7xQMum1+AyhW6zWh3yqFDcBeIUb6XxWcvR6Xw/WxHUJrU1lXBmrxaAmBT4HEti+ogWC4HwuTyG5xyzALCKNIxHre0L/pouYKzikBqubyJf4u+EqjmEiF3zZR35dySu+vUjgN5MUWVbxNYpHPRtfD5RUul4yqtpVpBHMq0SsZriuahi02wYMeVhj7Xdy3hM3Uzmlbetu2spsBU5LnPAVRfMGaienxFg93eE9143DOeCmj2I2CCByWcqKYAF8q8YbZc+uRlGx1RWCpH7sney3spu0uZTCW/m4okyZ5nBgUN8vVpCEXF0KiljkQmcn9PkttsX93FWnjr2Yx0HfC3Op/T7xATEjdqGHzA2aqGVJvw0gt/fXy1FIRZ0Nq+1EVNu1vdWOJ5B/aUIotHYtCRxFex9fjP8xeezk5j75OkTeE+Th11hD0aZ9AKFxcErPk
    manager-ip: AgADj0sT6xsLul6DlBsZzRSo67hFmzZGvDr8c/69CZpMXlcUoLo6njXJbeiANFDqKIdrP1dw3QNfgjf6iZNJB+fGlg7YYyiJEmtfoHF7gWIVCEZyvmyVR5Qrh2I3Y5NB9P41RC6W9tZWxp89DDixC7493LRFio1kgk/8Oh+o3vJGyD3i/wtaVpWMO72UlmL1M6OawZwIKfhJcCv13ekVyR8Dd70OqhGPCCmUJO73WQCPHFaFGzVetoyOziVBxyxMsGXM54gfVpjzqIqQUl68CZg1deAIdwbbJKd2MQLGb+M1PKOvH8iNZ5afaCXtPdHV48JiuP2zDkwD8ICX17nRUWMo2XJdyG1uinqyPN3yvH5Re7gxW8uMDRTWRJO/l5wEQa21S1VuSaeLDgdvv3OoaDgxCoxCVUs2mKdAsQSoIkRnipeFGv+0xl7yyvOforusY6pUVR5XYu4lw+NMcYajrYAzAVtpW+JPyL+XlvZ6cEMe6VJOVsZ9elTzTAvO7uGVdl6+33oINOxFsBDAiClVs+y6xmNbFpdc1Hn8DUpj9sddqG14v0rUNNbyqhP79bQl0gnJ+3u2/l3xdhw5B6n4Kup8Jfe3GTfPyvkGoEL7vaNLzyN+yl7/soZvaWYCAWUgSSKJhvBhBohx58bXXyVb9YKb4oHyALAsEJCkgI/90+xoxsZNI4cq2C7agiQFob20rWfACXbr+lii69jM
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security

