---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgCyLqHSWg7QIkEPADbMk9sjGxHYs21/pbvQV2KT6q69NE2FrOhVPISJIGo2m65P/GY65RUVaFqxDMmw6xqwv/O6YZ1lXs5FBLjsko2PloyUE27qPyiLNXcVGte01rflpkOfu3HCv4q4aOnpyAcughSaVEVAxyPlH0OR3BJ7VLvxajCUpdQYvpomkwfgA9k+eDwzp8Y7mEJ5QF9SJsg5ODER28av/5fJdRufUDxWYoJjDaTu9j26TDQ0AzoUt/b95m+Fjr/thXQSGo3fW7AucZSO/yULYOxScmElT9aSYc9IGO6hIIBZ2Fwo/0Z7u87nYE1McREZuuQWBZTS6ad6RWxUjjse74EOENj8A3IXfwut7VY+/wJwkUfv4oiQ7Az0yuS/U+0DSPRDnLsolEI39gqJWVMICCrNM8NlFITpYDg1/EyQC67CfWE65McC1tMSUNdq8eVYTxhKtum2C6mhqMvA7foyyxCun4r5JtY5Gs7z0N2BxKeN4Otr889dFpqSJmsiVCOOBEdnAOXQi88bH0NYKyJGg3sx6t3ljRT/7bwpsmJO37aLwzn07nPz8M5T6kvp5Yrx/wFp5XNr8l+Vnudqfgjr4uUSSTeOQoc60JpiJr+FY/B6Xf6GWeJTK6KYmUrsj6amWX7C2pA+XvUU+bXtBYmjJ4AOt0NG1Fe5ipbndMFHPrzdPK8pCjZmQ6eXObKLtOzrAP9isk6QdlU21tHBHYD8kle4yBM5aLk9pQ==
  template:
    metadata:
      name: trufflehog-infra
      namespace: security
