apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: falco
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
        values:
          cloud: '{{ index .metadata.labels "cloud_provider" }}'
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-falco'
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: 'argocd/kustomize/falco/overlays/app-plane-dev'
      destination:
        server: "{{.server}}"
        namespace: security
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
