# TODO: Seal these secrets before deployment.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: trufflehog-infra
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-azure-credentials
  namespace: security
spec:
  encryptedData:
    client-id: PLACEHOLDER_RUN_SEAL_ENV_SH
    client-secret: PLACEHOLDER_RUN_SEAL_ENV_SH
    tenant-id: PLACEHOLDER_RUN_SEAL_ENV_SH
    subscription-id: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: trufflehog-azure-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: trufflehog-gcs-credentials
      namespace: security
