---
apiVersion: alertreaction.io/v1alpha1
kind: AlertReaction
metadata:
  name: falkordb-low-disk-space-warning
  namespace: observability
spec:
  alertName: FalkorDBLowDiskSpaceWarning
  actions:
  - name: execute-disk-threshold-email-workflow
    image: dudizimber/alert-reactions-gcp-workflows:v0.1.1
    command: ["./gcp-workflows"]
    serviceAccount: alert-reaction-actions-sa
    env:
    - name: GCP_PROJECT_ID
      value: "ctrl-plane-prod-b1b92df2"
    - name: GCP_LOCATION
      value: "us-central1"
    - name: WORKFLOW_NAME
      value: "falkordb-instance-disk-threshold-exceeded"
    - name: TIMEOUT_SECONDS
      value: "600"
    - name: WAIT_FOR_COMPLETION
      value: "true"
    # Alert data passed to workflow
    - name: ALERT_JSON
      valueFrom:
        alertRef:
          fieldPath: "."
---
apiVersion: alertreaction.io/v1alpha1
kind: AlertReaction
metadata:
  name: falkordb-low-disk-space-critical
  namespace: observability
spec:
  alertName: FalkorDBLowDiskSpaceCritical
  actions:
  - name: execute-disk-threshold-email-workflow
    image: dudizimber/alert-reactions-gcp-workflows:v0.1.1
    command: ["./gcp-workflows"]
    serviceAccount: alert-reaction-actions-sa
    env:
    - name: GCP_PROJECT_ID
      value: "ctrl-plane-prod-b1b92df2"
    - name: GCP_LOCATION
      value: "us-central1"
    - name: WORKFLOW_NAME
      value: "falkordb-instance-disk-threshold-exceeded"
    - name: TIMEOUT_SECONDS
      value: "600"
    - name: WAIT_FOR_COMPLETION
      value: "true"
    # Alert data passed to workflow
    - name: ALERT_JSON
      valueFrom:
        alertRef:
          fieldPath: "."
---
