apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: prowler-config
    behavior: create
    literals:
      - cloud-provider=azure
      - cluster-name=app-plane-azure-prod
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - azure-credentials-patch.yaml
