---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-azure-credentials
  namespace: security
spec:
  encryptedData:
    client-id: AgAFwHQ+0BXmY/uB9K897pqzvHrX5F5I0vZHeUqvbbzS6zRfKOZ2tWim6QUlw9dSn2PjH4tNzlYL1TR4UBZVNtXSaMXjgsSaiySwJg7VWYNhsiZrNugmolqflFmUWYzfiyOziD5LLv9oX8g+AXwFAcuhCoqo9tyis0IfmiMqhNZOecRtk1AocSFk1EIdqareah2TvB7+A534WOdc9h6K5NvUc78hF0efhOIwiAXickvd0lVfp3VhpGdgwWrWusu2q8H0RGfQTDFquKozL1e42elkQsUu9PsWG+TAw15Z8Yf0cVagaXMr1N/fiJ9NH+OHROErq6GemcrmU2Qobt2DK0Dj32sPUkYbUwSEgskRDb0qzUIOW0GyOUbrM0haeTKfHHdX+MVa3ZlaNzbvnzLoire8+Kmp/SSqWLHh4chmhOeskdXAiEojzHTGuJIAOkzQt3zUx6Ck1ipLJp+czZ0VA5drNpU2RycW96YITtvzAv8jdblYeNXROfWgxWqC2DQtVFgZ/XJ1BZIUrOvyfZWJN+TAn5osL008njNTIYZB3nsbnN36JXb/ymDuJJpQyUGcE3yvv0Q8zTvAAz4xADjJPT/M6keXPg0IuGamOuVVGkf8ptklY7JtS4u+8UytArcu3AKAJzwmTOeRKmkGX5WJVpwABTY7OIAjgzZkB3toVeAIvIanqJUhE1D9BemOuR54z2x4EJ4Unzty9vmp
    client-secret: AgCBhGGYJvm+Ftl9jw9TkUIxZ5ilcolWAl4itsb5n1PHMK4zAJL4UZzQWSXLD/7C/nvdsFtFHusU1fq9VnLJJTGGGewigvlfCjRXXDil1Ai0evbuIy0FMHukClaQ8X1mJo14wtFYL2jU+nx3AEJjbMQX/LSjhENMWqAGt/e8cJ05WDYYWBrHLkaaam1k51QexQqZz6w4Nmqbk3eY+o5tz3lXohagu5vISV2BGemqBomu7l25OSe0RIhj8Ska5WISI/Cm6FFiTe04ClSYWEiDLy3xnAOF6Afsi9urzOOn1M1S6GZfHvwvYoDmAK40G6LAk+8t3JxInkWYihu5AeBTJ/U82YZYVJQ5vnGwosmoflbHWy0OqiP87QUhj6ISbhVNfmMzBQXou5wwVCW1qt14J89T3ZbOpB8MfoUQXdKvO1/gFRvsy/+gIcTahiGBSAS9OQWtll2GeJvXOLzq05RsDpWuRYuHZxkyhIeY3J4JwuqYEvN5OGgBIdh6OVZmrN1KF0isMPuUldpCvhU8A/yR+AsTk5g/Ow8vem3zlYgbFbWk7Oi7db85VKNj1rzAGpsUNvlEO6qeOlJPrrDcxzq6qE6xq7+0C0i1LfZ+ehlqUDfgF0+gAJ/8IUwiMCHUU/VBHLyWgw3aUE6cEXeo7LBMYsazYuw826JB5RTK9kBPb8Xce1148z/GhrfI+gyQHmR0l+QLkE0xGsRzc011
    subscription-id: AgB0Uk1uGFQT+Clgbimla4H9bg/gSBPGl6rZscvh2G2urZkyaW0aQE4cafua3QlKttfS3jEZn/Xq1+2281K95XiivldYRoo9CNSzQy03caYmk5L7IEEEUXXUiuLJFb/QZWt0DLga/Pw1Q10wkFxKNebFe1JXAmULllAfNm7YSCJ5l25LeHZB9q2p14/mSxohdqim5VNn/w51Pi1Yz+JO920rgUgfu+/qkMWYM+Bqaq1rw7jojjHY/GPqOmjPQDdjaW43qJZh4CYeDy3UJ5vTvih+fYV05lsbTPZwWsFbWvonFgLamORInMkoN6eFHOImudImrWv+aO7iZIrK00nkGnW6e+1D5q3KpyztvjYCUJVeBroiXKNx17fzxnkDFgaN00l+AtOin9R2D89GlUjVBUueVwZA1sVfJEHKwhdqLTvCSIq3F7BNr9MSwge27jI6QhNEuS8U7ELWZQd9OSNKYvVHf4Vica3ju5l7aU0IP2JEf9MEZ0iY7Xxohs/Dp+ZCywYYKHe5ezxwOvmID8dezHTHcByKLPgw6xqO602mPb8AU2QxMCsSzXw9/EpnCCxEVNDeb29VYyRC8aS9lStP+LNFzMYMa0iCDI9lH5QFyipFrzZcYHWhjAFfzBh3pSFLrN4wXQPJ+N6GiAa70rjxFXrPNvnmy/dZaiiHIU+zt3nBx1E9Q2gAcaYQTudpLKDAmWZGIwkjCS9xFDrR
    tenant-id: AgAT/81WIMzaUKeim2gUVnoZoAKKWkV/kmoLdPRQrjzbabQ1nL2B9GEDKtiH+OxeZx9y0tXIefELKt9w1qD5M7IajDgmHuZPoz2VMkdA5jEwtLHDnrhd9wZe4YELMjlg882nSjq+nbcG/nxZ0SvFdEfaMOzzSgSTcKL0saohLyHxCblUVoabjxAEsrYkCFa6Nj9yUtyggIYhwk9A2z3UX1x3NbIT7DDUmxy3bDCYM5Rp1ypXXYP8Q5Z5e/rQo8n9U4bgwz8mu/SabxLa9t8GilpuTUmZ3E4U7hq7sd2cA8XacmqMkNHUWeNGVsqMzLEt3hPKrRbfZeyb84Bs0yn4sgWi4CgDtvfjTlRqGWZrw1jLJze8PhJTFtN6LDMw/6eXgKXYOJguwuSONIVgkukhcsce1Lc8+DrgF0NdXlcgnaTL5zua3mgFDwSJMolOAI9WeB+R1P55jpdQhWk7pfTvctNZupW/9jbki2RLSE0sYx31r7N0zXYBDn8pdxdTV2sLFhNW7nzf/yTIwlnMpRrC5wiP8Ul7lPCkg6DBqbegZ4qtdakBAhvA+N9rPvP5s/Q3HKSO3NsPpc5h8VQdjriFz8IOlO0ovVgCX9rS2UwQaRm3+d1gSfDnwEV+3Fc11QHvvHFDPVjFFpn+AH01SZ/OHKcU2H4K1fCzdWOBK1MW8ihcckRalfjmZrxW6MrgpfUaVy5Ol7jydY6o8ouF
  template:
    metadata:
      name: prowler-azure-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: AgB2qZ15s5kG+jDIjxCmAZnzw512SATWb7iZDT/5R4iWluVsZswHt0aOEdOwdHcW4aIn76m2DcwkjALHSZLxiOgWAOm6Hp7jYekO4X9AJd+dMQvLXhPDCs1FHCPGHZ3vSwFN8jchb+tWTE/LHmuh42m4BE3RiJmYjMpm2TIHiUKCqPXMQdoIHsGyXAut+12RYyf8Kxbh4Mp7SJRfreHIZDDLYoDkF5H6IHWTO4cV42wdv2vbsJYpBFJgnkUGHP8RIhBRfzVRIPk6kYNpbU7vD/5EMOjDZQN+WlVyqgO/aWXvoJW9GGYC6GTFd4e6zgzbTxXu2m3tX8U0qPBObu2wpIk0cimRkLgeP4sMVZzBPHsH9sxMIPsHHM9kXoZe6QTslHkLvM/ITHV4IRloP42vuw66M5IRpSdekQgoH4hjNn4k2tRsoq0NArdbkKwAfz5MX7ML3/jHsuwGTYubyDpaFT4a7CuvfFcqxPrOwIEKIYYSBq7n70M0CCRX5zQQu0QEF4hWu+oWFuMkLjdRQlHcA2O4qFZSStBoDxC5St72acCtaasxhz0ZNWNoAHdpAV6gqDnGNLDozlUAF2lgZqcdbQr/Bt5QuGac1IBxQ3BZTM2wBAw5mGiGZ4HiLFHCzAI9t/ZrPjRVwFjlWiJO+teGTRiOQbEWRNljKHOCPENSiWEfMWOyXjLOfGiRzT34DWJEZaZ6TUVkTGNMlpzd
  template:
    metadata:
      name: prowler-gcs-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgC9KXLWHSlNz81WP12BV2WcgkOcritMqCPWtcroOtgpnhUIL9OGK01v7zqLlIgE8VgA5ZXNb8JeX4CMymubHw0quBVv7rdxcSfvNd8NZbbQ33aj5vjv8f2YouUEMI/UnUeiteA5y8R2wfSKeMtHIGcxGganvHJuQ9QCj0ER74ugxpWu2VrqwidwrFSatdvSIW9FdPyzLWEAAvdBAfOw0okhV0c4H3J/WJ97SqC6bvqcXCy9fJK/8cV7ooHLZO9rFyicDrkHneSeTaq8MJbKYqJTFVaU8zAnHMbuwxJ9j5ZeePAZqdVp6tgNRCDjhomWtMUbXVyM0lGxVZAAL/LN8dE35/jUE2Yr2hZCXX2YJ8PucAV+h9fxXZFPYEjFtpIU0/mqQ0SIDKkCG/JsT7IT4hnD7iGpx/YYtNPe2jaw0EOr7Mqn+FB3EFfzdM5vQKWUZsV3Q50ooY69M0xDvv83sPICXaeTfeZqBQzxYaEXI/JzOfdpl0XXr6t5PUi1NIMfNSDI2BZtJbDpuj0/iaBtMABBtEBiNXSpzsWJrLgGqX27UCoYbWEX0lCJyo/bi4pcbfzGV+ndaHxHwtiVjkkPjsSdrVUvmaSva69sDnl8dTTm5CzKK1hXcP4Ipuhed76FtWsHbDiak5gdyCv2Sd1cilOoki/+L56fLtxSkYH/qRuk7gh9siEyzAPSFZBur2p8eijLqODdbDdnaDYM
  template:
    metadata:
      name: prowler-infra
      namespace: security
