apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: k8s.rules.containeroom
spec:
  groups:
    - name: k8s.rules.container_oom
      rules:
        - alert: ContainerOOMKilled
          expr: |
            group by (pod, cluster, namespace) (changes(kube_pod_container_status_restarts_total[5m]) > 0)
            and
            group by (pod, cluster, namespace) (kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1)
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "Container OOMKilled"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was terminated due to OOMKilled.\nRunbook link: https://github.com/FalkorDB/runbooks/blob/main/alerts/ContainerOOMKilledRunbook.md"
