apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: falkordb.rules
  labels:
    is_logs: "false"
spec:
  groups:
    - name: falkordb.rules.general
      rules:
        - alert: FalkorDBDown
          expr: redis_up{container="service"} == 0
          for: 15s
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB down (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            view_logs_prod: https://grafana.observability.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}
            view_logs_dev: https://grafana.observability.dev.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}
        
        - alert: FalkorDBSentinelMasterDisagreement
          expr: count(count_values("master_address", redis_sentinel_master_status[1m]) by (namespace)) by (namespace) > 1
          for: 5m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "Sentinel master disagreement in {{ $labels.namespace }}"
            description: "[cluster={{ $labels.cluster }}] Sentinels in '{{ $labels.namespace }}' report multiple master_address values — they do not agree on the master.\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
            runbook_url: "https://FalkorDB.github.io/runbooks/alerts/sentinelsplitbrainalertsrunbook"

        - alert: FalkorDBInsufficientSentinels
          expr: redis_sentinel_master_sentinels < 3
          for: 5m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "Insufficient sentinels in {{ $labels.namespace }}"
            description: "[cluster={{ $labels.cluster }}] FalkorDB deployment in '{{ $labels.namespace }}' has less than 3 sentinels (current: {{ $value }}). A minimum of 3 sentinels is required for proper high availability.\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"

        - alert: FalkorDBEvenNumberOfSentinels
          expr: redis_sentinel_master_sentinels % 2 == 0 and redis_sentinel_master_sentinels > 0
          for: 5m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "Even number of sentinels in {{ $labels.namespace }}"
            description: "[cluster={{ $labels.cluster }}] FalkorDB deployment in '{{ $labels.namespace }}' has an even number of sentinels ({{ $value }}). This can lead to split-brain scenarios. Use an odd number of sentinels.\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
            
        - alert: FalkorDBMissingMaster
          expr: absent(redis_instance_info) == 0 and count(redis_instance_info{role="master"}) by (namespace) < 1
          for: 5m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB missing master (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB has no node marked as master.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

        - alert: FalkorDBTooManyMasters
          expr: (count(redis_instance_info{role="master", redis_mode!="cluster"}) by (namespace)) > 1
          for: 2m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB too many masters (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB has too many nodes marked as master.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

        - alert: FalkorDBMissingBackup
          expr: time() - redis_rdb_last_save_timestamp_seconds > 60 * 60 * 24 and rate(redis_commands_processed_total[5m]) < (rate(redis_commands_processed_total[15m]) * 0.2)
          for: 1h
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB missing backup (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB has not been backuped for 24 hours\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

        - alert: FalkorDBOutOfSystemMemory
          expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
          for: 2m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB out of system memory (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB is running out of system memory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

        - alert: FalkorDBOutOfConfiguredMaxmemory
          expr: ceil(redis_memory_used_bytes / redis_memory_max_bytes * 100) >= 90 and ceil(redis_memory_used_bytes / redis_memory_max_bytes * 100) < 100 and on(instance) redis_memory_max_bytes > 0
          for: 2m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB out of configured maxmemory (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB is running out of configured maxmemory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            runbook_url: "https://github.com/FalkorDB/runbooks/blob/main/alerts/FalkorDBOutOfConfiguredMaxmemoryRunbook.md"
            threshold: "{{ $value }}"

        - alert: FalkorDBOutOfConfiguredMaxmemoryCritical
          expr: ceil(redis_memory_used_bytes / redis_memory_max_bytes * 100) >= 100 and on(instance) redis_memory_max_bytes > 0
          for: 2m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB out of configured maxmemory (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB is running out of configured maxmemory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            runbook_url: "https://github.com/FalkorDB/runbooks/blob/main/alerts/FalkorDBOutOfConfiguredMaxmemoryRunbook.md"
            threshold: "{{ $value }}"

        - alert: FalkorDBTooManyConnections
          expr: redis_connected_clients / redis_config_maxclients * 100 > 90
          for: 2m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB too many connections (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB is running out of connections (> 90% used)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

        - alert: FalkorDBRejectedConnections
          expr: increase(redis_rejected_connections_total[1m]) > 0
          for: 0m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB rejected connections (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] Some connections to FalkorDB has been rejected\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

        - alert: FalkorDBAOFFileSizeExceededWarning
          expr: redis_aof_file_size_bytes > 64 * 1024 * 1024
          for: 15m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "FalkorDB AOF file size exceeded threshold in namespace {{ $labels.namespace }}"
            description: "[cluster={{ $labels.cluster }}] The AOF file size for FalkorDB in namespace {{ $labels.namespace }} has exceeded 64MB. Current size: {{ $value | humanize1024 }}."

        - alert: FalkorDBAOFFileSizeExceededCritical
          expr: redis_aof_file_size_bytes >= 512 * 1024 * 1024
          for: 15m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "FalkorDB AOF file size exceeded the 512MB threshold in namespace {{ $labels.namespace }}"
            description: "[cluster={{ $labels.cluster }}] The AOF file size for FalkorDB in namespace {{ $labels.namespace }} has exceeded 512MB. Current size: {{ $value | humanize1024 }}"
            runbook_url: "https://FalkorDB.github.io/runbooks/alerts/falkordbaoffilesizeexceededcriticalrunbook"
            view_logs_prod: https://grafana.observability.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%20AND%20container:%5C%22service%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}
            view_logs_dev: https://grafana.observability.dev.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%20AND%20container:%5C%22service%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}

        - alert: FalkorDBAOFPendingRewriteWarning
          expr: |
            avg_over_time(redis_aof_pending_rewrite[10m]) == 1
            unless
            avg_over_time(redis_aof_pending_rewrite[20m]) == 1
          for: 0m
          labels:
            severity: warning
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "AOF pending rewrite is taking too long (namespace {{ $labels.namespace }})"
            description: "[cluster={{ $labels.cluster }}] AOF pending rewrite has been pending for more than 10 minutes on namespace {{ $labels.namespace }}. This might indicate an issue with AOF persistence."

        - alert: FalkorDBAOFPendingRewriteCritical
          expr: avg_over_time(redis_aof_pending_rewrite[20m]) == 1
          for: 0m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: "AOF pending rewrite is critically delayed (namespace {{ $labels.namespace }})"
            description: "[cluster={{ $labels.cluster }}] AOF pending rewrite has been pending for more than 20 minutes on namespace {{ $labels.namespace }}. This is a critical issue that could impact data durability."
            runbook_url: "https://FalkorDB.github.io/runbooks/alerts/falkordbaofpendingrewritecriticalrunbook"
            view_logs_prod: https://grafana.observability.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}
            view_logs_dev: https://grafana.observability.dev.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}
    - name: falkordb.rules.standalone
      rules: []

    - name: falkordb.rules.replication
      rules:
        - alert: FalkorDBReplicationBroken
          expr: ((delta(redis_connected_slaves[1m]) < 0) and on(namespace) redis_instance_info{redis_mode="replication"}) > 0
          for: 5m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB replication broken (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] FalkorDB instance lost a slave\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            view_logs_prod: https://grafana.observability.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%20AND%20container:%5C%22service%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}
            view_logs_dev: https://grafana.observability.dev.internal.falkordb.cloud/explore?orgId=1&left={%22datasource%22:%22VictoriaLogs%22,%22queries%22:[{%22expr%22:%22pod:%5C%22{{ $labels.pod }}%5C%22%20AND%20namespace:%5C%22{{ $labels.namespace }}%5C%22%20AND%20container:%5C%22service%5C%22%22}],%22range%22:{%22from%22:%22{{ (index .Alerts 0).StartsAt.Add -300000000000 | date "2006-01-02T15:04:05Z" }}%22,%22to%22:%22now%22}}

    - name: falkordb.rules.cluster
      rules:
        - alert: FalkorDBClusterFlapping
          expr: ((changes(redis_connected_slaves[1m]) > 1) and on(namespace) redis_instance_info{redis_mode="cluster"} > 0)
          for: 2m
          labels:
            severity: critical
            cluster: '{{ $labels.cluster }}'
          annotations:
            summary: FalkorDB cluster flapping (instance {{ $labels.namespace }})
            description: "[cluster={{ $labels.cluster }}] Changes have been detected in FalkorDB replica connection. This can occur when replica nodes lose connection to the master and reconnect (a.k.a flapping).\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"