apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: falkordb.rules
spec:
 groups:
  - name: falkordb.rules.general
    rules:
      - alert: FalkorDBDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: FalkorDB down (instance {{ $labels.namespace }})
          description: "FalkorDB instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      
      - alert: FalkorDBSentinelMasterDisagreement
        expr: count(count_values("master_address", redis_sentinel_master_status{namespace="{{ $labels.namespace }}"} == 1)) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Sentinels disagree on the Redis master"
          description: "Multiple master_address values have been reported by Sentinels for at least 5 minutes."


      - alert: FalkorDBMissingMaster
        expr: absent(redis_instance_info) == 0 and count(redis_instance_info{role="master"}) by (namespace) < 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: FalkorDB missing master (instance {{ $labels.namespace }})
          description: "FalkorDB has no node marked as master.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBTooManyMasters
        expr: (count(redis_instance_info{role="master", redis_mode!="cluster"}) by (namespace)) > 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: FalkorDB too many masters (instance {{ $labels.namespace }})
          description: "FalkorDB has too many nodes marked as master.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBMissingBackup
        expr: time() - redis_rdb_last_save_timestamp_seconds > 60 * 60 * 24 and rate(redis_commands_processed_total[5m]) < (rate(redis_commands_processed_total[15m]) * 0.2)
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: FalkorDB missing backup (instance {{ $labels.namespace }})
          description: "FalkorDB has not been backuped for 24 hours\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBOutOfSystemMemory
        expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: FalkorDB out of system memory (instance {{ $labels.namespace }})
          description: "FalkorDB is running out of system memory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBOutOfConfiguredMaxmemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90 and on(instance) redis_memory_max_bytes > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: FalkorDB out of configured maxmemory (instance {{ $labels.namespace }})
          description: "FalkorDB is running out of configured maxmemory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBTooManyConnections
        expr: redis_connected_clients / redis_config_maxclients * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: FalkorDB too many connections (instance {{ $labels.namespace }})
          description: "FalkorDB is running out of connections (> 90% used)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBRejectedConnections
        expr: increase(redis_rejected_connections_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: FalkorDB rejected connections (instance {{ $labels.namespace }})
          description: "Some connections to FalkorDB has been rejected\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: FalkorDBAOFFileSizeExceeded
        expr: redis_aof_file_size_bytes > 64 * 1024 * 1024
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "FalkorDB AOF file size exceeded threshold in namespace {{ $labels.namespace }}"
          description: "The AOF file size for FalkorDB in namespace {{ $labels.namespace }} has exceeded 64MB. Current size: {{ $value | humanize1024 }}."

  - name: falkordb.rules.standalone
    rules: []

  - name: falkordb.rules.replication
    rules:
      - alert: FalkorDBReplicationBroken
        expr: ((delta(redis_connected_slaves[1m]) < 0) and on(namespace) redis_instance_info{redis_mode="replication"}) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: FalkorDB replication broken (instance {{ $labels.namespace }})
          description: "FalkorDB instance lost a slave\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: falkordb.rules.cluster
    rules:
      - alert: FalkorDBClusterFlapping
        expr: ((changes(redis_connected_slaves[1m]) > 1) and on(namespace) redis_instance_info{redis_mode="cluster"} > 0)
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: FalkorDB cluster flapping (instance {{ $labels.namespace }})
          description: "Changes have been detected in FalkorDB replica connection. This can occur when replica nodes lose connection to the master and reconnect (a.k.a flapping).\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
