---
# Source: victoria-metrics-k8s-stack/templates/rules/rule.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: k8s.rules.podowner
spec:
  groups:
    - name: k8s.rules.pod_owner
      params: {}
      rules:
        - annotations: {}
          expr: |-
            max by (namespace,workload,pod,cluster) (
              label_replace(
                label_replace(
                  kube_pod_owner{job="kube-state-metrics", owner_kind="ReplicaSet"},
                  "replicaset", "$1", "owner_name", "(.*)"
                ) * on (replicaset,namespace,cluster) group_left(owner_name) topk by (replicaset,namespace,cluster) (
                  1, max by (replicaset,namespace,owner_name,cluster) (
                    kube_replicaset_owner{job="kube-state-metrics"}
                  )
                ),
                "workload", "$1", "owner_name", "(.*)"
              )
            )
          labels:
            workload_type: deployment
            cluster: '{{ $labels.cluster }}'
          record: namespace_workload_pod:kube_pod_owner:relabel
        - annotations: {}
          expr: |-
            max by (namespace,workload,pod,cluster) (
              label_replace(
                kube_pod_owner{job="kube-state-metrics", owner_kind="DaemonSet"},
                "workload", "$1", "owner_name", "(.*)"
              )
            )
          labels:
            workload_type: daemonset
            cluster: '{{ $labels.cluster }}'
          record: namespace_workload_pod:kube_pod_owner:relabel
        - annotations: {}
          expr: |-
            max by (namespace,workload,pod,cluster) (
              label_replace(
                kube_pod_owner{job="kube-state-metrics", owner_kind="StatefulSet"},
                "workload", "$1", "owner_name", "(.*)"
              )
            )
          labels:
            workload_type: statefulset
            cluster: '{{ $labels.cluster }}'
          record: namespace_workload_pod:kube_pod_owner:relabel
        - annotations: {}
          expr: |-
            max by (namespace,workload,pod,cluster) (
              label_replace(
                kube_pod_owner{job="kube-state-metrics", owner_kind="Job"},
                "workload", "$1", "owner_name", "(.*)"
              )
            )
          labels:
            workload_type: job
            cluster: '{{ $labels.cluster }}'
          record: namespace_workload_pod:kube_pod_owner:relabel
