---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: vl-health
spec:
  groups:
    - name: vl-health
      params: {}
      rules:
        - alert: DiskRunsOutOfSpace
          annotations:
            dashboard: grafana.domain.com/d/wNf0q_kZk?viewPanel=53&var-instance={{ $labels.instance }}
            description: |-
              Disk utilisation on instance {{ $labels.instance }} is more than 80%.
               Having less than 20% of free disk space could cripple merge processes and overall performance. Consider to limit the ingestion rate, decrease retention or scale the disk space if possible.
            summary: Instance {{ $labels.instance }} (job={{ $labels.job }}) will run out of disk space soon
          expr: |-
            sum(vl_data_size_bytes) by (job,instance,cluster) /
            (
             sum(vl_free_disk_space_bytes) by (job,instance,cluster) +
             sum(vl_data_size_bytes) by (job,instance,cluster)
            ) > 0.8
          for: 30m
          labels:
            severity: critical