{
 "title": "LDAP System",
 "description": "LDAP authentication system overview",
 "tags": [ "ldap" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ldap_auth_attempts_total,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Organizations",
   "type": "stat",
   "description": "Total number of LDAP organizations",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ldap_organizations_count{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "stat",
   "description": "Total number of LDAP groups",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ldap_groups_count{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Total number of LDAP users",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ldap_users_count{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "description": "Rate of LDAP authentication attempts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ldap_auth_attempts_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster, namespace)",
     "legendFormat": "{{cluster}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Bind Operations",
   "type": "timeseries",
   "description": "Rate of LDAP bind operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ldap_bind_operations_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster, namespace)",
     "legendFormat": "{{cluster}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "User Operations",
   "type": "timeseries",
   "description": "Rate of LDAP user operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ldap_user_operations_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster, namespace)",
     "legendFormat": "{{cluster}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Group Operations",
   "type": "timeseries",
   "description": "Rate of LDAP group operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ldap_group_operations_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster, namespace)",
     "legendFormat": "{{cluster}} / {{namespace}}"
    }
   ]
  }
 ]
}