apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.falkordb.cloud
      secretName: api-tls
  rules:
    - host: api.falkordb.cloud
      http:
        paths:
          - path: /v1/db-importer(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: db-importer
                port:
                  number: 3000
