---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-importer-worker
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-importer-worker
  template:
    metadata:
      labels:
        app: db-importer-worker
    spec:
      serviceAccountName: db-exporter-sa
      containers:
        - name: db-importer-worker
          image: europe-west1-docker.pkg.dev/ctrl-plane-prod-b1b92df2/backend/db-importer-worker:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: db-importer-worker-env
---
apiVersion: v1
kind: Service
metadata:
  name: db-importer-worker
  namespace: api
spec:
  selector:
    app: db-importer-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
