apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
    targetRevision: dev
    path: argocd/kustomize/fluentbit
    kustomize:
      patches:
        - target:
            kind: DaemonSet
            name: fluent-bit
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/env/1/value
              value: "{{ .name }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: fluent-bit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
