apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana-operator
    repoURL: ghcr.io/grafana/helm-charts
    targetRevision: v5.16.0
    helm:
      valuesObject:
        fullnameOverride: grafana-operator
        nodeSelector:
          node_pool: observability-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
