apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-secret-generator-ctrl-plane
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-secret-generator
    repoURL: https://helm.mittwald.de
    targetRevision: 3.4.0
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true