apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    chart: n8n
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 0.29.0
    helm:
      releaseName: n8n
      valuesObject:
        config:
          executions:
            mode: queue
        secret:
          database:
            type: postgresdb
            postgresdb:
              host: n8n-postgresql
              port: 5432
              database: n8n
              user: n8n
        main:
          enabled: true
          replicaCount: 1
        worker:
          enabled: true
          replicaCount: 2
        webhook:
          enabled: true
          replicaCount: 1
        redis:
          enabled: true
          architecture: standalone
        postgresql:
          enabled: true
          auth:
            username: n8n
            database: n8n
          primary:
            persistence:
              enabled: true
              size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
