apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-operator
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: v4.12.0
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
