apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 2.17.2
    helm:
      releaseName: sealed-secrets
      valuesObject:
        fullnameOverride: "sealed-secrets"
        nodeSelector:
          node_pool: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true