apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.65.0
    helm:
      releaseName: vm
      valuesObject:
        fullnameOverride: "vm"
        defaultDashboards:
          enabled: true
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
          dashboards:
            victoriametrics-vmagent:
              enabled: false
          grafanaOperator:
            enabled: true
            spec:
              allowCrossNamespaceImport: false
              instanceSelector:
                matchLabels:
                  dashboards: grafana
        defaultRules:
          create: false
        victoria-metrics-operator:
          operator:
            disable_prometheus_converter: true
          nodeSelector:
            node_pool: observability-resources
        vmsingle:
          spec:
            port: "8429"
            retentionPeriod: 180d
            logFormat: json
            nodeSelector:
              node_pool: observability-resources
            resources:
              requests:
                memory: "2Gi"
                cpu: "1200m"
              limits:
                memory: "4Gi"
                cpu: "2"
            storage:
              resources:
                requests:
                  storage: 300Gi
            serviceSpec:
              metadata:
                annotations:
                  cloud.google.com/load-balancer-type: Internal
              spec:
                type: LoadBalancer
        alertmanager:
          spec:
            nodeSelector:
              node_pool: observability-resources
            secrets:
              - pagerduty-service-key
            configSecret: null
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ["alertname", "namespace", "pod"]
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: "k8s-alert-reaction-operator"
              routes:
                - match:
                    alertname: Watchdog
                  receiver: "blackhole"
                - receiver: 'k8s-alert-reaction-operator'
                  continue: true
                - receiver: "pagerduty"
                  continue: true
            receivers:
              - name: blackhole
              - name: 'k8s-alert-reaction-operator'
                webhook_configs:
                - url: 'http://alert-reaction-operator-webhook.observability.svc.cluster.local:9090/webhook'
                  send_resolved: false
              - name: "pagerduty"
                pagerduty_configs:
                  - service_key_file: "/etc/vm/secrets/pagerduty-service-key/api-key"
                    url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
                    send_resolved: true
                    client_url: https://grafana.observability.dev.internal.falkordb.cloud/alerting/groups
        vmalert:
          spec:
            nodeSelector:
              node_pool: observability-resources
            externalLabels:
              environment: dev
            ruleSelector:
              matchLabels:
                is_logs: "false"
        vmauth:
          enabled: true
          spec:
            selectAllByDefault: true
            userNamespaceSelector: {}
            userSelector: {}
            nodeSelector:
              node_pool: public-pool
            unauthorizedUserAccessSpec:
              discover_backend_ips: true
              url_map:
                - src_paths: ["/notfound"]
                  url_prefix:
                    - https://vmauth.observability.dev.internal.falkordb.cloud
            ingress:
              annotations:
                cert-manager.io/issuer: letsencrypt
                kubernetes.io/ingress.class: gce
                kubernetes.io/ingress.allow-http: "false"
                kubernetes.io/ingress.global-static-ip-name: "vmauth-ip"
              tlsSecretName: vmauth-tls
              tlsHosts:
                - "vmauth.observability.dev.internal.falkordb.cloud"
        vmagent:
          enabled: false
        grafana:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        kube-state-metrics:
          enabled: false
        kubelet:
          enabled: false
        kubeApiServer:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeDns:
          enabled: false
        coreDns:
          enabled: false
        kubeEtcd:
          enabled: false
        enabled:
          enabled: false
        kubeProxy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vm-victoria-metrics-operator-validation
      namespace: observability
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vm-victoria-metrics-operator-admission
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"
    - group: ""
      kind: Deployment
      name: vm-grafana
      namespace: observability
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
