apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmalert-logs
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-alert
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.25.5
    helm:
      releaseName: vm-alert-logs
      valuesObject:
        fullnameOverride: "vm-alert-logs"
        server:
          nodeSelector:
            node_pool: observability-resources
          datasource:
            url: http://victorialogs-server.observability.svc.cluster.local:9428
          notifier:
            alertmanager:
              url: http://vmalertmanager-vm.observability.svc.cluster.local:9093
          remote:
            read:
              url: http://vmsingle-vm.observability.svc.cluster.local:8429
            write:
              url: http://vmsingle-vm.observability.svc.cluster.local:8429/api/v1/write
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true