apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmuser-metrics-reader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
    targetRevision: dev
    path: argocd/kustomize/vmuser-metrics-reader
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
