apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

resources:
  - ../../base

images:
  - name: us-central1-docker.pkg.dev/PROJECT/backend/db-importer-worker
    newName: us-central1-docker.pkg.dev/ctrl-plane-dev-f7a2434f/backend/db-importer-worker
