---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    enrollment-key: AgBRt1mpb7BwFfHtw/y7cNa0+bpOW0wMAG/fyQYza5hdsovXKCigD3Q4EIzeqH/xrFQfWlNuIPWGhrJSAyoZefYNKwvzrGCE1VEIQRkgpVhwV4aHujmz0MiqPArHp/VfkNNIy8l+ZMAeTAltPz78OkeP+1UDAj9P+GKxLXPtisf02Vje0132O900W/timDg7Acpv5CJUWoh5QCoH7HqkMguZ2fGuF2E13Nql1yb1mjvG64BUNemGSvyadNO8BG75BpFZ1LUCYKVmS40mQEjEyGXwMTXAAgpWvB5LdgyW3RsLw/dhwb5u09/z6GUwF6VSi4A/d+51/bD6gX5WfdewuX6Ir6fToHAAHsXOn41kogXHLujwSll4S7SyfvOCb7oRDKK1vUzxcbHgbZTCDGhUxc6DpvClgBm9bIZ4q8GJtu/sRHT3klf2YnOeDlylmbs3ZdgNrInEMPlMxghwJaSBaUCkkHMQnweQrbC6MdsD5/u/aZG7dK8PeWx6LYf08skgP8HerTzpcqlc3kgpdbaFhgVk6v4sKF7duTXkJe5SgiGRIsG6PKYf2eTa4JY9JELf+sbmh6ANn9bKJha/+ENd1E/Qq3Vde0hGs6kLsda68n9wEFIne7HbmtZADQaYEYGisVa9KndeLUbcQhL9yDg85ZEh6vztof/nnkq+sLg6iFIhub/OyNPlKtG7uLUTuBANWmTm3ZCQEoIuKdgq
    manager-ip: AgAohtPK6M9WHzhvNV1Y4AEGJgyumCKg8QjTFeYZAv99rxt3VY1WlyRIaFbvLcp3LM3Nv1zINP8jyi1w0Lx7lAOtg9sRNu3usS66xKq2pODNPN1QdtcIVjyxnCc79Y8gBHrn99XuBZO2Oos08bRQ6aJ1TU6V2VSCbTrO6JIHkHw9QHZLI2Yt76FmYpywd73XRkK6tZOsn6IFQ2BC/QW82mR77FBDpd5KlX1jIQSSw8JElaWBLL2pBLNT7/6/4syKv/6U7PnCoVdP3v/UBbM4DkAQaetpUCxoDwIql61kQTvIYswfVnQTBlfaVq2tb2VoBfNYm4tjlHqCtD6npTzCfbrlPElHEDnfPutWAi8Wwy1jS1hp+XwN6VLpAEou6bd6KPSgUWGConCdfZFQkD7EzjuJtBULki4iIJuzbqLBBvdv3vfX4ApiZA+WPSIOBVE7evqYoozfgth7er7t+nk+qFsWXnGodI1inIMA/nTErLJ1pdkYsegqQKoIPS/27VQd31PZS8/6grPyx5j6q2V96PJtEDcTL2T7JS9vvfPDGVF74pXBSkQ5EXNYhovov0b4dq7V6n5NYVzKInlcTHQfflelSbP7Ocw9L3+5sFzBlrb4lVB3Aolbm1GyGVTJ+p1vF0Wm1bB1/3Srw4+QpXYre39Oyn7+6/njTlhEaqK0qfQFtatEul7T7YXwD4MINOuNOhtcWWqViyJ0g9T2
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security

