---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    enrollment-key: AgB8rlz1/IuldwDbps58p5GYyTpuMsF6vITkDwhkZtvR8a1PVQ2qfcjtJ+IJJvAaY8UcKxwgIlFlEjaDr6zZxc93wEpro95tXIrItctIbyykrbxOuh6LjuOW+Pkm2zW1H7eU2iTo8HS1OxuMn/GJK0+y8HjnIH1GFlnxRBwiCrmJxkFBcWH/P971MlfdDlnxTJ4Alnpq6+F88n3LBv0LKsCxiNoSIP1x3pAiGjNq14ZSmYXdxG8sQ3ZwozSdB5ZOKpG/sN/32/K6sG3u9lfHAyEbceyI4Oh9wbqiJODNOJTXUQzUs9c4UDrQPQCN1hPCBywe1MgsyA5sHUoPIwr9RjmNtgW8og0BEP72jlEAkVBb4LQjElIMf4LbL0DMLCGJc6Ngm09Dpnz7ZtxY5K+Cz3bD7HzHGS8fI2ts/jUOLAMZaZBt5EX7rM4DWW55rIPQKTUSx7irU5NEYWbd86OHswjP1ZreVXksCprBbeqtEtQRekA7JN2bdKjTwnbhSwxPuMAWaTNbfA714wUzrbgIBhxi7N3+fvVa59r2SUf8jTJATgxwp3UuX9sCJgROqNk1DGIYh47wMEHTc/1eZDej0KtUwEb42vPTup9qboWENyitXdey4QZKDEFPOHcNrG1JKo1TvAJZIPR9bUa4vdMHLtyIGrcjsXGXzrSm7jy5HOBqZDCt2F7mNxB2gk7xiNnl/odHa6D1uR8YTovlobqT3/P3UonWy2/tuzLFxe2bjBaBLiA0FD9BPWfyJCZ7UD2vcYLj8A5Vny1xBL9J+anfUr+B
    manager-ip: AgCXxN63jNmStR5DeaZAMAJsoXFvUCmpE8LKaI2cjtGU+zJ8Aibn5HHTTY0M35MF2nFkevGOa2mb+Jqzy0iWWEbZctnGwlnjaA4/7UMd9t8MQWKBpeBuOKdYi6AmGpLBBeehFEsQe+UzQ0MuT8vpUvjwANxwFrTTfhEhKbKzdy1rfl+4RptE/w2WFiB6tGlmdkaHeCn1OVOZTAuuR6WILkrYjPZnCF3kOeMbixxTaMtugJ5+GvlxYu78A3RHVq4o5+7tg/4xqeO/z/u7tg7JzKw5gdIxvfJVd1KV6jIdPSvJK9s2eQymJ8yRsdvgCDVWBP73PdNhshLQhDgj1HFWl5lDBYwv3Suqt+oMjGsBSSZkELzv5PRfbDcurg+2FdvHQbGLwVXdHzZxOoRDREM0wlcPW26XbiacCRf1GelVX4/HHZFK4FlcRgO8Fb3TkfpbEUgRSMdWOS1iL7qZ7N9tSYZuy72tTlc804Knj/3en73MnCFTWcsf3K/uqYFEAdi9Ry2wmElTd+p5/smWnjdYEg1mNUMy5unqQ5T+38dearPSV02tWh/oRZUNLEieDxnpNmtKiivglD97VAjhH9XjOMqM6XIPK9JiFa5xrSVoyIvz23COf5B7ChESbFnLFigzsD8hZWb5JOM2KT5TmNbkSjapaCOXc8j6/wcS6UVrTmy0lymQT/qhFoBy26lbNjrUkcQuCX5u9NG245o3CZF4
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security
