---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-azure-credentials
  namespace: security
spec:
  encryptedData:
    client-id: AgDP/fYqpe8QqHzdFpq48diGvK/nU6nhubhJn6YZgdNrfagyNAVsMGSEG9VSdpupmhqlHRpLRx7yaFoA3DfCDMNbmFsSNx0ToVuI1r0oIC9mTm0c2X3NpKe/2xIzyRYt3CYkte2RBNiDiFtN1nOTc4ng+kKw3wAvSDOw685/rbw2dnzkIhgrTfSX+tr0zBDRAmeTOxEoikO5S3gsYTCK1i7wSfNigAE/6d6bZgbfI2pz0CrNjM4ti00cogepsuMSRquOcFTaJnWK6n3zMQX2v/1ht/tzqxxrgxLkBIolIaw23GcdIKog4lzB7i+sZ47LseasVQIhAn3mzmYypOu74vIZX9MrzU0TwCSTNqpPtCRdLmH3wibyieteD2OY1N3JAN0CzZZOvU9Uc1w5x5X5NtIEKQMNjr19yZqj/fO7pTPb8UDI52oxWszc4yZLib6APqvjjI9Av1xkrZhDHuh9geCgcgm9EaEPeSuZajnfHQjzi+yg/LmeC/PFjMmtTxUmrS648J5twZaQKdKBfN9K8m1Vk7cmJrCzKsrNYf9NhexsRNzTCN9OV3+M8wAfcXFgnKuCQoBvQfvEJGmu5bjvFUs4R1CoKbMU46yOpSpornXpVPsz/BqsGylABU2oaNJO9rcfyiKUfvlaSVBG6yq4Iic3HD687Jt9tRUIqON12hGAl8KrzVESqq+2ViISmFHGBwZvPHb7GadIlcYY
    client-secret: AgCVbsLkHRijyClQT3gHfYvm5ne79Ryx25aRNf2GV/ge1IltZKoyQ1LGy/wF3XQjPS4m1bcK+SSwkY8zvaA1RC7eso5TZEb1CWbUOBy6re84F4GwH1d+zbnn1rkv39O8Darp2m0e07L8Z0iBoVg1QdzbcV7H6s8zhi4AbKFgwi7JOlYNFuociOWuSMQanQlZgo95JwLNwviqnp4UUMe4Mox3VOFlKGRtfGgYj3iSCWWS81XPbxe7qg36aa3HuAyljmwAo6JRCfuBq7lsHv0alFbnq5TgkiaY4D/D4q4ZAp6STf2NXpH3fAdS4KmClUk0bY8uNYFWWAQBVXW3wZKv43argdznwmvzTAJKpZA35gJSBvkVw7BH+9OK59xoz6dxM6XxP0VDTziZr8kSE7Oz1VQ6USyOyretUwYGAkUT7f3zSWaf433JITr80/aYSKAhU/pCQjK6qbHpNAIgKuY3XTx5Ke+4Vy8W411AjP4giXnyCmhbOD4OwN/0DxjfuqEug3ZO/KMdq3vH5WdvQRNokgoyhxS5Y2jnDYAo79getTq7FWOk6/TQGLgTDrQ7swLAU4EJzWTWcqx+k45yqST51vGx0p4nmMSEmE+l7ZbKwRHLHZKmbXD6pAItjq906zvBm2R4irwO1RMMwIfPh8hzGX+pfh5diYsn/8m3FYiSkrJupm4EPo6/eR+DBWIEZC3jVjjqPBsXd0rTA5Pc
    subscription-id: AgCgrW7xnEtbX0Fr4f9yGy+XLsHXvKw/jKJZfl4/XVehnmxu9DFfuTdzABfYxWENSKXPxE69NYt51m/9kc+jFipxqfA9VBdD9WzkBnNr6yaaaimpFByPRupG3lFnc+VOYF3DR3QPAkEwoUdRIDFDdubUFB9v4eq6loX0VpmsANf03sH/H/ml90FtlQmDrfk4d+4IhDDRaorV882uxLz7U/LipmZLQFLeHC5F3SeUbHqr6tzaCeJHvWB7v2ZtZRJdNJkYdjXY7xZQKpco3aUMhvAyzFOPArZPhZtukhISaPi1LDrcm94Xkrjf9F8LKwhoEfhsRBJx/4Dri24k2i3HCj3FcvMRDwHjU+E9yiR11EZqzL3zRqLta+kCQ4ucNOsT2dF6uXDJq4pDvX4gQNoMi3sqjDMB46OPr8mYbT5PgSVG+WQ3jJOZ0QSevhKAzNdsRIDAqVb+PS7N9srHAnOgE1TqLv5CoBLakXRDuPf3QZIuEbiSypPtH8zchPzcoJzHYA3g88pGDTkpdqCs4yr2nie5wzCaXtmXpbI4BHlVXBwNCKc0rpAdd61+H2TVQlrc1yy89QRqI0zbjjVEWH+1X7VhA4Y/530Fru/pjSc7GiZ6fJH7NbzM6HJvFy9bZ30Me4HAWrjae9YS6cpyvelntmZ/qDKKQ1/CItEzgZC7BdHKv4chGEVdkXm886SzhXd8GqDKfKEXsEDU5dZf
    tenant-id: AgBStIqe3t8fdFUKOiGIJiT53piqnbZVAwgHr+DIVnHGycv6uMFmevusCqGSez5SqqJm/4d1nPUqqdGAijGvraoUFOG9T+6ZGJE9dI6uiAI/RzRbG+J4jfRsWUbuRN9g+eCAv+kHHZyTcEQb8h1I3en2K9F79NzEPNrSgDL2NHSdg4gHFQSFBCFSpSepL+FWkN3YQx598CUM6+s0LJTXjMCvvfD9WSEoHoFMbEZexpBj9QYfdLMkOjhOKeisYav0j9Av7f3bqDMcokW7cJ4KlCWqb+RWj+WnrS6X8ApvcghUwuRUbKdfXErGtGj0vZHoER8wjHhcwhz20+TS9lyKuNmpJ3qFEBH0Bzg7KpyLFNLJdo+8Fd+dk9zh3132CSSHWWxjux+PmBdwwgrl9M4z+t11KE2Pm7VguwkvcQvSEvVl3/Z1U8R02FxRmha09wHfRjz+GpTJHr+6PMSHhU8/9OIehilPF97ifM8DG3LTtxMOars2pAltUs06/nowdOeC9r2XRPpK9YoQ1VJio6e4DdciGGcJ8oPQTEqMLKPwIIKrz6tZVLynNiUOncmBIQ//vr/h6b4BKBNEDyV/7J+M/oDh099q3pyuih0TZnBzx4yuVDn6TyNFA/pfcWS7VC+K2fXBj4RTDuyB91R6cNM06VDkaFQmjQq9aCJaHhQui7wMA/ZN3O2YtJCbvg4I0e+BwwFOtMRHjXXQRURX
  template:
    metadata:
      name: prowler-azure-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: AgByup02l/MrdVdaupp4kwJ+kAnTzBuP5i69SugFDWL/IAkRdg/ebIOTBpQXrrg3v8Ba6g53YPJ9CGvhJzRi5OujshwfxWkOqLgBNC8XiGJBX4CG+m9FcgAjS65EsZ53vLz5g+42HEWtymaNlpi4Cp7yF83/4dN5k5EMeWTMj/+UpDXTScx2NaoWjSBoFziKihL6pdWCFc+TPkv3DvcdOiIsY16SEgDAr08Fuhw/ye5XNH+6Sa0aG2/eVmQpmafaEcSzOjbpy0IJqVdkuhWFFfs4fkNyrJ8S9kOBPTGO7yWDUIpChulSnsjhcrFIRP0B5wwA1YXdZBsbwmiFNRoNcse7ONorhRarmnw8AI3w5acDf1sQYJIdgi5lR/E4l+DDcPaqaFAX8nOUDdxmECZ5dFAQ+LvNaRSvm37Xp9/qom2B8OUiGjEOlb04iPaZHGwlRZPdHE6X2kGGMqsYf+JM9s/9zrwDi8FLNASdi+iuuMGnon/lbTjfbN168irIijraeIM2V1+KLJfGhmdW6AqKB94n3ulEJJLHLHdEZTcLwAd08hLjUlywSXrXB2SiUOOmMrRgkd7yeU3luFOV1Bt0LUtQmGMokREpTHd1fOL9+7mJnLYC2y2dwLgiZnAIDzkqeZg4OsZTlt7LHd3chbmkZ33Iby2eG0iWvTkLcR9WM0NUijU9OCCyfRPevgaYWNl5cumSnCVqB4/Zw54o
  template:
    metadata:
      name: prowler-gcs-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBZtaAfN9ateJ/dohGFxue8UAv3LJL7ARYJudsPb07A4nTxhq07e075+JP1qYs8MtRsZJfF3W0W/coMIzOFEMed6uHGV9FvKZ7qNQH86h4fLAgFXDHYiV5shnCuPsuFlT7GwubErjg/+CvuO9ZT5GJGvHqqtKy6Cv+ZTOavotKglzjg4BEMMLnY+xzzO1rpKHwAXh6Ot0J2UG3NwY1YdhON44ZPeqmYaX/C6ldb1vN0xuxui0JfHI56ZU+N9EKeJTJYRlnv0nbJ4n45W48XrMUbaCRMvUBoMG0BQioZeOgLrqBsQPeILFdD6KjTRmVcUsNFE/j9J2n66S8LrQDi0Vkg5x4y862zaM2imIFGvIFwi3iUPSOqWCnjQglgCoCN2FggrWDHzbYM/svHuDvw9s8MpdhtCFLTtBM6CcXJZwrC3kbBA6CtVPDynZDydlBL7Wjo26gymsn9oxHQUVg4t1o9iAF7CX4KMfR5ccaLmVuRt5xTkff3znbac6u0uZSo46lL/gJkkGjVlkMi6ni6ExNsLB9MWVU8YMO/q3gtlbA8bPZ6TOqxgoOn68B+qtLAgg4za8LDMMNv6CT8v2bcvX6UCpBojrLAERjWPcRyZzQyFBiC8P4qfm8EgL3hT4bh1Vq5wfwCdWZAzb0kjCPXyuq0OCmq6S3p51d+5KSxQSBm8oJw1Ckk6wF8qad2JDYEcQf5/KOgGCMXheKt
  template:
    metadata:
      name: prowler-infra
      namespace: security
