apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.33.4
    helm:
      releaseName: vm
      valuesObject:
        fullnameOverride: "vm"
        defaultDashboards:
          enabled: true
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
        defaultRules:
          create: true
        vmsingle:
          spec:
            retentionPeriod: 3d
            logFormat: json
            nodeSelector:
              node_pool: observability-resources
            serviceSpec:
              metadata:
                annotations:
                  cloud.google.com/load-balancer-type: Internal
              spec:
                type: LoadBalancer
        alertmanager:
          spec:
            nodeSelector:
              node_pool: observability-resources
        vmalert:
          spec:
            nodeSelector:
              node_pool: observability-resources
        vmagent:
          enabled: false
        grafana:
          enabled: true
        prometheus-node-exporter:
          enabled: false
        kube-state-metrics:
          enabled: false
        kubelet:
          enabled: false
        kubeApiServer:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeDns:
          enabled: false
        coreDns:
          enabled: false
        kubeEtcd:
          enabled: false
        enabled:
          enabled: false
        kubeProxy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vm-victoria-metrics-operator-validation
      namespace: observability
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vm-victoria-metrics-operator-admission
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"
    - group: ""
      kind: Deployment
      name: vm-grafana
      namespace: observability
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret

