---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: security
spec:
  encryptedData:
    API_PASSWORD: AgCVCpr2qLjE9fQV3Otcsh87MIiBbjsHr1TDQ6+EpxsoBHaUebCsG+FsxY5vRX3SXyLe7dsFv5IH+2ZW7WVU88Uxdo9WpleuZxtxeRldX/zE0m7RIN3w0cm/ul+t73sS1QJ+TWeoHaklwzJiOEaOogp0ccFjuZ5qESi4mxLYSeMJebEW663TeMxdCOwCCJ6cnHg8XlIW2b5J2lFmEzhr4zKcJo7tPEVrvktsxzoa7vEhcL3KBfyRiDwOjvy3Cr8XPnEtAxncud6nuqa2R7KiL1mmnQ0//NjNH6X3G2UNHoqSyBZtg4nzCGNmFW7CyoG5BFFgcDBLp+//1KJAJ96geyYt1KtH6/ajKcCWS0L9qiiorcveRna28MMcTy8DzjArOvAPXldV6Oizzr6/jatkKCcP8AoJqeoiTVHl802pp5SYBhmK73rcwSR3HoXfG6rTe/h4gdvIXSPnLDztmu6v2wj99FpXv17BYrSkJuErprlm7tQQre8QPwIijEmtjuX1fYhOH3+23Dz8fygbiAm42Poxo/eNw1ZGccBFWN/jVRWGzp4r7T/gqNUXS9o0yeC6Ulr9+sjmmw2C5gahMOzbSw6h9P4E1o/G5dQeushPegoTCECC/s7o/rpNcXb6STgeKH61yAagklHktPzx+SeeIkFCV6W5AwmUQiTapFrkVQdmowQeAyQLO0qiO5Ia63d62JUMOGLhJ0/44cjAIIbwz9oE/WTOKNuY+HDZ5Y2a7MrqY60qicc/Hld0AlvZ2824qvyagAhF5w4jkO8dLkTn3tKv
    API_USERNAME: AgBTEFtpkxjMq+DuMNkwpVNPexduGcQIZR+dvhSCsor4ncwdm+Ayvg/SLGzMyVoshhDHQUj+XKiajjMqT0zeSYlBk0mzZ+m3P0R/LcWZVqcfZamrk8Rq0syepupTD2XPD+hQccRqwmi/T30GUmYdsF69gsFHbcec414b8MvLamuXFh54oq9KpweGKoDWxhr00WEitdWqCQioQpiYXy/IRoPpyDdMvy1lRxpUF1CHfjmwVoFXfOgY5yRGNcLRO8s8NJOSdqekR+PhssYm0kRzEpS/bKIKhlF48zHTE5YFemHVX76hKoh89QQb9VO8Dl169HQV6NKthpMJu7DwVS64hFbjh/5JgSoRuD5L8qF9ROZv0zQC2ugPm3ePI6g13ozxNvfVeRLoPaczGJ2yIXUTLvBqHkDGi4mlMz5RXNodr95Nl18yK6Ixvk9iqR//vd9q7PbiBwBe5/p6lQPqWij54HVxBIf3fY+WjKTloevWExbsVmuCmQ7inR4dLJRFS2EefXJhMswayAtNm8eGPLbkjhCIAhGR0jB690ii3QWiLAUHrtyDZqhEWHyHq20ae37JQgG34xQVWOr/P+32J/ULSGCCI8oXsoJGVQOgaVeb8tLG7atli4itnrBbPEn6m6I/uhTNVVIkIJ/g868/jhShWN1Xor46TtNMi8umooTMUKvFt98QUvX27nNGT+XpEPW8HjMJmHmhX+KEUSo=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: security
