---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: security
spec:
  encryptedData:
    API_PASSWORD: AgBg8ANGNp/yzsFB2JRlTOU/K4uyTzOBdzWYyZLp3NpdE1OD9Yj/wtZdAY9p0xDA8BDdQqddDYa9Dkuft1QEveRfcNAslfO2yAcomMURMOOFvvX//GPNtWJLhF7tCUfOROVY53V99NZLf/NIS05qtQmO65CXfCY7WyqjO0kcSWsfpcok7I9jrx2yTlAS9F91rr1Bft4MYcfjoakMKUMC5/s8JQstL29CKwTW0IboqVvPsoA/hZAhEl/q62sEFCFI43RpRIQ+nGVjQseG6nI+W1frjc5Yaz0B2xSTgzBNaT6PyGw3vEMGSBHCNrUwe7P8tXlbBzQEb2IYwlPw428776rs45nSoqGG2v/zkEBC7S9z/N7RdHJrkH4XRV9/oIEcNwmDyUxDvU3U+o/bLu8VbqUJFl33eP05MlE503lT4bK2Dci4ykqdb/0cj1P/cyW4Jut/z1iS8QhOctlkM7EI8WDG7vQ0O7MKXxs1/z6es3suWXzbQ2hgQ15oYHVeVZM525/1D6mLXlCX4Cb77MGQNftNp6neUbd8PllNAnoakVByA7SJ/G2rAcdCePkySB9hXAacPobwA91s8HtnPw+zFliXNIRdINvEZAt1LIiGA/dWas5yQwETwpZdNgCybKC1hC8EiScxT7LRQYnvY5tweSlvorr/yftWgP5zyVMxaEBQvLAXRQ85prrBZuTfurADtkuypRQn1dPXzgN3ACEnE4aJ2yzhQ6OSLjx03tjSqsyCCB7vFWZ3vRDMQkk/mAyf6maj7TOYDCITC1quior6TNWB
    API_USERNAME: AgAGiq6rn+w9Acm1EKik3Yog6ghMZPGwuGVEAS2Cp0mW5VdpJSPC5sE5n4fFN9bBanRb/5RQdwGEiF1n3zAeQSEPP9K63C6BlfnCcZc2K2hqTqmzBjpXroEfs9XORPZjrymCaDY3Q27rVnPEsI5/XFBPntMJ0qM8/gnXlwP60VSN+QYZ5i5eWrHaCFBx9u0qQZUTeEJRxgg5IWKp5kkGigoa3WfM10z8zYhDHsIz7RP42Wjb0BMsOKm5qJFSgByGbYg83x5QrcyD5SZKXMSDhh7j0YEv/km0KEUY8xd86hwck5J0b0SXFDYHXs/y2b8aMRzi21XjVu83MG6gGqtorH81o/POx/C/tPnERpCd6nfv9VtTPV6JwWlDWJZLaGJglv3F+VtaFMWVUYpbu3urZM4eZlJMn6uowxfVNwS6WVSzQz2TByiGh5jANtqf7+B8/4SzZ76m+nMofpgWVu5By3T6vzkn6Kgc/MQrfoqGv6yhQvBaHbPSum7lv/hJisDLre4JtnkzAypTBjWg5UBmnobvg1Kp2GFbrJCEIi2bjdd5U1iVYywu7ARaEAOHPGybBoo1ayIgIn3UYxp71xwz0cst1C0mAcDhuhgIbD81FHIHXhD0HXPbIOC4oS4kGypcDjP7RxWakuQxejewJgzlwf+7DSS0DOdyIrQOSUxtq7j48ZnSsioiiJUGUshmVJ4fNTp8fO3EUELi/J4=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: security
