apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
  - api-cred-env-secret.yaml
  - indexer-cred-env-secret.yaml
  - dashboard-cred-env-secret.yaml
  - cluster-key-env-secret.yaml
patches:
  - path: service-lb-patch.yaml
