---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-manager-authd
  namespace: security
spec:
  encryptedData:
    authd.pass: AgAp5XXVtVilU4RkpJmJ9jEzMuh8axAQ8QE3xx1gRfcLD/QJBQWwGnIEFLA0+dCaNU4GpZFKjSBBR2OKDct/l1ss1LmlIdUY3FHgoQ2w/oYdmmypB+BNwW4OPfU5LYLeC9im4fS2BFWVmwffUbpe2xrbwFTdGxOQ2RBRXbVDST1D7GNifN1zFQ99GdMX+JLCulyWAAs3sg7bjJx53S2Blxj+bplW2PAfXfA9RW0iWUSKalKgV0IhSjP0ErbHqy7V9TSyOhAbXpQpwvNQcXskrvQt7jlhJfVTopvyubBgn8taUNWyeW8Ugao+JwOBhyNO3Mv66K1EOM8n4tcK5w2LqTGwSeqibDMkbhnI3T36424YdJ6XFOPBmwy3sJRIdB2BKogbWWGhN5nmG3W31+3rBNxckwQNfQoooxXTWl0YrRzyJPLlsMG7PMNFQRpczUZ9D6iVJtCGwELdWS+y+oEby4G5OWYFu4cjR2IoIWTm0ooHzDequnO27nL43pBJ/bfTwxXQM2V6VMxcF0WvefI5ZyMSuBJQbzDTdlBGmLiBdCT/UxuCjSE4CqoAdnqcaHGNSURvqKwy8fizAUTVCCRUgX2i90rJHcJTobeh/1BkiqowNP20kj5I13v/ZJWDmutCTT50hJr43eAt2vQoBTkB9EbUMG+fVkNHg2dSLRKIqDpDDUqaki3TmSlYk806j7FHcd7IY9UGM7UuStYzn6y+nwtqQZ95HaOsQ2JRNC3GVQUajqp5KPa1uyUkY2IyhVxXBekYrPZnPNDELHQnJ+t/EXmD
  template:
    metadata:
      name: wazuh-manager-authd
      namespace: security
