---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-manager-authd
  namespace: security
spec:
  encryptedData:
    WAZUH_AUTHD_PASS: AgCgxbhpWdC9cqBEOtwixBnml92Zdr8aP5VYIohVFPoF7rtnpc1SFaU4BlI106IdzYdbHqSzlYXcxOy3npQvCVC0kDMKZiVVARciideDzw++2JX+Lo2dVdAEJU8jyx7/nlGm+FDY9eiHb5B32PZwpxWAlRfpVloq3XlbVoAA52KJLpsBOUvY1Y1daIqM2ns0XNVwsxG/ha4KsVuMwpxoUf0hYMdV/ZL/eLBPkqaPqScC0apFL6vGgpq40WBuaNxrpmyf4qHBL1V3OLbqOy/pqUzgIUP0C9zmMfi4icBUXu/TV/tYnzBL6dWNQn4R3IOtX/P/2eHgcetUM6oodBdR0xM+acafwv5ry/vZWW5s8uJ3iib8jloVrE1V6PMW0mzT9OAsyAE+vS+qmM7FvaME+bq3w+dvjoJkAEKKTBUmXdRmqh9PZqp82B115FOmrrGs6S2nCWuVsDYSeyb89QhTo+/S1eui9gfzGN67mSG7VoEZQ/m34/kX3vDgHwOMQSSrwC/3MR3Drm8S6dZCwdP449IVTtcyyLlmFkGBjL4h729SDcBB33BLe2yu9lMFTkHd9SkA0kxYVfS0aWM+fBbR+DoGliE0NwqCfl5vh2kgpDZyc+OjHEIxNgVhVEtaMdh7w/dGyq28ClQNQKHAQ7sbbsoRSRSmNHtxbpKm/WhXr64Q9YApN6iY7agXS+ZA4XHasCl/PTjI+Hjbr2pWXsuHagiy5NEwDdebl0E9szsH9Y4h3cPZpZFIcXIxKJ+owhw1CANyh/V55kjcmQZYFjU1RGlA
  template:
    metadata:
      name: wazuh-manager-authd
      namespace: security
