---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: threatmapper-console-key
  namespace: security
spec:
  encryptedData:
    DEEPFENCE_KEY: AgBqa+TWL7Qzel1gLYUTMi57/ZY8NfXz1JF5/6IBJB54urLaxQQzxwnfw+6RtzjGhVu6HzLKv9nXrdy5ItJguRUwjLsYSgOkWKyYjACCTL4D0zpVKsNLZQ7/NAfMpdJEcZ7EhmzrxNRvc3OT6KBrrP9B9uv0fKlk7Kfr3I1bFDlGQXDyxTsJpWYDXWmXYF5rEMVQEW+26uhLn51eud4ech4U/qux1wWO5XMOCuqLzCzh2MQqphGmsktSoRHdsFm58S1yayCHSWz0zg4l8p7fojDCzAzvvHh5wACnj2pXtyIGaS2lLKWuChkeeK6gUu0FhcYhbDfiDLj17IuWXYhSGN+lh+9SZYITsRnRMWtBpOXcnMLI7F2mliFLX4mkZoFdawr//kWv6e9gg7ovQZ/XJHqF86gIMaD/TdRAloqZ7DK5kGKOPYGfabvDaCP6ywFMpgI3h3+4MdDu7jmwBEmfQEKskA06dyX4n4lQwwe2bpkx4J3JtNTd0ABy/mWo4wIj0ZxAAM63SldJs0zoYcIojawPLGtF7vrKkTf/Td87twL4KBWNjRdzcZlAZLLd/dyrlkMJ+GfVDImKbEkhWfqHe4g5AnqDATaRzUEEXwoNg6qkPfokeJg01Cj9fN6Xdg7xugdSst65a0Ayc/kP5SrrJtBml0EqyTBxBnQOLVtSJQSvytZdUV/g4MIcXKwv9riwN0LD5QraCMgx96VbENO8KnNtGFD0ZfDQHjQpVS31ed1R9NQz57S3uMB40g==
  template:
    metadata:
      name: threatmapper-console-key
      namespace: security

