apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    chart: n8n
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.16.28
    helm:
      releaseName: n8n
      valuesObject:
        existingEncryptionKeySecret: n8n-encryption-key-secret
        db:
          type: postgresdb
        externalPostgresql:
          host: n8n-postgresql
          port: 5432
          username: n8n
          database: n8n
          existingSecret: n8n-postgresql-secret
        externalRedis:
          host: n8n-redis-master
          port: 6379
          existingSecret: n8n-redis-secret
        main:
          count: 1
        worker:
          mode: queue
          count: 2
        webhook:
          mode: queue
          count: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
