apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    chart: n8n
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.16.28
    helm:
      releaseName: n8n
      valuesObject:
        existingEncryptionKeySecret: n8n-encryption-key-secret
        db:
          type: postgresdb
        main:
          count: 1
        worker:
          mode: queue
          count: 2
        webhook:
          mode: queue
          count: 1
        redis:
          enabled: true
        postgresql:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
