apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-logs-single
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.11.5
    helm:
      valuesObject:
        fullnameOverride: "victorialogs"
        server:
          retentionPeriod: 1y
          nodeSelector:
            node_pool: observability-resources-large
          persistentVolume:
            enabled: true
            size: 500Gi
          resources:
            requests:
              memory: "6Gi"
              cpu: "1500m"
        dashboards:
          enabled: true
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
          grafanaOperator:
            enabled: true
            spec:
              instanceSelector:
                matchLabels:
                  dashboards: "grafana"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
