# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vmuser-readonly
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
#     targetRevision: HEAD
#     path: argocd/kustomize/vmuser-readonly
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: observability
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true
