---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-aws-credentials
  namespace: security
spec:
  encryptedData:
    region: AgCeP3MduTHOjCKu0ACPj8p8j40rDqvhlsFfYrzqZdfbyITksoKEUhqVdUA+Z1NOKQbjMHTL8CgSRalJCDVnttXat6Czk886Ha3HLkPcTTVOesjT6ddpLQenG7MzKoTjo/WumG4Ly6Ds6dXWpUms8T6PyRY7WjNl9jRhWdJpAplwFGO4ukUU9mSbcVJxkt1avQmjYC9dhPTRo7rNNWtbPzboM179+PHwy0MEk8YnZlWhcV4KYvOXCN4E6WQXUF5TZ95ayJzSaAWrjtM/tRlbzNpkLFbsvyp85Tbr9GEL42z0p5Yksjp3IJg6uxMkQ9jBjWHtMm6UwdSG6JxnIaQRje7T82plynONn1jn8J04PVN/8Qdv3iU63bsFuBs9nHLgC/YYydxwhJFj5pnLTrVzo0hQgfV45LvcsCmQvAabzOEb/nwjn+0XeYEBQSHwFrGJLzVquZuG1DE1RFnlNK2iDmGJ1N90r/qSvnHt1ld5/kX84ro10X6E5qq22Vs4yvdvUz/F/KCJcjX8KPyRlbeV8o51f2BADUtFm8OehKWVZNTtOeB55koL4CYcNFQ8HNrAzDqv+fgZX6ft+1Ev2bLqRR3ulgeZwP7O69lDsnNHsaJNwGGrJGvvieXtAtn933u3o+8Z6h2j4gXCoys53zKcAIXv2Yw1gWm2RhnBEq/kP9pc+TqxkVU2lGY7psVlilIReTXNoL+q+dMyOS2X
    role-arn: AgC6UeyZj+HB/6q8WSB/L3MikTMB1IB/T2/eo3+0enf1cFIQaMiAdGIH5SquelpZd9E5lk5cv/yBvK0/h9jSbq7ttCWVOT0LgctCEDJcnh/ZRV2knxv3ithN79d8vE0FKd9b8kaHT0eLAAimMgCpTqoUQC/6pJE/AlauQNs7zV/tZUjIpA1CizYtCzDpSgIL1wymJLTJ1qirAGuh/mWyZ3Cgq6PLL216DNOT/Gjcd86NYEdjtNptA9MfaEfKB1QuKYWnRIhpcOtB/T3x2XhpUtGcJnDWZudMk2AG25KFcVp/jWC6VyuUOzUAXgl06o3yk8SsDhioCArEIP/3GMgiIc/NBClECajUsln+dhOwlaxU6T2+Jols6Nv8MX25eQRqxnRWdkqJNxbLwclLBCG5AuQuIPSTEaAkCfuOwRdypR5FhGa8aIt8dJuBx2yDvA7WJszwr7ofqE9GQhAwOjTC+M0mEVmZMMNdxEOJ0lLKzVP1l+sWZrsJhf27SNE/eUXfu6WBYP7qjXf5M/fjC76pSpJSV4jCMJBA6VHnpj0OC6njTAjK5sghXD4wPlv1GTOTnJKaKWTU8QvO1gZrob6NpRyCWS2lWVmkEw9wgZm+qJUZKeORe78Urg4WaMIhBtf6p/Y2Ix6/1l3wqHuI2/LFgz5MuokoFkOooycByaFVJqaWNfXzWsHB42QhIqanqcNYs0ozt3J4qXNeZ1xJ
  template:
    metadata:
      name: prowler-aws-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: AgAzZT4u6KOmB4vAhVE46Bs/ucW8qcOX34zzkZ4ZIv5foPo1KjgRMgAokP/Nt53lWrYiWVkS8U1E4pNmiqJGH6pmPAIgzN/9CIjga1qQdUWZmG8/5vNsv3iaiW75NDBHnXnhL6ZGj436zsceaoc6GGQpl/ikoIe5QrBm5rfKgxzFGH4Dej6akJuo8A2MXZFpzPkbFMf7xk5Hv7vicdoueEuwhTDQHVsYXlBv7KbD7TYW7bqc8OliV6te1LOIL7CWwzDw6vv5WG9aESiL6m814NaTgM7zCZMAYrc78/26LOs3x+dpKhKJNY+EIvab0DgZEyhIbnbgkBqWWtXY16S9hE5C/nJ+VPW1SAsg3D7zTuaEfDg6DPwMBArN1atdH49aws+70e3qaS6Yp63mSfxCaNSaVMZn2Vx8pFDXpJqzpyrYrs86VcgJgKpHATcdsckVXhwujQgvmyHHzEz72JcGLS7K8j7WjB1AiudWDKLKINPdvAYZ6KjGjTIgaGdBVsf7PwgbNmjbRmcQrK/gXNyzig/XOvOor38nExd6cK3qXtB5lTbx3dEINM0fEiJkEdOLTIeKwxRVMPJiHagF9F9eTjr7LM7fqORD6wJ9C2EOkQVBoPOTHh6wf8eBufsP3wVO9DK3tOcNPlxKXVaYbpdp1cKn0rMR9S7AEIy9bQsNoKNqeHc6KhcMaWyXzNwmelJqNpY8KcDhKILCzigg
  template:
    metadata:
      name: prowler-gcs-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBT8PUtqfLDb7A5IFNUPIVuQz2XUrJSo56vCulXV/BHcOIh8wMmV0XqbPpx4OSVKZIqYR+Yhl9s4zAM9SzWWRblZmdDWSHFPIq61zO1Q5hPFrFBTp9yhjZHnsjjmbKb7e0Gum3PVql/TjhdJtfVAjSqr9tFS+QeyBCQ+jppvcelgVg7T29xxXmoa7ATQJceLr+7iaKFyJpzKtvujRKpcadOnkVs0vwMff+zOzdEhbFMO9dAQ46RTGsyQnoq8H1DCMelmLDyrxfKRTc3xhYuE5oJPPAhyS5mHRJGkyctUknEKMGt0mLt0oE1unSmV6ts2OeAPO4Nk4hsNt1YgFPNu7feasHJ0AInPEHFKqMsOHD9b1mMofsZiwKWpyvzvjwlJ65QjtjWvuDpVPvhZfMtjljBUMvIqzB0hPBh1VXKcrJkAVtRoVk2yujcyIZ01EoY3Z69dAmUplXmJRaS9sAk4MBuXcLLzXl5Wi8FGph+/SNMY2YHwVNiAy5uObCm7e3xWwnQpmBXlBj11IP5NwEIBEUTZrM57xqAnqJYe2ypo4yrDH2TIl+kGWtG8oXPIz2EX8lsSpdqUSgdRbioR1BAs78DUG84r77WiE2qvTE/Xmkh7LP5PiSov2UEwA6WDhcueEEgEoS5T3jSmfWquy7/UO1ZGqOW6Ez0qiCKYsBNq9v8sqNe5oOqwrxTiV/JqKeC2tlZMT+Eb7krshIH
  template:
    metadata:
      name: prowler-infra
      namespace: security
