apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: prowler-config
    behavior: create
    literals:
      - cloud-provider=gcp
      - cluster-name=ctrl-plane-dev
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: wi-patch.yaml
