---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAVwDIbdOZo+zH9hnMxAL3+uJOUoF5fPKCnyl5cX1Mkd06+oiwjRGb1Q41dtjf3vPFO81vVYedhWFfQmjjqqgVP9zcJoIH/fPpszKJ8VN/3H4elskY1rz2YzZoGG9nnYrZf6g6WwY9fByqgf9oJkF44rM85RRGQZNJp90+WBBwfRErA8s8Ht7l5KJavH7q8pfo9/XbGJjy0x7Pm1a6xTNK2GnDHEx0IVybmLfCLl+g4d9Dfg+S2FECSBJloyKrf3He55kST9bDZW9daj5rBYsxuHm8OqLP1QoBRJ/BpAb7voYBGiWZn8EBa9aVDj7unvOspfQzJ12r8QHR4jiM2mNf71Bf1dOy8Bpq+3HmajhUBE6rX1+67KyJbLDvfCLBlh4WtOKcP0J0CiCh8oI4lSczMRgjbgMhLNskDMZRGhYO5fxuxtcq7+3mVDXTsWOaSt7dsB6MJ8q56ISewim4+Ed8tpOAGIq8C8hu3/c9pp0L0WoPUwAgSnu6BeeUaNrCIMIikvWR3VR3Dx9Ub6kDRmSfifwUaY0dt+l0eXTmQ7VIdN29PpCcGNpwF07J6lRt1XEkjM4QQRJDdziMHdn1tfEqfd5/7Fa6fUcjZb5Nz+H6bZwMvwZD90njq/b+lhlqA27ejYhXw6qZhq+d5fNIcPAEvSXeR951zh9/gOmQe0CrADY3ZAsL0ySOcuSoPyN/TNX0Tw9dHzBLp7SJTVPOpYCuCDbLfz60uzt+j0Kiwuw==
  template:
    metadata:
      name: prowler-infra
      namespace: security
