---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgCQc65ttAiwW7odtl+DgGA9ZSo1echy24YRgdoK4TALWS6NNq7RLs2CYjLOhNIgMXxx25dnqbwRLBKhq89EyhfhKsKUrMJUe3bFjrqvs9rpNF4sF+EIOPVZ2ru4zKutcm62h/fFbv0ofTWICmRKbOVyv3eIlNY3wY1KeIRO1ojBccoJcdAWw8ESGzQc4b+Xc+vuMuEIaXpA3ZmuNinK2/Dg1L+IX2IyKtp8ftyqSgiPklKYSBNaxEZCyTjrBsf98kbOxp2dqMZ3KXQiTL+F+hNe8t+9MPDi/XKtDmFCjbuMVufT3Gyu60zMYAW34c1SPx0PJhkSVmb6kpo4VT/2aUiavciVutAEIdzRKby33DI3w0yGQrV8uom4Jcbshs5pvD9FahRx7ifA6mY6aIFpRoRYeJUk/ZmQYveceubCqy9riysE5RZ0CG/AIHLY+uhkNJk3IbPYb6hEYUXSnEnoah8eSs1vzbZW8zVQTzfpBuirugEOlX1XGUg6gRA/quxZQsew3YFunlbxT4txKBb7TSrID+ETjKloRWwsEl+vQNRARtRdxd1MkruXsT1dqcTndFknY7D1RwQyz39WSQcfCU2cHnwfxUmot1LpAqXoRFlM4eUjyw77ag0jvuqUYsxM7apnUhA4zg5zsFKZA0I/y7eBxidYjUTx0q3ZM0VK2L/B3qq7bmcO2aiz/jCkl7qDeQhnv4ZY4w/NnAwj7iaeNgsVOO4QbEIbZBam5wswqA==
  template:
    metadata:
      name: trufflehog-infra
      namespace: security
