# TODO: Seal this secret before deployment.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: PLACEHOLDER_RUN_SEAL_ENV_SH
  template:
    metadata:
      name: grype-infra
      namespace: security
