apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-importer-worker
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "worker=us-central1-docker.pkg.dev/ctrl-plane-prod-b1b92df2/backend/db-importer-worker"
    argocd-image-updater.argoproj.io/worker.update-strategy: semver
    argocd-image-updater.argoproj.io/worker.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-secret
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
    targetRevision: main
    path: argocd/kustomize/db-importer-worker/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
