apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
    targetRevision: main
    path: argocd/kustomize/grafana/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: grafana.integreatly.org
      kind: Grafana
      jsonPointers:
        - /status
    - group: grafana.integreatly.org
      kind: GrafanaDatasource
      jsonPointers:
        - /status
