apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.3.7
    helm:
      releaseName: kyverno
      valuesObject:
        fullnameOverride: kyverno
        admissionController:
          replicas: 3
          nodeSelector:
            node_pool: security
          container:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
        backgroundController:
          replicas: 2
          nodeSelector:
            node_pool: security
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
        cleanupController:
          nodeSelector:
            node_pool: security
        reportsController:
          nodeSelector:
            node_pool: security
        config:
          webhooks:
            - namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: NotIn
                    values:
                      - kube-system
                      - kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
