apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
configMapGenerator:
  - name: falco-env
    behavior: create
    literals:
      - cluster-name=ctrl-plane-dev
      - plane=ctrl-plane
      - env=dev
generatorOptions:
  disableNameSuffixHash: true
