---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: threatmapper-sensor-key
  namespace: security
spec:
  encryptedData:
    api-key: AgDA4EN+qX3appyxFQz0qrLhTnTjjMxWEz2h+itmyBa1idqK9UzskSFtrRfsZmIGiWXQyenrh8iWc62OefoYnmLDILexlynm9h8soSUSilcyBCiPMCe/88qxBz/JgbJuY9+KMCL05TvQaTG9WvCw1tSgqfkXqc7eCvx+R0b0pkinit9fFfKfCAlyd1QHI4JuTo2fmPcqQMgC0LE6e1Dj6y+gajWNuC0rMy+z6nL2YLm1ZTyk6kgmTF8WHVfuMzQKRb1+v9v3m/NRnkiGjmZjXVR0A0wi8mtcRo1OHNVKHlItIXH57vWDdt1TgOcm5cv8e2WRufHnMlUI7k1zG/9SggnHgKmdEHLH1PtTBHteyzOqGzNJ24iLZANWuSUK0Oo6JXDA0DJE/K7aMzf28QHO19aqNNCykmawt+OKp4vIsz1Rbd14qRB79QcZrTYEI0EhHGPPpL/4wm+4/lkg9UDyv4bUSrHMJWbACQToQCJ9HzXFW0+/fmqblkgZRRvmx1B6YJ4wnD3iv0c6Kh+BOdWiGm3MKfGFi+PTaWhdsvBll7Zu+kuU67d6qxx3lKOudOjaY1YMz6vPzPLM+JgBQcmNIw0U4A8hmA64+xZjtM1IsfPaLfOA5O9+oYd/2KHBGZZrnB+wPnMo+K6U6jxIEWC4LUhbIf5KA/JgYgXPzfvL22isBecRlWBjzLgREV6L7cVOh7g3mPW/bKBqTJ3/8oxxCd96xPid4WJzb+JyAe1Gm77XgiliAsdnQPkPwZs=
    console-url: AgBLCN/aCoMuhwHMK3ZCK56QUvz0JCttAC4BuKOkZPi13/uMWr9uQxCXlxxnOhHz0jIqzb2f24RTdgShsACs1c+9CGD/pbkTBTF2QobHlNfuHk5QnvjQqzsLNWaRrqXrvEw32Wu7rvtnUMlsjPySmUzfxdZiqM5J/iGQYJrberZrWF7SX8gtW8sht6W0D4qmKxmfiKROqaRqM8AqotYD+o0LYJLO83aJWcAKgBy/BB7r3faDaO4HQhK7cqFhQ0h1OVQQc594W5I+AU0oOvkkykG/5slh+KGUMCrw2F/iDHHebQqZVgdGAtqrSNArfbsRAl894+/CJFHh/5DZ9vY3JXXmssctjKE+xQKdsYNtEp3FJYg8qD76qD5RM0NW0uiecLHjt/5VYUCkKLBqmoVU9VITOxKoyZHMMc7qsCaV3PhdALZvWLDUe9Lg+asADLtiDmktYhDM7UjWJ6iqHiyFmTEinAmAIOJ++fOrVGJV3VaiyBSyKhL8ZZCCfkh+0+77dmyaPOoJD7bYgZ6YE9H/bCW8XX15CVQk5kWfQUlCaBhkIyfZmA4wYJms5w4omoxOteClWNnQLQs3Laz8PBLelUqEOtI8ymt7IbbGhYTqIJt+gnr7jbE/R4SHkG69txOVnUgJ0+/H7pfipeLdBStIeoo/Jtq6YRdrsrClLaxfLPYlXgtv8AFm1cXk+JdAPXE/1DNPeTqcIbRpbXjlSQdKYKdpIxEbqmC/dbaWWPTKRPjx9IHmduNzzmfA3iIipeo8+Lt/
  template:
    metadata:
      name: threatmapper-sensor-key
      namespace: security

