---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: threatmapper-sensor-key
  namespace: security
spec:
  encryptedData:
    api-key: AgBbmpoXpQp6jxu7smUodcj+c5h1HzgkI+dWOVcYgqZ1Fh6YNS7jhlEnPMyI6t72sBGn1pM9nNrUoYRvbRzX3tvEnrrBAgt+/WIf5PTAObt0tumylus3c1FeUUjVnDk9jg9swEDcvm78WszL4Ako4bK5pXnHQOxqgpLYs3j7BzvaLnaHklOkyPktXqE/GnvbwtSmb4EeWI/TcY/IihU7ZXyH17FlCpFS2SDTVyQE78ee4wlQLZlrBcxsRz3THhuxoeFwiujpU/Wo1okfvLGnvuuHjgjxjxQZ+AmgCdquJCm3Dec9+ofTUjyG9hn3ACOAEGTmF98SBtowGVG+ADKV9dsh3GZzI1Czad7RFjqqgbTJQwlhWMHAxsc/J10kJN7k0r0caY6bR4zYuw9VG+huW6zolclONuC8MuH6GiT86qJj7SxVfHEz+G+OTflZfHRPCskhyRlqMA5xiWEhyUpdB7HgGIubVy5MGsi+Ab8+UISXvIT/kLsjb3m1KaYWfoLHIrrNYKj8N8jMWajika7erwaRnGuJUDvta0muRoZ7tLFiRtWpFxmVcLfB+CLtFXDPD7N/sosQSX8k5XJ8n1WYywWRMg6os8/MSRfRTxvNrwpKzTBd9Wqjf2IG+IiNr1Qrx+Oi4qiJCkhewX37IGFBfLh+3WSguobF+C2npYUWRqgykHegwLb0CeczzgnaaaWKQmuFsqWaDEmQemjpapXyoUDOZRF9pMMuHQ42a8LmeIZvT58mzp5JbXvoZE0=
    console-url: AgCzOEx6YlsJkbP8A4zD1jWWPYYXNz5c8m63JA3FQe4Ynygofa+f1ecwfs8U+wD+coVBV7MRE93Y3dPeV3mArEVsnuPxyu07q6tKTtAYaUpT3OJupr7OwX2rROjP0CnQcsGPnpYNdGhTnREE3kZnD6M2Up8ijr0kzQNglGhI3pF0QXmk4Spv0JJ3xwZ1GWesqjLVOdSc34uSuDaHqT3UcVciEAZxgJRfwzShewfXioKbRB35kgD6SQ9NTJ1/8WT8gmz+JJqil2Je58j+nPRnongoUNxWPjsE3l9G4DR2Re5G13NqqQNoPiyvC+CFyJU4BMbdTRq7qK3ctbaPGw9akMw+8BEi1f28UiyLQUdWDrHs7ZDPszUS8LV37YL25ObhZ26E7o3X8rIJt2xZp+SV1BKVnHohwx3Zz7GGMVvYpDaNDB8dozbKT1YFF1rEF7FXDKA0TflHHzbJzqCwE0XK+TxHkD9ELuyGgoxJawNPjtwqli5kZ2aBA9Mju1EDD2+cTVyfDVIjBAOeY4QZucXkVjuZVbj9938m5sTydO87DH/ciNchTI7VsUwYjBS4uHv69C3rHfWU0FikQ1IzI3EKfDqcY9yB1kYgOie3fW/17jBZxFl/BYkd51DwWRZ6ofZMsRoULdXV7Kv9ITp261Rvrb5XHW0jO9/9iIvgNM4noCpCtYlba67R2vw64hK0gMGI3/igC5qdMIuZ6pT32HZjOo7OXiNEsZM2ZUBaL0RkXwpAlGWgBcz0MZ3cNrvEL5kln6fz
  template:
    metadata:
      name: threatmapper-sensor-key
      namespace: security
