apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  - grafana-managed-certificate.yaml
  - grafana-vm-datasource.yaml
  - grafana-testdata-datasource.yaml
  - customer-grafana.yaml
  - customer-grafana-ingresses.yaml
