---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBP900Bg76WyEdyuwFpGwWx8+3IB9YQlmFsjTv7Fm9BfFXmXhTpFckukFBlVI9Gkz3QGEZy4Au3YDDBNbBsiqORo0QdN/jdXKUduOde8bBbt+2AXruEOk1Mz0xzPlJMmvAR3C8I796LaWgyTb+Q1mSj3X5HBYRpPaMUw7axm8lACzevKypV8QZwLKqwLPtANh02M1zmPcBnYKdzyg6hd2Ig1fuT4xVweiT/Zv8K0dvyEZImnILrj/ZrXb3nO1qNjsJdGZi6gc2YkBtsKycPEinS7OWFMY1TBMSd61ezw+O/Hy3rfPnzttNa1iPMmRUKSnRtSbxKh0/AhxcJhDWw9is4wmqse7imbLyd/ByXD3UmvcaXJNkW8rMqr1UD6dPNbRqb/lnKQxXKjMmpMkrYt8R3hOJ+L12fzuCslc/9EElFS75Ox5AFKwDG4ZoG7iyZF6b4aWClvaCth3Z9KuxjhqV8a3Yox6LFB3qIypK6p/ZrgHmdbdf/98TgoWv7fhO3PUsltTCf44jGTzRm5FHW0IXnl2EwwC5RkzCDpxzhQiIs+jjE+9AMnyQ6iQmPvkqVqaAORy0PBtAIbUYv7T3abe+bot3ELK96grghZZBv0m0HzaWs2smrqPUa0M14Z0JGQ5qhocyHBBIERfqRPkw9L7q7pmWBOiR5rHgeSyjLJI3EutHH4S4mK0gJUp0g9DII85nasiadowaiaBjIbOfhF10kslRP1wRlFgVOikR4nw==
  template:
    metadata:
      name: kube-bench-infra
      namespace: security
