apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser
  namespace: observability
spec:
  name: vmuser
  username: vmuser
  passwordRef:
    key: password
    name: vmuser
  headers:
    - name: 
  targetRefs:
    - crd:
        kind: VMSingle
        name: vm
        namespace: observability
      paths:
        - "/api/v1/write"
        - "/prometheus/api/v1/write"
        - "/api/v1/query"
        - "/api/v1/query_range"
        - "/vmui.*"
      query_args:
        - name: extra_label
          value: cluster_new=cluster
    - static:
        url: http://victorialogs-server.observability.svc.cluster.local:9428
      paths:
        - "/insert/loki/api/v1/push"