global:
  image:
    tag: "v2.13.3"
  logging:
    format: json
  domain: "argocd.observability.dev.internal.falkordb.cloud"
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    controller: gke
    tls: true
    gke:
      managedCertificate:
        create: true
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "argocd-ip"

cmp:
  repositories:
    falkordb-dbaas:
      url: https://github.com/FalkorDB/falkordb-dbaas

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: ctrl-plane-observability-stack
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: argocd/ctrl_plane/dev
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: app-plane-observability-stack
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: argocd/app_plane/dev
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}
