global:
  image:
    tag: "v2.13.3"
  logging:
    format: json
  domain: "argocd.observability.dev.internal.falkordb.cloud"
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    controller: gke
    tls: true
    gke:
      managedCertificate:
        create: true

cmp:
  repositories:
    falkordb-dbaas:
      url: https://github.com/FalkorDB/falkordb-dbaas

configs:
  secret:
    createSecret: false
  cm:
    url: https://argocd.observability.dev.internal.falkordb.cloud
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: $dex.google.clientId
          clientSecret: $dex.google.clientSecret
        type: oidc
        id: google
        name: Google

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: ctrl-plane-observability-stack
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: argocd/ctrl_plane/dev
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: app-plane-observability-stack
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: argocd/app_plane/dev
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}
