---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alert-silence-syncer-env
  namespace: observability
spec:
  encryptedData:
    ARGO_SILENCE_REPO_TARGET_REVISION: AgBlw5JW4hWxyRH88g7ZAeuWcb/w9tsW3QaQL0GWKWbF9kKD7F/+ClEk/3YVR9lJmjXZD9M5YBGx+cydRH4L/M1HFUiEapxGTYdU+wtUJ+NglKm0q/6h+lbhWOCziJX5/Hg3R2mP2Emq1wLANXTElBjFFSVWEKCQMkrqbDafjMQ4YKO3p4mmzYCsMDHYS/Jubr3wGjUjmMHdCqJ2dgX6cwvq4r9Fiz6Y8unwlKrHb6PBg0lKhLu63Tg8/oWOXFVHt66mFn1bJleS4Veh6ACEpyuA9AST1ZnPSM/uZtSW+F8mprUUqOZCfYeIUffFRNhhxVTRsR7IEVB160Lxd9nOlxb3JDqHK6mNu7TrJ2sSDQnQkZNzaa7mzzu3r5JMdCyBsPBwv5eXDK6BGZ23eq6WocJMjsKNcDKRq/SXPxE0SdrWD7rJVuopZf1GgHSgjXUXVWscjh4VRkryoyQjaaGefm5B4FvwInVS6LACVuIcVlUtWl1OM9Jk+epu1uvimXHa0uksyglj/vFmYCIe2036L25MbVjHP1DR4j1Uwl3YcfywlGz+Fqz/4emY0StaE4Ypl634NewpW5NtjaP80BhlyS+rEkAR55+L0dnvpI+X9n3RHNFm6xQXGQLxqBaQSqySWYMqIgzUfABaU2GO+Iy+OLGyU5CwPVF8vEldDI10eO+QH0WjyPgd7af/jyQOLMjMi2tjXB9c
    SERVICE_NAME: AgBf4Iu6BqApKdX6f1SHZFc2u6bVgtX56xfWgbbQh6d89hFTF8dd1HlKxdWcqo+UWoGTMySzbgJ2xMSM6351PH1f2FOtebE7lPVsoYssVMYx/bMeqoTSsxkyQnzgrbL4VWuOWFVbrqbCdd1ccua8UJNh8dNM5Kf79/DKqcohXv+XppZXsOV4+hKq3o+9AztpMJeZJBVAaEgKqQuzNntbgPwzNFnGaBN3CAZvsjuNU5r0udMnFGOdMbodV905fSUv13UL7jcs6eg4rs1vozSWNU6inMn5uCYfEIIyeQTKkC8mR/gliDGjteZfdsicw38ISH/KNrSznEzH4MJJjIcwjbKpkz/+D3IgaQextu5h7SpLIT2qS2w/ePBuDG7rtYUFots5+7tJ+e4eO63EAnnibXgsI6jDruI1+nllYehkIW+l1Mvp80ObmiocqZKM+PunH0bpS9SohdROgg2i86nfS8nIeTYP7286Sdhzk1HR/IW37ovGiZZwpcBsADeJCxjb5Q6cYTD1izPm1tHnL3hikFNtflz8v5tw90uvxTEmLxPXj0jITv2jikW8/Va7iCJArWsO/6lVWAI6Q/SFcqRZ4hd0ME0fgBhKN7OD7nPaWC1qSwq3wsp30xEqNg/mKpq1VFngPEk0t7CbSJAiUwBslGjQMQhXLvq1DGFzS1+NOKOhg+btfcTDQ3XUvIAY7OUmpuu7IpPjn/8ELRS/TBhxOoE+/KlGrg==
  template:
    metadata:
      name: alert-silence-syncer-env
      namespace: observability
    type: Opaque
