# TODO: Seal this secret for prod
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: trufflehog-infra
      namespace: security
