---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: threatmapper-console-key
  namespace: security
spec:
  encryptedData:
    DEEPFENCE_KEY: AgCQhdaExrn0vTqM868REwdGICoPSRFybZmTNh+bcuVo6n3JZEBCCIqez57nHRfLg6gpIKe0igwSMShZoLZX7u00xk67gitENcw+IOT8Z209fqd5MVepbuplxFzXwM4tFJ3ySWHz26Y2r7oVkGRdEj6u1FbaxZM6lvnXryJEhNcX3N4UsD1BkdeEF29ver8O087N3LuwnrHJ/7fqsU8y36DS1at8Ntze90if3qDCVr+lpoBP9osLS1v2TGEH8P+6ysyUGzSaxR3/nwWEjR7TwELUFjmwo7ZX/aUFDnPJ5VgGKheNnZOQXPc2M+gste8lOMLD/lE3WcifZYb4kovV4AE2X6xRL6L41K9CL4vs2XZTG7bR45cYUWdfpiFBgsNO8i3Zvh/qOg0+a/HKTeXNBuibnL3IxKwFZ4IDaRFujuj+EH9gqX2P1KSIfcNM4ncpfo0ElSUhIRlJe+u1nzKSc2oCi875D5TsXtLhBfa9vo3PLO9XmkLIONo90V3PAKNm3ve7Fxkb5mGR/WkgSD0V3iCkeEFi5TYAe84gsJWZBFWADSOP9N8OjpDwLz8dciGUuWJWKW/uRxSHqPHuksrD+KT3P00Nahwy36MlxJr8BQrvteT+94m1IbMnec36hw0NFjMsXyDh/BMgjos4G7CfjhsGofAeBdafXk63yUUBMtI/rNzIrfG7dh1QEvwc0L4hz7zqn/aBGfAw5RcBvzFh4TbEx/xYr9fTdc+g9cI8HR2YkOJilOrKEOqspNc=
  template:
    metadata:
      name: threatmapper-console-key
      namespace: security
