---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: threatmapper-console-key
  namespace: security
spec:
  encryptedData:
    DEEPFENCE_KEY: AgC20kRpvbJ3lEKGQ7at49ovINTzJekT9ba5a6WVFVUrmCvKvb/ebXMpXhCzN2F3IC/bi48twSpsFKh2icX5cvTd7MNT8NrYFZVPq6k1cLsrPwGN5lozEZYsVI5ADcIo2rYV5ju8amsI7wPlxuty7UvTFhpVGz/VXJ0xyR+MYusaml3xbCeuzH2m6WVWWCVifWOiiIjhc7urKec7/B15aC7xZGxoxq5zopWAB4NWM/xAj8bl9t+Y6dcnrAjna2xUMIsNTPogopWRYx6lO+iJqZWAHNQQhP+/Z+9jhyS3pcWTF3Y7/m5RI538oqwDSzbr7IOHlS/nvf+y2wDJ8WD1CA7w/p0JkK9chTSN4E0YS0MBj1qdrLI7MnyAS92Zhg18Lq9BQGcQ0rsGr1IKDvhYTj+WfijQ0Oonc9dV8moY6B1s3lvn+y4YMSEhVsb/W4HgBbl0PF4idrDAJDo96KKORp8JJN+ASWxjAwj/LASZh5+tS8TyRHbHUxNeCurZIqsFZa7upZ/+zR2C0fGQZY4CJNWGc7QH7ZJ1F+iuaEXgEHv9HCcLP3fYRcp4FraB28Pvp9yW5mTRZjOKeERCOxoXSh4fWxAnf1kVP4MrmjWwWtAnuDQPU+c3GA9b8G2CkIt5JArpQU40PnXtLjoiZ9wEnxccKuB/rGprfrcVayGpD6wdary22ODHT/V7ADu8AgTak+qRmQZDsN7eVMQl+I+uIDj4oZW2jsZzLU3Okeiipdu6JhFRwJ6jZKJv0tM=
  template:
    metadata:
      name: threatmapper-console-key
      namespace: security

