---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgB8pV5WBXCU8TVcBp4BFY5vs8skkCjcfgbZu0QQJ550WXIxYjmATXjflLlXWtZbepT8KWoglzZZdhydi7HJ8hNUku9ROiihij/pyzUc2N4kKtYaAbkKzc8ktshtMDyT3nsZWh45h5ZflXuMDy6NNo9sRjkxbPYNaCkChH63Wvl3jjq5PPPaFY+0CveJruT81j7lLozB2czVrPJB8l4FP9lnZvksBBps4GtA2kn6q6PJ7glPSdmOhK8oGUUFXBucslaIUxXLKiDZUtKpM+NJGVW3xL4lmUQh6db70MhQ36bWN0rB8OnD7AexXGRJnRL1eRfu1Ntac4Xco7LV8quTgYZBuAP05ctpL/QZ0/U+MuUWT+ualdYfSZgbRsWOwcScN9rdortwyc+xm8L0j0/Q4fOlv8Nm7IO0hcztAIkCNiQoDy6nS8LcLyxZJwYutEqIB1o8dQBHEXzp0aI37vZ4YiXAZPh4Mba3vsyY4grPTZuQiD9Zf2XzJQsKr5yPVvmKYsLzXPeFTHwgT9A5OHEVxyLy7LEFLTVC1jKVG4CksSgB2KsmUqGhJfxbSE270WVPsgp2fOX9PROziAQkw14cj6v1atFVcq1oftcg4qplsE19F7yZNK8efRqVzuz3tL+w55JERhoneVyS5zd8nCsFa/lXKUJRZNqByFaq59lUfY/uIn3s0m466qKqg+OMWlt5JzntcygTzNEeGVJLuhkUPXGe7AWIb31RBBHP/1WMzA==
  template:
    metadata:
      name: grype-infra
      namespace: security
