# Patch ServiceAccount with GCP Workload Identity annotation.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grype
  namespace: security
  annotations:
    iam.gke.io/gcp-service-account: prowler-uploader@ctrl-plane-dev-f7a2434f.iam.gserviceaccount.com
