apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
configMapGenerator:
  - name: prowler-config
    behavior: create
    literals:
      - evidence-bucket=falkordb-evidence-locker-prod
      - cloud-provider=aws
      - cluster-name=app-plane-aws-prod
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - aws-credentials-patch.yaml
