---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-aws-credentials
  namespace: security
spec:
  encryptedData:
    region: AgAIzHXImcbBF5MVT05LWbL0TrJxfve1u5ONg36wiB62eoajgr3Kv8kHw6yDTBWtvbAfq0I4yS714OcZxrXdsbgAhnJOcY4ShofUgCTVh/1SfjQD0uGYRBNpDxsxB8hbJmGv8ZpSamJ66jrNgUbLWm7m0+ohLoEE7BsiXUkgrdajePNTFbHcKgAj3RII2YiYHcC387ONur6qOd7A/g2MbBXqzTWDIWeg/ITgZxukvD/Y9G3v4GZefhIufwo/+Sk99YbSz88yVDvGj8mZGbOo/tveDGNH3rJ6ntjGKpFQQstzH2RSsQ6ZAKIL3Ntj1hc5QrR7USLmEIQ2ne/H4k2Kap/sAiGMsFBkiDCq1xRJXLNX+aaPwOOvbk1jVpPjMAv06w9W79Bp7r6Z4blfADxVI+mt0FBykbsmn4OlT4FtR9sVkJUhfXPOprtkwD+TVpNrTNfASeCp90wdruId0bBbO5zgXxf45dpM72XeLEUNcy3roYoPPr5QvesZCV45Eou/HbdavEQUMZI/Klf5C22FH9H4va0zEkpZa7tYMw9jj1dik8ijHl33Akt091iZQtwzkDUAgxdiqtlnxllsDhDWtpvV98R0ayb7r163Lj/8/j5WbnGRKrQj7jHk4G7ivK5B6nAOZojBBM3opjPgEkPlZ1ex+c4iaViGbD73SicJkdKmj47c4oVGa41UL/UhOUuyyR586/JZIAE1/lNJ
    role-arn: AgA2pFlbVFHgyG+F1CjA5/qM0DHG/26chsVod2YIuEgJU7hv7G+zTrKc3ZYb0qRbqd8wKUZGNt9kVtPB+Ht6H08qxDeIXqr8HI3QyZ0WLLhetK+XAbxSFWVDTmbpkdr9at6e8qP5ypLF2h0o0n7BV0oC5iLM+dcSTjtYTymVVsTADTgoHpxpc+hwrjmo8QpQ1x0PO6RxB/N/0FX4lDdv4kC7I6SBOsP/8vwrrBIoLd8KPr5tcUSuxi3glEXizad2S+jYTWKNKPmsIM85eDssYc45oZrw5ZbDrlZl7klYy77Pym+VzQ+0cRN/8zClu1IwuUBfnapgtifbphO05/UqeYHKpxB3h5KHj7xR1ODWBBLQAfsZQLx4zkO7gK5Myd6dAr21xSiMXJN8/k6oO4DHSc68r8nMYqeH5JToKZ8PdcBfyvRAxG6ZdnfH7hVwUpXUGxauu8ldhJaPOFAqu/ka4MbHmpK5Qb9jUPr7+ctB0sZEgCC8sdQPy1rwq0jBbBqwiXa9p9hnQfQPGbTq8wVXCtHhidETMhoY3JFbCWXlB9j/WgpimJvslsRs6KsmsUwKhBcUyNXPn0YsBE3GJCTGWD7OybJtcH/Mh7jjkvFqKjdclen0RzqtuvkhcU5b3gC7qSfz5qZvPiAS3wp2zdSj+fzxMHE4slvN2JTlbmNSkiPaWWIQkiaoO3BGuqXpLvHfXgzhFKXRAPgXHbbt
  template:
    metadata:
      name: prowler-aws-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: AgA3VX7oLLkeaE4kK9N9KxOoU7Kz76VvdUSVVUz7ivTgNu2/EQKGVC7KwDs3rXqiuUrzSQ+iCLhNhyye40eeJJKK2/4h40/E0AxPJF8+/jimHTzyaKfBwhpouBRpwhYHqEMycZDbnvqd3uEYZkj5+fjuio8zoRNZeCKfRZgJv2/2f7rAqWXmOaAF+tlInBnic2YcgwhBbwKt4YlziaSvXswMngNKGi09jbqH7DvzDxiDF30v8aN3KgzKkSBSuvX8gYCcKR5SsBMvWUrdB9pLJ8d7Xv3twfmsR9s/dWhaHKXCaJhXOdnXzy1enblKDkQW+L/tebeHKKlfvgYhMFC6sP423BUBUG/ZSXZvZUm6yFXghgIo1gNzb3UjwlREbN4A3CcOGWuR7rwfVmT+8Md+Z5UCBHfovIgkeYVRiEZyMnMzFXItyh+LRAbmKgMWHDrq3OT4LpEseBswA+toH/1Wh5dlDmtDUR8bSxQdawJ7D74NNX2SfDlik5XDX1fg69G2ASaFEsh3PQaXvlhsWtH66n9oRQ5qd57JfBhct8tHHvc0HWbY2UHgTNeV/aAwjPQSDBwZ1gLBr7iyNL39zHqbIsGq5elmkuiKJd1GJvzXp07ZkT4lUoRb3QQHK67wZBlmETM1nb1lNeHreOYdC8k178ZhMi2+/g9EifCUOrR3paModsHZnoNgFODoYHF4c3eRyJMlL8vAekcToF1G
  template:
    metadata:
      name: prowler-gcs-credentials
      namespace: security
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBfv4D+MbPTC0B5C442bugJn7JLbZPU1q4EQ7DGCr9QvWLYtva1skamlkYL2eGBlT6Dlmg1SARj+hbwqgnTAOCWzq7I4e9LvrDV6NTX6OU29qzOL10AVetSU+UhO2z9wqjClRfV1tav1dtIVHJzyklDJBBz/Frja9Xj7YKhv4OCRn71mPPNg+wWDhRztYXq7p9Dgy9dBpfzua4hHxR10PavgbH/VQIs2y+FSBHRw1MUf0mwd1COc5UN0Q/yBHVCe69zmPzkzdi798EzgiFsrUj+rrSM1QF+dVTyNynWb27QheHLezFi3eABDf0+sVdVlVuQBIm2UAWzOxC1KfumlCOtHkPUk8pUWkEdJEHI+eufp2ctp0R4XwF+mtn5rTCgWIn/82KRm59qOMbU6WUHrP34dz41ckaKrfZMUNkv+oPFIIHDmHOVVWkLx+qf6e8696p4krjVVMB/7BexNCjXtq1G498n2do8yqDJr73ltEZso7nIj3VxaBk2yQK2eAtY1NR3WBXVTynTmfa7ENoeH2Q41QpXucpaLltL5p4oZBRrChWhL3v0Oh4xhT4o4vNT4aQ4+lgEkNvVgbEE6gffuS0Si21tVLCcepSGoAfZYSX6OA3aqwTGuyxRhnp7xSxtRuMCsDctVn/67jCipUD/bSq9t9dRCd9sd6sU28VZL5YcC+Y6LjmX2VFM2bn/5a912Hks04rzxkucj1Q2
  template:
    metadata:
      name: prowler-infra
      namespace: security
