apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser
  namespace: observability
spec:
  name: vmuser
  username: vmuser
  generatePassword: true
  targetRefs:
    - crd:
        kind: VMSingle
        name: vmsingle-vm
        namespace: observability
      paths: ["/.*"]
