apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
configMapGenerator:
  - name: compliance-report-config
    behavior: create
    literals:
      - evidence-bucket=falkordb-security-evidence-dev
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: ServiceAccount
      name: compliance-report
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: compliance-report@ctrl-plane-dev-f7a2434f.iam.gserviceaccount.com
