---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-git-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgC8LQA3yYW3nLiCZF/5S6MVOuL/t1zli3IJ+i1MA6U4NAqFA+Me0Yaf6gelIbqBL/fnG0AcdLhBwYM3uLiE9RPRpjy5512fvMeQhKf2/R9jxzjs/V5S6xlD8giu/YHgB17IxywoVZeJi5fsENf1tP4ZDMzOprO6h6l/bhLnZOPf4n4/iq0fvbjezMKwaND4ztcEFvU5tHXF9HfEcGkcTP0NzqNSMwKTVZvUbvW2j6aLLz8pjk1aiyrnZGZ4FGlkaVMYngs+LakpkA1E9AChtgxznG+zF18n/NQ3vVMmkbWf5esnng/gTutQR2vOBH+iOOmXfDyFXWL0ZdQSqJ0HgAdgjat/dQyul+ns22TbuUUpZ7+NbRD5gQ+PTJkoGIwo1yS+PvBmGfRoaVfEWQvKh5gYC79nE3wvVeEkKiT9ICNMYnTmQZ1Y97TU5mCPWMQSeCZzvX+JeCH7/m2sZTQJezhzLnW2OjwwksnjnH6zh04dLcT9+I63iV7tHpshnrHg/6pl3TwPobR7sR+vwQZXrGOH5ACh8f1GFZC6yn+Gfx4XgrEehOmUm541tV+F1WGijkazOoX3rfwtP2YQL8o5V9WNHh1RXCDEfeIWvcWOIK6xDAIJcvirDbBb+tnkUPgU6ogsAo7sO8wSZPDmpGj/lvb1wwZtiJ8wc2XyPJ+VEU9NSkY5hP8GOVzq4lm6+7y8jT11P7AYCWTAaWkMPv+SVc/lubT+mSIRFGd8e9pT9dP9vFjuX+W9X8IIxNoXckRFgf5s5raFnDA9XQJ8LwG2DHPJweT4C9Rt27ndTzBEf0c58WuPV0GHBcRTUs3+Eo4=
    username: AgCDMqEZ/JrUJJDVKeeXugjMSxgBS+nAFRo0NcZnPL0H4qSaf0HqFLs0M7dqAX6rZJlWdnNjUo/w5E1JnGyIlRB3+HUSKYD2gYgQBxLiUs/OlQLfagfWwXSLZmf3waZ0XN2w9EDRGgi+zZz2ddWBQOaH7lbQBg/Rqxd8u940e/akQoOyiN1OWbTQWmBwIp0mxugmbXWTbJFvGjQebyHIM6Mbu2k0ineeDHodK95Xs/1/UdEBTFJBB3meplrIdq8Tuia85jNbsUKIKwTiPXnZYH68fEPpEdXQcUCLj/YSYDyNIRlsanr8qbVv6p8o2CgQKWiW0Stbb0XbEiTWs86qwelFn9KfvcbxsTMRj2fEl49U/KharwKE44O2NFOLBSZ/alHSE1pRmR0OJycuY04ozju+/RdmXP21JsMyDRbNszF4MlWfwUEe861XIM88zmkGiO2mDyDZQnRrNMVeqwjYPahTTMcpTXqVfVvnAwiOa8LIBOG6ohPatzXNVbmSLK6KTEgrPMe2jis0eqxUFAchlF0Vi0xx4imuUjObN3DOr9d4ZO+gqpi/U6HszHv77b/jxBANjTIQv3SPIujRCZK6clatnHHD+93PbC9MYGlPyFhQOmp5tDM1nhPsmH/mWZkH8Y7b2Iglm9pJx7jLhyoOaaU6fiW/BrLY7RoYIrql7P1dMv1suff6wPu9TUJDBd7Xt5kRZfCvrIReoeBkCpI=
  template:
    metadata:
      name: argocd-image-updater-git-secret
      namespace: argocd

