apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fluentbit
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-fluentbit'
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: argocd/kustomize/fluentbit
        kustomize: {}
      destination:
        server: "{{.server}}"
        namespace: fluent-bit
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
