apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ldap-auth
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-ldap-auth'
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: dev
        path: argocd/kustomize/ldap-auth/dev
        kustomize:
          patches:
            - target:
                kind: ServiceMonitor
              patch: |-
                - op: remove
                  path: /metadata
            - target:
                kind: ConfigMap
                name: ldap-auth-config
              patch: |-
                - op: replace
                  path: /data/LDAP_BASE_DN
                  value: "dc=falkordb,dc=cloud"
                - op: add
                  path: /data/LDAP_SEARCH_BIND_ORG
                  value: "admin"
      destination:
        server: "{{.server}}"
        namespace: ldap-auth
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
