apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: robusta
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-robusta'
    spec:
      project: default
      source:
        chart: robusta
        repoURL: https://robusta-charts.github.io/robusta
        targetRevision: 0.25.0
        helm:
          releaseName: robusta
          valuesObject:
            clusterName: "{{ .name }}"
            globalConfig:
              signing_key: {{ "'{{ env.signing_key }}'" }}
              account_id: {{ "'{{ env.account_id }}'" }}
              prometheus_url: http://vmsingle-vm-victoria-metrics-k8s-stack.observability.svc.cluster.local:8429
              alertmanager_url: http://vmalertmanager-vm-victoria-metrics-k8s-stack.observability.svc.cluster.local:9093
              grafana_url: http://grafana-services.observability.svc.cluster.local:3000
            sinksConfig:
              - robusta_sink:
                  name: robusta_ui_sink
                  token: {{ "'{{ env.robusta_ui_token }}'" }}
              - pagerduty_sink:
                  name: main_pagerduty_sink
                  api_key: {{ "'{{ env.pagerduty }}'" }}
            enablePrometheusStack: false
            enablePlatformPlaybooks: true
            runner:
              nodeSelector:
                node_pool: observability
              sendAdditionalTelemetry: true
              additionalEnvVars:
                - name: signing_key
                  valueFrom:
                    secretKeyRef:
                      name: robusta-secrets
                      key: signing_key
                - name: account_id
                  valueFrom:
                    secretKeyRef:
                      name: robusta-secrets
                      key: account_id
                - name: robusta_ui_token
                  valueFrom:
                    secretKeyRef:
                      name: robusta-secrets
                      key: robusta_ui_token
                - name: pagerduty
                  valueFrom:
                    secretKeyRef:
                      name: pagerduty-service-key
                      key: api-key
            enableHolmesGPT: true
            enabledManagedConfiguration: true
            kubewatch:
              nodeSelector:
                node_pool: observability
            holmes:
              nodeSelector:
                node_pool: observability
              toolsets:
                prometheus/metrics:
                  enabled: true
                  config:
                    prometheus_url: http://vmsingle-vm-victoria-metrics-k8s-stack.observability.svc.cluster.local:8429
              additionalEnvVars:
                - name: ROBUSTA_AI
                  value: "true"
                - name: signing_key
                  valueFrom:
                    secretKeyRef:
                      name: robusta-secrets
                      key: signing_key
                - name: account_id
                  valueFrom:
                    secretKeyRef:
                      name: robusta-secrets
                      key: account_id
      destination:
        server: "{{.server}}"
        namespace: observability
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
