apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: silence-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-silence-op'
    spec:
      project: default
      source:
        chart: silence-operator
        repoURL: giantswarm.github.io/control-plane-catalog
        targetRevision: v0.18.0
        helm:
          valuesObject:
            fullnameOverride: silence-operator
            nodeSelector:
              node_pool: observability
      destination:
        server: "{{.server}}"
        namespace: observability
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
