global:
  image:
    tag: "v2.13.3"
  logging:
    format: json
server:
  extraArgs:
    - --insecure

configs:
  cmp:
    plugins:
      kustomize-load-restrictions-none:
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build --load-restrictor LoadRestrictionsNone"]

  repositories:
    falkordb-dbaas:
      url: https://github.com/FalkorDB/falkordb-dbaas

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: ctrl-plane-observability-stack
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: 94-add-app-plane-observability-stack
        path: tofu/gcp/observability_stack/control_plane/k8s/argocd
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: app-plane-observability-stack
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: 94-add-app-plane-observability-stack
        path: tofu/gcp/observability_stack/app_plane/argocd
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}
