
global:
  image:
    tag: "v2.13.3"
  logging:
    format: json
server:
  extraArgs:
  - --insecure


cmp:
  repositories:
    falkordb-dbaas:
      url: https://github.com/FalkorDB/falkordb-dbaas


extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: observability-stack
    spec:
      goTemplate: true
      goTemplateOptions: ["missingkey=error"]
      generators:
      - clusters: 
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      template:
        metadata:
          name: '{{`{{.name | replace "_" "-"}}`}}-observability-stack'
        spec:
          project: default
          source:
            repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
            targetRevision: HEAD
            path: tofu/gcp/observability_stack/app_plane/argocd
          destination:
            server: '{{`{{.server}}`}}'
            namespace: observability