---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    enrollment-key: AgAe6rCMUrFpoFvLHox/BWnB+WhHYUcBOW/QuLFGRW43mRecTDto0VgMIFBnm98KTr4ipGK7yx/nXlTeCXwAlccS1QVF22bQKCWzY5T84tZrMKrvdYs5jcmZliS2ISqECnzpoqKq/ODbkGA5PRfPQYAcwxjei6J3SFeVwHjo4kfHDmfe2T7bdqqe5icFJ5yzuCP6CL6BpCUalcAFhh8hAFj/vDtK1xipJPuT+fcMPnk3hDz0Pt/iRRSKV6DsZoHzjWnPDDK14RncOKVZUUhWofHK0l/1Bkcg/StqAu/iVfjmtenGrDi60KCrn9VIBa+X2U7cLh9bucUZV1hVfwAiwQ9yWYuaesLkhEShFWkZSCe0TlGWstriR0eXjflojwK6OwA177KwFxpmAAR2Nzesw9UFon9nLjto/oKJ4yYU2JQYo/q7Au2WwtD9T3Ig6wgQU0CzN6zAKuDQvzngsteIeFAnuleNpvd/mChs3Zzz2tW63xAKWHxmCZLJrr/LyhuaR1RdMbvkIAyKBiz/0gDHfKUgyrTpTQre7rFimCTgXfYuJ99oq1iY80gVAGXy8V43nQ8OwnSF3XSWhACE1DvOPuwvoXhASj7NocCaFGcn4HxDYQynMDdyyjDDrUIWmQ/ruFaHyCBp3srspm94bUWEqnrJFxVACv8PaPwnTbzXnTpeRfNEb3NQ1GE/wCosPEQfeSpUfrGYSm/yFlcO
    manager-ip: AgAIusi8QVv0vmndkFNV1s2J7sljvWL93Re/NN05VdYRrlwNBxDTHWeRjSGQMeuGKZZD/0/UIG1wxnxsIdC3F8eqdg5nO/MjkTIEezBkoLb+jyzNsOcmY4I5lP44GQFt8DALKhoAzu7PMbe3tSpxrj23XQX6Gt124VH8WbST+jjYxQaF5EbMIbqtaoCh4oCAUYym9P2rKm/qFx5wwTfEmJuQtHh2hpY4N1QeXxFl/++y6nlPba/Nd0MvsOLThIbL+zlp531lGjpQghWgOr0tI+QCmN1v3lGjhc37piarfaq88L00EhFc7aa5xAMi4uU7DrPEJdymNuuua6/bwZ7T7T3jiJRWTLCQ6QBBEJK9MaXhyTa4hgTMpU+MuwsS9SN/plmztDGu1/jl8j6kM7qG4XmCqz6PWrzen65oJLDaJS7Pk/+WYMeUlMpz+/L+zxvlKPRdgcYr+EANy7g7kuu/3C5T9dLybTlvk1nniKADBMlb7HnxL+e4BEIuq8+ftYkrJf4+LwVzLmEtfwv0B+SzISlRt2e+3t3PtYcDKw8tdb+UvEvDmhUy8KcOQocWAZSFOpuEMyoo0a3TcqClx/7AVVB/yHzijtBHeT7PnV8RdnQ4E7+nGH7mhq6bXC4sy9jY98c1j8ImmdWAYzHhpREh5YLpFoQBR4ne8/AcubjikllvdgPACBBWldXOEQOGNSrI/7RPS0UqPoF8/tx7
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security

