---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    enrollment-key: AgBxtehdpm4RXqb78inkCf1skNyPgCPaUHn2tNkt3G0YMUW6hZduoRNXMjLvzt02qHwgCZM25GDPLaw6djm2s4j/g1feZGwIj/c8yAO6u1gifu99VCuZ6ThUtl+a2AavuIZJjdjb23KwHn08pmqm+F4mat78UXC69vH6NQQA1APL280IlMwTF8tHc2Pn5dVnCUfvPEBbE93N7h7cLYaFN/oaHZCmUPV7URQhFuplYs+ZvtJc5s1YxyLOhRg2d3ILhG4L5JTuXHtWDpIzTsnHg8O7q3CmjxpEzwzSlDZTUGz0GDxTsje+jD6e8FjpiotbJEGb9LyNgoaBXHGoJj95uvwvM1LhQgH53WAWp2JQOVOLSdPkFKN+FjgFyGnmj7VEWlN5MocYGJdpcAZ6RhVI3WUXvPXla23j5Kncxbxzhz1Q0gAog1a1+zWtvcgFONcv5lO3xBVpGnmSuNFc0Xpt1neDPKAjWUXnNuo6lpDM/0owj1yTJtIWWDfD6wtefE6a7he1Sfw5J/qcWoZwjaQtlcZWY7iethuc4Djh5xUlOmltAAuuW+EvLlqPCEoEEr+z1x4YwiAeL5E3rLz8CWqf5mMjrWfF7Ftn368WRuMQ+AIdtmH97CzbjACpmZjzbyMDRRQv/dg5H4XiTXr0zbNmk8hT+7QLzOrbsst1XG4xks9JxNUf0DHGEnYMke+AS6JoGt6y4Q8CLeHuSqWFe9L+PJssX1qXKZkwA2OIEDqThuWl6K1WZZuPNkwH45qbwjXdg+wedMG/oCjBljyeJVk1zO0J
    manager-ip: AgCrwGZHlcAXGCkiwNjXUoI2V0kW0bnd4d625wroAJxnLv6wAmIUaO2KXp/aeCquKwtUWXuYem0sVb5VYth0AyIAZ/XVNlZ0PiqwxEPNbA+LdrZQWCFPWVGhy94p3Yi2SgvH9ZufFCGnZR60dwX5JWyUr0eAT6cjTcGkPbuw1OEXR3egQbXvhX5hZk6k1ifJjdumaEeNOg0FXwgvum8+e8yt5Q255iSI//eFLhw5segKwl0eik4GYn8voZ9vy+/i8+ZA2xsa8tNHLv8ncyKSlTMghJS1CrrDX+8e0Q604pGsEBZEeD6VOdJKyWanF/MHNjWd9sLEJWwKZNOcY4dl49BA/7cEi2fB1J4VT/SEIlM4DOI5ykFuPD/teveLleE0wMUUeCnpwDLwdvaikiWYt2moqaydrRy1I5H1lqHDPia6H6N7uq42GxWk5tcMeNzGht6a1dnR+Qg/QQureb1A509Yt+oddR8ZSkCuWlZ/fp3R6BsdP02HqYrbNdkHi1BlnjnZr5ldd7iZGodNDgd5wzECEU/YOazY8xD3TcXFz8C1Khop6NifUfwtOAlLhj7l/V5RbnULuGRH/2Nm6+UrX9D3iGXO6ffdVnkI398LGHrBHy64STx5xibNARJ0PjErd8sc+mES0T48scr6025Tm10MrdHsht0KIIHUePzr5mROlmEfdfsiGrzoOugsCYiwBYuukuR4mpe7NQMf8gkU
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security
