---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    registration-password: AgAczzrDmgyYjyhyjvVqSP0uIPO/ooHpkxuUGts2YZ4CabAOeiroddF/jEvoe5SoNJb8sKmD67etEYTokkbTI75dmgoBzjpjGG5XI4G9dHLfo9g4aayPolwRQZMwietO+a3JeIU/Rt+wcNgU58r0aOhb1cCkCoRRuC+KfcCCYsivaXwzFzpSfzqrtcNZ6ev6e2Mg+JQBr9A9f+TEY99wD+7K3427WInM/p6i97sJRgAoOQAi0jMJ8c20i4x8gRYpThjkjwlfPnqc9J41mqkdnNB7MmUZsxKH/aJEwE6z7vz3T2LDRBvs/ENxPxCn60IMBiX60jVrh9nGlSwYqMstb7ExWYCvrLYFoWI87sd1vDfgPGyeeyFuaslaObdpfpPKlUU7FTjoI/FvxgqBWu3hWzKFMnTVXfgRLYpJeazturwB9b7smHeOTI2bYPWmt1+LXnJ/vRdSKa9K8r5IpKPrS65XxJVEZLNfOIZ8+5b4IR6jFxUDYEBn6xk/b2v6tfOaesGkK9s3fTWVQh2RmMLrwE/QTL5ptFp/7eEBIn/N08t+YQcNEDC02/m9d/wRge+lOBNH9gPN2+vo0SBM7DRUVrwlaYTZOc7VdJwyr9VtCqUGZ0Pc7IIJCruHl7yxTkkDBbwm4ft+XHHObZvyyibxzlSbl3X05Y7W4N4LEBHU3XMVqTN+wA2ms9OOn+zQiVbCIS376T7H6ZRocsnbRo04t1CGTj7fHXZ/S574UHqHGV6LMhF7NDiOr0LLOVKI3kMDCYJVLAwM7TZ+D5p7Eec/IRRG
    wazuh-manager: AgAGAlwIGfNByd3FqFHUCo3Ebcd5DSO36B66uB7l1NA8GsEk8mDgmJurZYOfRHj/BsfbP1hQgxuvPZEXj9Tql4Ox9FrOcQLI7kQpl3NqPaxzcT4jAigiH4PJDO+tZIer5UFHOyQPXHuvpNHECJVK6Sn6PnfUW9a5DJjUv4D3cfdKFulKMbVFcuTYodmO1qjfM6fiLTrhVSftp8H/DpmBaDgkkhV3CUXQNvcezTSS/hGwDq5qFCvZM7wCHzZHeZMlO5P3y6mW3cxO0sCe7fpegfmZIr8eFh/UZg2RBAXMRF8II0KhdB9Ug5yBG92zwDHCzATN134foGP5cs1g117x4FKldfXHIjHJT+CsZPryYzznXkGdmdMfIHYrQqVmg36Ia4dgLtlR3OdJjDhJ2L3j3W8V4qnpvwAd1N51MDHpvL6E+SIhvyTXJkms3GwpLFz3EsEQ14DPzkkGFAmo4vzHqrvQLJ+/8/4AkbpIY+QTzYic5r5F9FCGcpbQMjvuYOhlx+BIb8RzgFG9Yba+Sa3H+uLbxIpCrmtRZlqfmUMNPRVuLE53lMuGUIZ9xuCUiMemo6u3hgzMGPPGhlzxOcywGQ6Z632pmI6FTHDY2LCJFF6OglsjJExFC/a5nmBK+1fww6rdDbBuGRsr2istW6o44BnksUwKyrI+xyZmNZ+Tjk9aJ0skAtOITCpZp8LzOiuoMkoSCfxdAcfhHm1TZ5nk
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security
