apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - serviceaccount.yaml
  - cronjob.yaml
configMapGenerator:
  - name: compliance-report-script
    files:
      - generate_compliance_report.sh
generatorOptions:
  disableNameSuffixHash: true
