apiVersion: batch/v1
kind: Job
metadata:
  name: ldap-auth-create-admin
  namespace: ldap-auth
  labels:
    app: ldap-auth
    component: admin-setup
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: ldap-auth
        component: admin-setup
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-admin
        image: docker.io/falkordb/ldap-auth-rs:0.2.0
        command:
        - /bin/sh
        - -c
        - |
          set -e
          export LDAP_AUTH_URL="https://ldap-auth-service:8080"
          export LDAP_AUTH_INSECURE=true
          echo "Waiting for LDAP auth server to be ready..."
          
          # Wait for the server to be healthy
          until ldap-auth-cli health; do
            echo "LDAP auth server not ready yet, retrying in 5 seconds..."
            sleep 5
          done
          
          echo "LDAP auth server is ready!"
          echo "Creating admin user..."
          
          # Create the admin user (gracefully handle if already exists)
          if ldap-auth-cli user create --org admin --username admin --password "$LDAP_ADMIN_PASSWORD" 2>&1 | tee /tmp/output.txt; then
            echo "Admin user created successfully!"
          else
            if grep -q "409 Conflict\|already exists" /tmp/output.txt; then
              echo "Admin user already exists, skipping creation."
              exit 0
            else
              echo "Failed to create admin user"
              cat /tmp/output.txt
              exit 1
            fi
          fi
        env:
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-auth-admin-secret
              key: LDAP_ADMIN_PASSWORD
        - name: LDAP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ldap-auth-secrets
              key: API_BEARER_TOKEN
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL