apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: ldap-auth-admin-secret
  namespace: ldap-auth
  labels:
    app.kubernetes.io/component: secrets
spec:
  fields:
  - fieldName: LDAP_ADMIN_PASSWORD
    length: "16"
    encoding: base64url