---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: security
spec:
  encryptedData:
    API_PASSWORD: AgB992Vr3j7bac/Ueanw/psVJYZ38hwUXdI/dHJ19ge6lXuuzcupO786JEpCDL1fDUTGySMbCjA76bInM1jyvtXcTsvL0jIedhegKCsaH81d4hUv2onR2uiVoQDsFIGnum3x+lX6jV+M+VibjIhGM2iXZDItMuraPhbI20vvSsvQggmccjLmSKqH7EHqpsN6vnS620ZsuD0eTLFc+/bGMIHmkAjD08MhWoaxYKXmKBT5ZOpD2NnX+zZQ0OWSzHVNsO0rgcfkMzWe7f9OQzlAugFwkuqDWT+er9jpGohJnXAKWjV7T8IBOWjKtFoqjY3bJ4nGc4wSvpp7hVfB+FE30DERAQ7SLoB6ryafGn53d52oPzaGaC/XkH9w/Uw8N0Vc+WNmNm1qOoYl+fa/u6Yl/VJAkuCDfBZs6YwXAOzjVH9ErxtbF1l7gU/wLT8V701ZHKOwzXICwLEcfNKLv3LFU/UIyQwdf+F1EpwyNjpfzaq9+OMxq+rNIHvAVCCPXdJY07wef97EJ91pd9xm2ke+PEsXjpkIBgQYGaMwLrbu35Uhnc9DUHBqhcqMkT5IXeArGcg3PzNYlWBbHceccLkXy1V/nauW+U9zWm+unCbu8XFKkmovscbMT8fJYCPkSFHvcyGhxUpGgapX66QtMcMed3yW3WvrJf8iTktw6RxR8likCPihkKIakkPgHNqakf5iqXKOHYyQOiErbXysQZeIQsaaqd42mh3X/iifXC53d570R7mxafRdkDO+M6hlZ+We08CS+AKEMxS7dRJrIo3RIr0Q
    API_USERNAME: AgACD/OryKnVwUrEgE8Fdq0yVa4dgW8oQFxLFJwsHX0BUySVPc/3P/SrnOBxlHCMkc8dVZNonMy75LXisTV80bcEe68oDOVdnQra2XwfciPPMLmWY6+rc7GsCQajZyThcg9rC5v0A8smG5MCtc+tEzxz54D07bcenauVmLF7A1QSNPu37QF6s88CQEecKkgbm0Jj8Vmgp4tG/H8uj1yVmWzZvDCgBdlDbwfqr13F4gj7lsN/kYA4UnfZfJKTnJWD/2sSAwKLns0EWe4xdg7nb9iOttdd1QZEsux+4/wMfnYpMswWca5L5ETdUUJ0JxLL9f5AuCAfGjKZJsQ2I7lPuKF0jheEJmVe/C1lu8QD9TMIjMOxpXU6A0UfP4+hUjOaP2MlPaR7iMcduD2vNEDd7AFTWyXr8bC14+GeIOGMhSngj4htf2FSewY3vX7UooCpvoW508OeqMDJgeWH1sbs9qWBG+hAYeaNWXS+aXUgrPeac+hJpMl8eWeDeRWb1HI9kNgBIZ43ndJ1iKnPUxY1NQT/Fhspyqmk9QFPHWvU9CV7Do5+znHiK5Y3vCyqTHsuVO7ZRkCLown1AmiSDN0G6sujVoy1T0oTOpYxUMBMsehcIF7Dh/OtkWDHq0kiaEo4MRdK8yPnNjoqermbUkvIZFzfxFUv2/VgEXBnsoBWWg5PoyBmGuZuFv4B6CN6R5PKm4gi8ZryIFHiwlo=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: security
