---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: security
spec:
  encryptedData:
    API_PASSWORD: AgAQG8Ao/vHcpq3+H0N+cLUzwkreF1D9TpSXYXeEDIIGSqWvW2aaPg9nH8Uj+pcsdTlbSmuL0Jfyyjha/IMrP/AWt0odhlUSBlQ7aVLnwtV2VXoAI6nABANRmDc2rB9oXA/VCQ3Gl1iMmZ9FLAsiT2Uuv8YPOLuABP/zREy/SGBcPaSaY2fTJN4dJyVeGIw/0NaR1/nFgZTdHwKLp0eeLDPZ9GIZAggArn4evBneDQKSRHuP2aVitKgE8jIqlcWy6f6FLuJbdRbIKfI8ekKPU7UKC6XBoN6B1NdhmFIbfYkp2Y8OpTKfNlcp/uy2QrMNjHueqXN6CQtviREm8SPDBJOM1Q+uFfrotXs5eFi58dPlsMTtE7QVm8JUQ4gLN+cGaRydwDz3G1YhxXMPk98eov4rPBW+GbdBxs79f45SVX2X5LPQxpoyq0+nr5P5sM/TFP7MvE8Ir4PrQL8J+G9M22+vxX/VW5YuLqmCUZwga7Y/nczjVjh4Iqpw7F3sPWwyJzoqZ7q4+HZfGkwjZJEAPEuvpfTATzsL/mYbOWOqHAB/OboaTTGy9zJ/hFlt6XfII1q1m1lSfpjPaaC6bRkEvTN7lXej8ZitfWg0NMKL9D6uPXl+Nj+DRSWufmLKGan9ATmNsd+J5Evv/imhES+6ZJVIJToSmJxSxK8D5EgqPJNScUXa5QTvc7YqP5NFa1ONeuHnRK3t9JpTqRODyADXrq5OeteLr7OkMGunt0oOU0aPwxln001f36iuWmV+FMM9XvAejI5XbK8IY4Be3X0+hozq
    API_USERNAME: AgBL4StGXdDRxCMd89HwTYXKbkYRQwRxmLpBdYcW0+djGNxX6sZC56lVtKGmATIefDEL7ges2Jbx3MH9fMQ3oft21xGfzld7GfknplxZPpg++45PZ9RvnP0EW30v5NdLVzSkQCimpQj/ORPz+5GNGGtL88fX+EPijQeuQf+z0wmfA2fjG8LRxrmaxGeNQjtrEM5RpXkDqDkYVl/BI2/JlTC3wxrdJXXJuWKoFJc2sYTqj5yHx5cI+26E9FCK5JnaNmOis7lsjdeZi81SscIMhKIyuDNEI0p2w2BzWkKHPnxhXgTPfH4b3prmFhIH3FVjR74oGNe1oZLE5ABrYS7kWabljNb9V+Cd5BO/olCobIp+suzpTRGh84T5q0eVzVCWB0H7/tJT81L143Q2G4+VeIV1TUzWI7LMomPmMPJHwj+VeWrYcmHHYXD1dDH1wd1BFnD6DQe7YLMMeiY4mCwc9lkJ+m7HI8c4rmA0+yBPjZCV9XV1QMPpV3Y11LVODVRB7TGm35C348MjqstP7Rp9DCIY3UnAthe8Qnjamers69FI8zFtjRvGPDAbIZzvucEQOfWnfYlnjw8jPf6whu+Z3iaRnTlard9IYiDthNgV3v5rZPauRDhq7AgFfzsoNbTlpT0sBukBv9pZDBMO2HWAAsAHEMjI+YlE7nAO1vR+75iwynYBZS/LKqDQRpNCwyz9tPsZ4ZsKZSoO5UY=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: security
