---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-manager-authd
  namespace: security
spec:
  encryptedData:
    authd.pass: AgC9AIw7UwCyLgJKLDN9IEmwqdr3bvMrqB0hyKt/e8KvKHC4PHI8qaqBlE+QI3OTnns/3HRmiL0jSaNvcLgQ9hRFZq1tYIulYkXeBy4CHCryvSUAwpuNxUGbIUICBJB6EindIF1y/TUnyFypMXj3SOCtaOIMmSqMdGvlVHkYjIqdivibb/250n7A+3SavbJ6rgJlB9oamH6uF9Wt9nTj2UBN0KrWt76zQv+uitbP1yin6WdFEJEd6NSMNaIp31l7s4cTVaeJ8TWrDjJrFHUP5j2QCgtjd9MIGoFp/J5wmaBiLEpHbS4k4c98NsHAH9/ELPENEI4Uz4Ffg0TsmBsiNy+RYEqNrSbvrL9LizButLNKPsHEL2nV2U82aDy2VjiWhRbHolqcZyrg2VjHeEm/EFV9zJyHKUJyHBmTT2/AopCDf4R66rTjUFsafWZ5dIYkUMG0JidrEv/ZgTH/h2aASxgEEW7VcBg0wh4U3avqztlzFWdYjtn3wJ8upn2VXqgDRR2VIZ3eGQbPOsHwUoJdnw7U4LgA7/SB3Nf3+Fh2poOK3dO/GluLFtsYOp5WKym0a5qAHLF8ztygUKgJEv1jKe1LVg3OBOR6dI2ZLOQ7Y9+8y+aP+m0rY6fjeSzdDZqXnzNkrDiS1n6Vtbq4GcplqODJuaGlu/EMXDCGc9kjZ2m/Mac/hJL2eKrdfufvj8PKyR2YvDWI9e7Sb5/CTGtzBX2VpqPQWxGj5U0YYUP9wuYFVug7M8o1xC+ox4YwYwsXxL0KJN1OsNx7mPD2aiJuSq84
  template:
    metadata:
      name: wazuh-manager-authd
      namespace: security
