---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-manager-authd
  namespace: security
spec:
  encryptedData:
    WAZUH_AUTHD_PASS: AgAx65uC+Sx/rywo8RDqoEW66WgW5nsEejfXGab1TL1uuEsJDInPl4Jp5gxtQrLIY6HAjiuxIHh2jT32IREIJJNlx+T36JC4L3ikIGaeiM+oRx9yEIs9lALL6Z0x3LipyrcwRtiFMi6DHAksgd5IF/GVPNXM+66WAY1Lkk4b5HDl7977FiNDPrmrP/8ETgAFCMNNAaYv0ZyVDQb1++RAQNU+YxtO78SxQDZ9ViOIPIQJW6br5v9FzmfUKBWYX0HmKvMdwzgaWvP27k0Zka9drvnL6EC1gmBLGwTCr16Dk/JfcHH1q49noAvbkhqXKBuRL7kV/vJXQcEy9XNAK23PdF70cKrInr7reqnaSjcfR+9+rxloSbjdo6J2LaPwFrtPco8kiJeFP0nA6fcAJSRKBKHHTnBQdZvNB6xlJiZjOmqt/93nDVx+4V7TYAYBbQ4CsFeggTxBWl0PzjVYYei+fUyvo+noYztTlhPrXGf31Ib9WfJKI/w42iyMREc/UXHhhMnx8WP9f5OQ6BQujebItgxb5gr2oF3nR4vyt+gcwTWiOMZmf/TvA4hfXrd09/YX20dDqUmtLtLKk6/NacNH18jHsluqUCneT49+QzFehoT/GlscqbCdEaUGVluXBobl9nGBpF02y/AZQx4yNea9Ftl0bWXB1HC2sjDxDRt5KAzWRQ8a4xWPrEkDaHk/yfC2FsXRRZERovSCwOoj96DzfUeL2bY1oK4yH0Sv2ILGvpfF3g24YiWS99nKMpwza2uiMFr818aWQiQh98Lf1IUnV3w7
  template:
    metadata:
      name: wazuh-manager-authd
      namespace: security
