apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: grype-config
    behavior: create
    literals:
      - cluster-name=app-plane-gcp-prod
      - wazuh-syslog-host=REPLACE_WITH_PROD_WAZUH_IP
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: wi-patch.yaml
