---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBL6f/J44/0ZwiSfxzP3M6ppMzPgZ1BviU4J/5/GKovPNfayFh5AmpDbw61uZZEHz3t+9b7MrPfp71oVJcgmsYZHyPifKFMxsvl1vB64QyopHyXXE4Ppt2w7utapSCx5id4C3bOi2Yyx+lyazZH2uUNvWEENm6Haj/a9v9+6s3JoiYMQsaTt1Cn1hVNjV/2gEcYm+ST/H9uCidLi6RVg3OiFYQ4k+qKASkVJ9kAIT0Kz3FAonypoU8LHSbmoiHubJ3olho4CEg68cKDfjDbTwxKjwj+U8qYPG1dtz8E/Qd0Y6o5cCyISG8S//6oW4Bbbxjl3eAikqoc+KPkXxqzmpTYa9s+kZ2f38ko7NVI8cOqItBQQ7ZEmauVGU2YNxjxDHAPjvXqzuXDbXSbCslhX5ndjFT8jTqeWQPoKS2/OFaoiAZcxjcUH4Np1uvAzIdQVOarPZbC5lAQ42gPtgeivVhOHJpno0qAXGBT2j/Oiie3W9svCyV6yw1Vd6/2GkxfWInlnwIr12zgxXM7S7Gh01qLI5PjImKH2POh116vkpEtSIIJ6A0M2YZIC4nq7FU7YS2TplUbcokvST5kiLfJbeOhpNRK+lIvQSejPNIq9de6SLrBFzGz7qHkHH1C6sHwanxD1CXhH/P2IkkWFgywkIwGKVsV7P3LLmEvSfcQrYlzp6r+GzGD9M95QOh1cDiKV0q/0z1RYIFgJpAKorjDEsfctn3Zg1wq9VuVLqOqSg==
  template:
    metadata:
      name: kube-bench-infra
      namespace: security
