---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgCMbGZ51c+uXEGJ7Am9Z780UZPAxIYhD6GbbTIwcpTwhepfdKKip0d2WVGILiIm4xxPJArxv7bxrrsrQghg8VsSN8kR/9qhqPFjrf4PXKDvIswFoYPF4hCP9GwlI6wjKQhPDP32Y3guFBgZhAVZgqJcuzu9WeQ+V2yinuYpHemlnr0W8LJ7KVs0Kiu5hgt/8/Ca0pI+YPzI1rgLb2DEnRA0BY8mDC02G14NWbpK7IW/gJhdZOVCcmxpBK0SxaPy70RFaqnM47afT93KtUZCaesgnLzDLO0OHytRYgJzB1RQfCXQnUzVuAePegEUF4xjvyYsipX3l91jP5ojQMvRR/eLO18obD9ISuGDB1ImA9o066K04Ei2kYgbYBgbufE2VgxRTzoB0wu7FOozVk3V3+u5gzlOE433Pa6Rctb4YvuW6ib61XrtlC+ub8VBslOpT72cXtBNbqR+KYeG1jCYLseRWhBfCtHsw2bEDBJO1DlZnC+ZD0+cdYi0JEgwAHWJWoOFuHppgH9SPHvjPbHNK5vhnIqUqzdzAw+loWHnhUPkKA7+PXY1uajyWk8q8wvXHIeWm4srczmgfB9qyJf6JX4uCHRf10RPXaXSNyQSvxRdwPEBSSfAIYFxsUNpvoMvg3ND5KsAqGk8gZ9mhGlrlPSXQvmeJdD/9zQMXbm7qcKO6Tke1V596h0fO+UfyIAv0VC2cgC8gi0rbjjy
  template:
    metadata:
      name: prowler-infra
      namespace: security

