---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgA7vvVHzbXc2JAIwU5SoFZZaPLj5KxTQP1nN3fYurmWT27uJL+/w829i38hUDVLoE3mMml+QqZ4FU28aKXVb01pM5UEXG0kiSbw7k8t1LvemDPwnsLpFriEg5l9oj4xs4qf3+4iry/zR5YwR34B8V1tDBT/MfD3nZ78Svwvl5t3EvRRLBDyOU6u1E6vHLuoobX+LbaU8mkkR0IbYAA81VZzrornLfA5/wVg9PPqQqPSWbgobKFg0iMSU5HqV2i9tQCQ1HhIf60Vd8sPWmqr9DW7ZObVfHVldAfgdOIeAqhQEa5mJVDLOXCaO2h49XX/5CHe6fcwEIY/nPdlWL62Gi7XXM3o2NVPs6454Kjh7KGfEO5k8VQlkdS1tb4WSyh/vE91EIghMDCC22Y/OwCb0a0jHpyo8KBk1z+HHL93XrkFpRUq71eB+EM06PoHWKIhdjpMbO7os6Qmv9WLIQyI+yTsNV7HEcRbGucaQjxqjox19jrKMoUDxCtprHeMPPDS1T+fJrX7WLc3ca7sfdGer2R81trH8anH8fiX6oj17NNDQubLuNrpJH7T/7bd/gIkG+N/hVepQWz2K4gJ65W0k6fPSAD7O/x6yiPc5ippJxyyUxJ/gfZFdYsi7+rKgpORuUn/JzYL7lMrYZHYhSO4EueEkixq9pTmFpp6rzD/51tYNbG2kp1W06r6TL5fmlW9ff5zImI+K/wj3HPEbfRhZ/WnoQX4G/eRkBuji0ecUw==
  template:
    metadata:
      name: prowler-infra
      namespace: security
