---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgArTz8EGZqe2qyVc1k4pAUwqFW83QzKm6fQ/5CsVxCujGf923tVsKvxOudTe26QgvZh+G6iFjs6ditYA9wiH7AAHlvEAFA41RDNumPmkIET33JZzbJgZrs7lws1PeWPqE3McOrAvsUqDSgddvNMJ7hTJI/HueL4IYw4hfw5fK9Sf0FPc2kHhndmDCfrNBqJ3nNoGC9+s8hTyXjNhO0n58ERvG4SNYpuI6rxt56WKwskHT1omw9x8GzYK8840g6SLs8tR/kXyZEWf/bsdebIl176Q/+z6aS8IWuYtv9GFUgVPMT0T0hOLbvLqqjBDxJ1NXb1rz5TTAqwCn+YTFFvrX+qAn5s12E0m4etRuEfDwXwvyoTR+V/YlzYV82dPzXeK4ixgsA5/Uo1drXq6o9tLE5kFj4WIa48LtHvspu8pvK64uF3NAtdaflrF1Slb3s9jA98E+wOvDKsyor0vYELSGwbSH1D1LvF3i0v3KeagIfa0MN37VEZR7ZOFvg7F8zKduDuQxUnuIhnI2R2f/+WfICV9hm617cI/FlhNFtp86Zcoh3M6qiqPUY7mWGpXw0iLZsGWmiC0XeZ3fuy5qgNfY4XDYeHgfrQ4u2QGrcdarQ1wUEWiySYm8UpO0272I0l6L1tYYApa+opAR8QH0GUVhqHT7L3ZcHvyUjiAtdn5Fs01sSVlhn9gHYlNI/2fvGhaG+ekMozMh9gZGu5
  template:
    metadata:
      name: prowler-infra
      namespace: security

