apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
patches:
  - path: ca-volume-patch.yaml
configMapGenerator:
  - name: wazuh-agent-config
    behavior: create
    literals:
      - agent-group=ctrl-plane-prod
generatorOptions:
  disableNameSuffixHash: true
