---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    enrollment-key: AgCWmUu9m8M43egxxZEDU4hJKRBwhPP0/pA4nD82o4F0Cb+apo1m+6KrXzsj3f0nKw0kQW/xPaSZ3LbUxBG2nAaecdnpbDWFI646xb8zFTM1kE7vOQKmxo6aY1vcoYgxdwT1EaEm7xZFPss5ewBlHZqSHsoOJ/WpldMRxUL5ZjFQXhMzFFG7Qhy10eXuwFQKX45P4E/QMDU3THU59sZdy2p0o6uGIp9qR1+2H+BOTUUYb33yBaNri6q1sXKNxa+3jvg9eARXncK5LwnJ1oLtZdjcCM9seENvPOYT6r5ZMjDWqg6998idRVLqGatNxlG9K5/7JUeUQyAsliidWB2Dg/EUbFGE0T1O0DhSEgHzYF0nA+a7k722tNVmLavmFFGdPas8WwFsNkQjOnePoCG0BIvqILgU6cF1vXRW2OV40QycJp8aujoLmyPWY250j8dZrRCAmAEracQmA1Bh+zhCPD8808fbOHuCAAnxpRGvoZNimgFVzmrVWfXKvCo/EiDAwQvMiKpAujRzpMkg1D00E38P6xXOSTvWcz2L/9LKw1PFRr+47sST8rQMjzmXE21Qc9X9jG3yYYS2/swxq7V6lGa/VdGlc/CIo8a3fVxhn4r4l4DYUQwq4sdL34HV03Cc+ljdaeGshsqzD84qsA+udusFA9eCQe3hM6zEbrIPTbVxxcjHRqipLC3iUHsjA2b5nEhsxE4KMBRcIgC3
    manager-ip: AgAA8E4cUSaW8EgOR8cyV3otRxVuF61wfypDdirIwbQ0PC97uNjbQVRsxtoh6fIYnnHAXjL4Mu7lt6MkiBoT/1WEmGw7Hmguq0SedLQKPXhKCDEaBPDVnQ1d0vAeOjyHxcbc6wZbKnl5ynLLgZ0A4MeJxGbNI2rCvDE6oyII8ljmazwOSi72Nna3TUWEm8b+w3vxHDRfPczF8hSEJYl5672eENzOSihabkMlappHcENBT5xrN6UoDu9O2+jpHVdKgimWVj4G9QkAUR5SDpWMczU/17XP41sjTfj1CV2RRK52jyhMoEEXul95WWzQ+jKLa3hQr3tIQhQ95WrXX1lCtQcgsQnuVVM0qdBqk3H6pov6cMfsOkLcxoRF5vzY/yJ8g4ZseAF5y6eS5o15P8X4dVT9/bm2AJR3Ts6HaZcDhU648B+snZSso8pH+D0hYlYxt2v2HV6Vh4OrMSr+9p4db9rV+TxXWFiMklB59Q1qF8C93rRvO13fMxhEbj7eErFY6LmOF8GziO+sMq29mF/g7i+DyBjsvxmX7h1iMWhOCOEQ5i6y9oZ7IppSvdCyn237k9UJVhIKz5GBTciwT5N00CUOgb+G1xV9QT6GRwo0hysrY4SR9rjQ/Wu5+oNq5B0mWE3dG66FwdxMb5+HLH2wRBQDbl9TQq156oFG8GSAS1+/RqbnKhUUpl0yM3zcr9Xhfi1ceoVrSYyjpWg3
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security

