apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
configMapGenerator:
  - name: threatmapper-sensor-config
    behavior: create
    literals:
      - console-url=threatmapper.security.internal.falkordb.cloud
      - cluster-name=ctrl-plane-prod
generatorOptions:
  disableNameSuffixHash: true
