---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: threatmapper-sensor-key
  namespace: security
spec:
  encryptedData:
    api-key: AgBClUk4Q/HOOtTwgwRVApHtVfkKUlf+8BpVYWKtudK8OzNcnnBWqaEhGZw02daGTodG3qoaVURQUkgJHVW8aGbmKsHAXlNy45bulU34V0dVlSdm08LALpFxHOW90udY60Lx0x8zPtdF9Gr2iVZMAKkqhtOQDHDuCMOxRfttDeLAPhWT0IfM9kkYYet37qggZkg5FdAwoSpyoVUHhchwgwaJ4z+tfLcAEiy14Zhy+og51416d6qnqnNk9QxTumB0D6iaJ8L9MtUYPL6FyY9yr7SLPDfVcoFz2+H8aG0+pimM+wl4ruFPo1sqvYWTMUAVy+H/Ph4gKlnPeGWWoSGJHap1BpHoT2XsMo+UrWxr2yHiqxS202VyASkGmOsbE78kUqYsfSG5IS0FUGM73amNARB4MB2eFUEMtrkDBfNA7ZMVg6CbJgyqLr/ipk5zOQUhMC6QuEWvLPImWb1rmskcJzbQJRXHe51Uz8ulIEW8Rry4ONPbfy9wZwjeGOQrSO32CzlOqeIVYdZI78B7pLsMVBPTev7KTyzzSwRfQRfw8PKhDsy6kliB4Uq1k3oZnFkWacNfpmrzwrkdso0Toag4+c68LevwC1SZnK9r37hB8R0zZu40d5CKeIAIqIEwSUhnJEwOwXO9SJslrXwZmSFd+4tSjba9/NiFoMwHqvLYyfy9c1iyrs4lUZS2L5qIxRslU/TdjptaCow9zCbwxQtamyGVGlApuDqtg5MCfDerIWY6py69TBFQMhYJ
    console-url: AgBYHPVwz6TiiIqiqdjJVjYikidPPOaO3PyW/ABnIBdLu8+raernBUC24rVWuv20R31IbVzbRSKrtBVBq7MTTfog8O3job3SOWomqU88sDtBFdDNDTi0EdVynm30f8i4yARkt4rS2Xvi+xMI4FSF/5WliqWAXmjP5JYHTb4TRK1CatruSliELfRfN7dsw7tuCSqH5z0hpn26KDDBCqWyncuNdIK5EwIcdm+4gGrNTPOau9YzrV2nK67RZ0gtBX6ExFlrdrGCImTPDziXJl6QAibnz+mTu8OzezwJSQ0XqwPQg8j54tZ58Ekcc7J4LLzRNHJyJvobHHtDe0hvOkOtSRyOtTxeGfC+gC6odbDZ3CLtVU2FxHXsceSYX6h/aqdeq/dgUqEj3MSHGP+s+nBo4Cp0Co+MisX9monv0/VON7wnleqxg1mTghP+Jl/lP7yCReGCk9eTtYl2uMyuUVYREsR8sEOLWUoTBblwPY5HrKu40Sgot0wbq8iLWQS2oF+9kAgZMs4AVKf9IVw/snVwbmecrMmyySSLcpizbeUlv6SE5ZV45NH160KB3BCMrfYvy6fwFFjwupXh9q/NojgBT2Bm1FpPlKYB/1u1gr3NZSsW1tG7OiNJEvs5jPtTlcYPwaU/UpGYD1lUpCwwI1A6iCeAQhBrnWK+RamqSbxYzshRiefE0B4OFp/PFVlqUPvUl8F2oCF31n4RT1ygNw8zCO9AGf/vJde31ZiXObugRW3NS0qPWhaD5f3Yk8XJeRE=
  template:
    metadata:
      name: threatmapper-sensor-key
      namespace: security

