---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubescape-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAWBWyt/HaO6/oJArJ96m9eL92mQ7qF/74zJ6uXsaVbptxMXa9kOENaszGOnLzuKYN1oMsBlg60FPCK4Z0AoZhzXaLH7EH9Z0TbUiCL86nb9DY2CP8it/vITBpf1TZxrMq3Pxx73y7kPggksTm/QcQwPiadh47jLZPGudCn1dqMsEiT4SZdr7OimIaEPTT6Pt9HMq7fKDbsokil20WgyPz2meG7Kj+Qbkpe85f0hmTNlk7x6FjWa+UPUybS2uxTAcnf1OyDOTDvZ5htGa299TKRVD+uYGviDn+mBdl2xkCvwyyCC+ui1mLLqRUpgOB0QPjj9vkxNy+EjezKLN7SCIWszDM3LO9PtYkHgZFu0GT5I/+jYH144bhjmzKBMxttWt0qECjuFUZjwlb1M7JpmeZUzt7G9thV1UwasDGsdzMudpUl3/QGUNViGXQlw7+j901cl4D9yQ3TDYERg+hUEHiEaC7JgUCVOvd1jq73yw+mkg6QjDDij1UhjlFjuMSXKEvqYe4sjI5mR9C6DbIWwIaOup3yINHmGLYfcTq4fvnJcX4pnQ96Y/XeONRqAkdtqCnmxvioiUPWMgJI1d0E0LGp1gL1R6InRo3K/SuhOxQFRTiJv2pO6qJ0DI174S5F3/PlzDrm23/ikKqyGmDwAhmjn7L4LO8B2sakqV8rH8gdPG6Q2ODYD6002+m+K01MVihDI8BOpBALiCQKVjpKj0ieEAbcRb3cjO/vNOp4Fw==
  template:
    metadata:
      name: kubescape-infra
      namespace: security
