---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alert-silence-syncer-env
  namespace: observability
spec:
  encryptedData:
    ARGO_SILENCE_REPO_TARGET_REVISION: AgBQJLF7oHgLjUqTa3OYe6QDJI9hUSUTVlG8T61VlkV9BHLOFrBonu5yoQtyz9/Z1Flh/pIwP/wb+vPf9uWAeqPU53w+79aXe9fJz1NKXQsl4e/P7yAG9HWrrrc6rE6G7H74zbjE6zp7zrHm6l+gMALn/Ae8zWYcFitYePjORQdaP9sKphZJh6ztFlCaY/1vD0twhdM4QpQ/w1vqUmDyJRshxmdWdw9x1EsvAScTjem2NL+Ldv0bjwsTpb9lY2SNzyxgAcTg1MN0yEDaUyh1rxdMbGRpXKf+B9r8aQ6hjG4TNaIwKcCPkU+9irX3Yjxq+fp7hBRaTs5rMz8XOYcjFFVz4rhEqCU9JSd6vUN7Qz3XqocRLD80w/oOltpjrQRVjTL6xH1Xa3orgXt34g2sCE/s+V2YhW4RbYM07hMMxFnPpwojByKw+QbE9XyqiMP44VzTxgDfdcHGSd/sRffawcjsAgOve79jtRol69Vlz8PHQ/kzsek6YPxJ2Kp7AdsXzBWbbnBqab7xHUy3zsa5FzpNPTrPquxGfPwvqvwrH+0UICcFU6fKMBUIwDU3GnuUyTiomoWFeaRncuLk0oLbTUbPol00I1Y5RNl4izbV825iVlHOU59uOyRmuxwEIyMn3Dlaq3Klb/Gkboehl8nt44+99GG7C7NzlZnBREg8dLvn6cvFmF5DmAQKq7eiruN/bXI/FTk=
    SERVICE_NAME: AgA+oHxRMPRzhuceTkGYpZwF3WIzQzyMMRcNYGCGoVUiWHChGJPox+ZrolVTdE0O+xBjeH6xWldNBeuGsUYaPVWQYrpHrY3w2UK7jSSmzyEN1GHSo8PMx1csqnw+/D9rtaiVZkAlxc283TuQSdsKL5phuN8tZ7qxZIhcIUei/eKZNGgdNRu8TxVTB2Q9FF5kPocbCiFgesOxIB/iX7jxRO93EMzQb5iYDS4lViATEWSMw/Gc+N59JuMayhwqbwmKbNvUBjNeQvqIZ63B1XCzZyYhuS6f/hyBUfL6D7TvXDEIPEzcU4zkw0/HCIsW2WfHkZNeF3V+jkMg1tvoHNeNi9AQ3oHe7cl4xMx9HBpprvHTzL4MoApR7DqPGhSfyn0KfXAQe6PsewOAP4xTQFHvVuV0lTAN2VXFaIKKeqLvxtk8Ej5yBZpjsaRKgbAZs37DyITwSQfTgFz9NhssKq59Z37S0Ptzqrjl+UqkFn4JLBtcCapLTJTs2tvVuiP+vZ/+0lYNVKDHLCG1m3C7BM+Xsq8iQ/tbadZErP2xV+FfJXkIebDGTjE2bmkPc+kobIPXbtgIQ2rzjZEzb0HCX5CucCdxLdS+QA6twAgrkV/dawSGNpDigFFqts7PYyALthdTXHE9G4vZZDiPL1jiyftzDHXGXZNBTDSPtn1OP5MM5Pv+Ns/fZBN+cn7YN/JQEGV5TtNlvLDClZj4BEeaV13DGxICLFriLg==
  template:
    metadata:
      creationTimestamp: null
      name: alert-silence-syncer-env
      namespace: observability
