name: Build frontends

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/build-frontends.yaml
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/build-frontends.yaml
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"
  pull-requests: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{  github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22.x.x"
          cache: "pnpm"
          cache-dependency-path: frontend

      - name: Install pnpm
        working-directory: frontend
        run: pnpm i --frozen-lockfile

      - name: Docker Build
        id: build-push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./frontend
          file: ./frontend/apps/auth-proxy/Dockerfile
          push: false
          tags: us-central1-docker.pkg.dev/${{ secrets.TF_CTRL_PLANE_PROJECT_ID }}/frontend/auth-proxy-web:sha-${{ github.sha }}

  push:
    runs-on: ubuntu-latest
    environment: ${{  github.ref_name == 'main' && 'prod' || 'dev' }}
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    needs: build
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22.x.x"
          cache: "pnpm"
          cache-dependency-path: frontend

      - name: Install pnpm
        working-directory: frontend
        run: pnpm i --frozen-lockfile

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Docker Login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get version from package.json
        id: version
        run: echo "VERSION=$(node -p "require('./frontend/apps/auth-proxy/package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Set tags
        id: set-tags
        run: |
          BASE_IMAGE="us-central1-docker.pkg.dev/${{ secrets.TF_CTRL_PLANE_PROJECT_ID }}/frontend/auth-proxy-web"
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "TAGS=${BASE_IMAGE}:${{ steps.version.outputs.VERSION }}-dev.${{ github.run_number }},${BASE_IMAGE}:sha-${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "TAGS=${BASE_IMAGE}:${{ steps.version.outputs.VERSION }},${BASE_IMAGE}:sha-${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "TAGS=${BASE_IMAGE}:sha-${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create .env
        working-directory: frontend/apps/auth-proxy
        run: |
          echo "NEXT_PUBLIC_GRAFANA_URL=${{ vars.AUTH_PROXY_NEXT_PUBLIC_GRAFANA_URL }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY=${{ vars.AUTH_PROXY_NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.AUTH_PROXY_NEXT_PUBLIC_BASE_URL }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_IDP_CLIENT_ID=${{ vars.AUTH_PROXY_NEXT_PUBLIC_GOOGLE_IDP_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_GITHUB_IDP_CLIENT_ID=${{ vars.AUTH_PROXY_NEXT_PUBLIC_GITHUB_IDP_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_SAAS_BUILDER_BASE_URL=${{ vars.AUTH_PROXY_NEXT_PUBLIC_SAAS_BUILDER_BASE_URL }}" >> .env

      - name: Docker Build and Push
        id: build-push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./frontend
          file: ./frontend/apps/auth-proxy/Dockerfile
          push: true
          tags: ${{ steps.set-tags.outputs.TAGS }}

      - name: Grype image scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ fromJSON(steps.build-push.outputs.metadata)['image.name'] }}
          fail-build: "false"
          severity-cutoff: high
          output-format: table
