name: TESTING Apply AWS infrastructure

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./scripts

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PLAN_WORKFLOW_NAME: testing-plan-aws-infra.yaml

jobs:
  initialize-env:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v2

      - name: Init AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.TF_VAR_REGION }}

      - name: Set up Tofu
        uses: opentofu/setup-opentofu@v1.0.1

      - name: Init infrastructure
        run: ./tofu_init.sh

      - name: Get aws state file
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ env.PLAN_WORKFLOW_NAME }}
          pr: ${{ env.PR_NUMBER }}
          name: state-aws-${{ env.PR_NUMBER }}
          path: tofu/local-aws

      - name: Get environment file
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ env.PLAN_WORKFLOW_NAME }}
          pr: ${{ env.PR_NUMBER }}
          name: environment-${{ env.PR_NUMBER }}
          path: tofu/terraform.tfvars

  apply-and-test-aws-module:
    needs: [initialize-env]
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Apply infrastructure
        id: apply_infrastructure
        run: ./tofu_apply_aws.sh -- -auto-approve
        timeout-minutes: 20
        continue-on-error: true

      - name: Get EKS cluster credentials
        id: get_eks_credentials
        if: steps.apply_infrastructure.outcome == 'success'
        run: |
          ./aws_update_kubeconfig.sh ${{ env.PR_NUMBER }}

      - name: Check connection to EKS cluster
        if: steps.get_eks_credentials.outcome == 'success'
        run: |
          kubectl get nodes

  apply-and-test-k8s-module:
    needs: [initialize-env, apply-and-test-aws-module]
    if: needs.apply-and-test-aws-module.result == 'success'
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Apply k8s module
        id: apply_k8s_module
        run: ./tofu_apply_k8s.sh -- -auto-approve
        timeout-minutes: 20
        continue-on-error: true

      - name: Get LoadBalancer host
        if: steps.apply_k8s_module.outcome == 'success'
        id: lb
        run: |
          echo "host=$(kubectl get svc -n falkordb falkordb -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_ENV

      - name: Run python tests
        if: steps.apply_k8s_module.outcome == 'success'
        working-directory: .
        continue-on-error: true
        run: |
          FALKORDB_HOST=${{ steps.lb.outputs.host }}
          FALKORDB_PORT=6379
          FALKORDB_PASSWORD=${{ secrets.TF_VAR_FALKORDB_PASSWORD }}
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pytest

  destroy-infra:
    needs: [apply-and-test-aws-module, apply-and-test-k8s-module]
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Destroy infrastructure
        if: always()
        run: ./tofu_destroy.sh
